(() => {
const catalog = {
  zh: {
    views: { home: '所有会议', prepare: '准备录制', live: '正在录制', detail: '会议详情', settings: '设置' },
    labels: { '所有会议': '所有会议', '最近删除': '最近删除', '设置': '设置', '开始会议': '开始会议', '会议库': '会议库', '准备录制': '准备录制', '实时字幕': '实时字幕', '会议详情': '会议详情', '本地优先': '本地优先', '音频与文本仅保存在此设备': '音频与文本仅保存在此设备', '每一场对话，都留有依据。': '每一场对话，都留有依据。', '录音、逐字稿和纪要只在你明确操作时导出或发送。': '录音、逐字稿和纪要只在你明确操作时导出或发送。', '搜索会议、逐字稿或标签': '搜索会议、逐字稿或标签', '所有分类': '所有分类', '最近 30 天': '最近 30 天', '返回会议库': '返回会议库', '开始一场会议': '开始一场会议', '先确认语言与音频输入。模型会在开始前加载，录制过程不会因网络状态中断。': '先确认语言与音频输入。模型会在开始前加载，录制过程不会因网络状态中断。', '录制音频': '录制音频', '会议名称': '会议名称', '会议语言': '会议语言', '译文目标': '译文目标', '我的麦克风': '我的麦克风', '系统音频': '系统音频', '输入良好': '输入良好', '已就绪': '已就绪', '当前模型': '当前模型', '中文确认文本与说话人分离': '中文确认文本与说话人分离', '管理模型与术语': '管理模型与术语', '正在录制': '正在录制', '暂停': '暂停', '继续': '继续', '结束会议': '结束会议', '保持在当下': '保持在当下', '译文: 开': '译文: 开', '译文: 关': '译文: 关', '回到最新': '回到最新', '参与者': '参与者', '本场状态': '本场状态', '我': '我', '麦克风': '麦克风', '系统音频': '系统音频', '打开会议面板': '打开会议面板', '导出': '导出', '逐字稿': '逐字稿', '摘要': '摘要', '纪要与待办': '纪要与待办', '播放此段': '播放此段', '生成完整会议纪要': '生成完整会议纪要', '模型与本地数据': '模型与本地数据', '已安装模型': '已安装模型', '下载更多模型': '下载更多模型', '术语库': '术语库', '12 个词条可用于会议准备、搜索和纪要。仅支持的模型会将其用于转写。': '12 个词条可用于会议准备、搜索和纪要。仅支持的模型会将其用于转写。', '管理术语库': '管理术语库', '存储与隐私': '存储与隐私', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。', '查看本地存储': '查看本地存储', '中文': '中文', '英语': '英语', '不需要翻译': '不需要翻译', '自动检测': '自动检测', '切换语言': '切换语言', '切换主题': '切换主题', 'Brevia': 'Brevia', '向量数据库': '向量数据库', 'CAM++': 'CAM++' },
    messages: { recordingSaved: '录音已安全保存，正在整理逐字稿', located: '已定位到对应音频片段', playing: '正在播放混音轨道', paused: '播放已暂停' }
  },
  en: {
    views: { home: 'All meetings', prepare: 'Prepare meeting', live: 'Recording', detail: 'Meeting details', settings: 'Settings' },
    labels: { '所有会议': 'All meetings', '最近删除': 'Recently deleted', '设置': 'Settings', '开始会议': 'Start meeting', '会议库': 'Meeting library', '准备录制': 'Prepare recording', '实时字幕': 'Live transcript', '会议详情': 'Meeting details', '本地优先': 'Local first', '音频与文本仅保存在此设备': 'Audio and text stay on this device', '每一场对话，都留有依据。': 'Every conversation leaves a traceable record.', '录音、逐字稿和纪要只在你明确操作时导出或发送。': 'Audio, transcripts, and notes are exported or shared only when you choose to.', '搜索会议、逐字稿或标签': 'Search meetings, transcripts, or tags', '所有分类': 'All categories', '最近 30 天': 'Last 30 days', '返回会议库': 'Back to library', '开始一场会议': 'Start a meeting', '先确认语言与音频输入。模型会在开始前加载，录制过程不会因网络状态中断。': 'Confirm language and audio input first. The model loads before recording and keeps working without a network connection.', '录制音频': 'Audio capture', '会议名称': 'Meeting name', '会议语言': 'Meeting language', '译文目标': 'Translation target', '我的麦克风': 'My microphone', '系统音频': 'System audio', '输入良好': 'Input ready', '已就绪': 'Ready', '当前模型': 'Current model', '中文确认文本与说话人分离': 'Chinese final transcription and speaker separation', '管理模型与术语': 'Manage models and terms', '正在录制': 'Recording', '暂停': 'Pause', '继续': 'Resume', '结束会议': 'End meeting', '保持在当下': 'Stay with the conversation', '译文: 开': 'Translation: On', '译文: 关': 'Translation: Off', '回到最新': 'Back to latest', '参与者': 'Participants', '本场状态': 'Session status', '我': 'Me', '麦克风': 'Microphone', '系统音频': 'System audio', '打开会议面板': 'Open meeting panel', '导出': 'Export', '逐字稿': 'Transcript', '摘要': 'Summary', '纪要与待办': 'Notes and actions', '播放此段': 'Play this segment', '生成完整会议纪要': 'Generate meeting notes', '模型与本地数据': 'Models and local data', '已安装模型': 'Installed models', '下载更多模型': 'Download more models', '术语库': 'Term library', '12 个词条可用于会议准备、搜索和纪要。仅支持的模型会将其用于转写。': '12 terms are available for meeting preparation, search, and notes. Only supported models use them during transcription.', '管理术语库': 'Manage terms', '存储与隐私': 'Storage and privacy', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': 'Meeting data stays on this Mac. External LLMs require explicit confirmation before receiving a transcript.', '查看本地存储': 'View local storage', '中文': 'Chinese', '英语': 'English', '不需要翻译': 'No translation', '自动检测': 'Auto detect', '切换语言': 'Switch language', '切换主题': 'Switch theme', 'Brevia': 'Brevia', '向量数据库': 'Vector database', 'CAM++': 'CAM++' },
    messages: { recordingSaved: 'Recording saved safely. Preparing transcript.', located: 'Moved to the linked audio segment', playing: 'Playing mixed track', paused: 'Playback paused' }
  },
  es: {
    views: { home: 'Todas las reuniones', prepare: 'Preparar reunión', live: 'Grabando', detail: 'Detalles de la reunión', settings: 'Configuración' },
    labels: { '所有会议': 'Todas las reuniones', '最近删除': 'Eliminadas recientemente', '设置': 'Configuración', '开始会议': 'Iniciar reunión', '会议库': 'Biblioteca de reuniones', '准备录制': 'Preparar grabación', '实时字幕': 'Transcripción en vivo', '会议详情': 'Detalles de la reunión', '本地优先': 'Primero local', '音频与文本仅保存在此设备': 'El audio y el texto permanecen en este dispositivo', '每一场对话，都留有依据。': 'Cada conversación conserva un registro verificable.', '录音、逐字稿和纪要只在你明确操作时导出或发送。': 'El audio, las transcripciones y las notas se exportan o comparten solo cuando lo eliges.', '搜索会议、逐字稿或标签': 'Buscar reuniones, transcripciones o etiquetas', '所有分类': 'Todas las categorías', '最近 30 天': 'Últimos 30 días', '返回会议库': 'Volver a la biblioteca', '开始一场会议': 'Iniciar una reunión', '先确认语言与音频输入。模型会在开始前加载，录制过程不会因网络状态中断。': 'Primero confirma el idioma y la entrada de audio. El modelo carga antes de grabar y sigue funcionando sin conexión.', '录制音频': 'Captura de audio', '会议名称': 'Nombre de la reunión', '会议语言': 'Idioma de la reunión', '译文目标': 'Idioma de traducción', '我的麦克风': 'Mi micrófono', '系统音频': 'Audio del sistema', '输入良好': 'Entrada lista', '已就绪': 'Listo', '当前模型': 'Modelo actual', '中文确认文本与说话人分离': 'Transcripción final en chino y separación de hablantes', '管理模型与术语': 'Gestionar modelos y términos', '正在录制': 'Grabando', '暂停': 'Pausar', '继续': 'Reanudar', '结束会议': 'Finalizar reunión', '保持在当下': 'Sigue la conversación', '译文: 开': 'Traducción: Sí', '译文: 关': 'Traducción: No', '回到最新': 'Volver a lo último', '参与者': 'Participantes', '本场状态': 'Estado de la sesión', '我': 'Yo', '麦克风': 'Micrófono', '系统音频': 'Audio del sistema', '打开会议面板': 'Abrir panel de reunión', '导出': 'Exportar', '逐字稿': 'Transcripción', '摘要': 'Resumen', '纪要与待办': 'Notas y tareas', '播放此段': 'Reproducir este segmento', '生成完整会议纪要': 'Generar notas de reunión', '模型与本地数据': 'Modelos y datos locales', '已安装模型': 'Modelos instalados', '下载更多模型': 'Descargar más modelos', '术语库': 'Biblioteca de términos', '12 个词条可用于会议准备、搜索和纪要。仅支持的模型会将其用于转写。': 'Hay 12 términos para preparar reuniones, buscar y crear notas. Solo los modelos compatibles los usan durante la transcripción.', '管理术语库': 'Gestionar términos', '存储与隐私': 'Almacenamiento y privacidad', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': 'Los datos de la reunión permanecen en este Mac. Los LLM externos requieren confirmación antes de recibir una transcripción.', '查看本地存储': 'Ver almacenamiento local', '中文': 'Chino', '英语': 'Inglés', '不需要翻译': 'Sin traducción', '自动检测': 'Detección automática', '切换语言': 'Cambiar idioma', '切换主题': 'Cambiar tema', 'Brevia': 'Brevia', '向量数据库': 'Base de datos vectorial', 'CAM++': 'CAM++' },
    messages: { recordingSaved: 'Grabación guardada. Preparando la transcripción.', located: 'Se abrió el segmento de audio vinculado', playing: 'Reproduciendo pista mezclada', paused: 'Reproducción pausada' }
  }
};
Object.assign(catalog.zh.labels, { '播放此段': '播放' });
Object.assign(catalog.en.labels, { '播放此段': 'Play' });
Object.assign(catalog.es.labels, { '播放此段': 'Reproducir' });
Object.assign(catalog.zh.labels, {
  '开始录制': '开始录制', '继续会议': '继续会议', '我 · 麦克风': '我 · 麦克风', '计算设备': '计算设备', '预计空间': '预计空间', '识别模型': '识别模型', '已应用术语': '已应用术语', '12 个词条': '12 个词条', '可用': '可用', '已完成精修': '已完成精修', '中文确认文本 · 1.2 GB': '中文确认文本 · 1.2 GB', '英文与其他语言 · 466 MB': '英文与其他语言 · 466 MB', '+ 9': '+ 9', '模型库': '模型库', '管理模型库': '管理模型库', '纪要模型': '纪要模型', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。', '管理纪要模型': '管理纪要模型', '总结提示词': '总结提示词', '编辑提示词': '编辑提示词', '配置 JSON': '配置 JSON', '当前启用的纪要模型配置。': '当前启用的纪要模型配置。'
});
Object.assign(catalog.en.labels, {
  '开始录制': 'Start recording', '继续会议': 'Resume meeting', '我 · 麦克风': 'Me · Microphone', '计算设备': 'Compute device', '预计空间': 'Estimated storage', '识别模型': 'Recognition model', '已应用术语': 'Applied terms', '12 个词条': '12 terms', '可用': 'Available', '已完成精修': 'Refinement complete', '中文确认文本 · 1.2 GB': 'Chinese final transcription · 1.2 GB', '英文与其他语言 · 466 MB': 'English and other languages · 466 MB', '+ 9': '+ 9', '模型库': 'Model library', '管理模型库': 'Manage model library', '纪要模型': 'Summary models', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': 'Configure APIs for meeting notes. All configuration stays local and is never uploaded.', '管理纪要模型': 'Manage summary models', '总结提示词': 'Summary prompt', '编辑提示词': 'Edit prompt', '配置 JSON': 'Configuration JSON', '当前启用的纪要模型配置。': 'The active summary model configuration.'
});
Object.assign(catalog.es.labels, {
  '开始录制': 'Iniciar grabación', '继续会议': 'Reanudar reunión', '我 · 麦克风': 'Yo · Micrófono', '计算设备': 'Dispositivo de cálculo', '预计空间': 'Almacenamiento estimado', '识别模型': 'Modelo de reconocimiento', '已应用术语': 'Términos aplicados', '12 个词条': '12 términos', '可用': 'Disponible', '已完成精修': 'Refinamiento completo', '中文确认文本 · 1.2 GB': 'Transcripción final en chino · 1.2 GB', '英文与其他语言 · 466 MB': 'Inglés y otros idiomas · 466 MB', '+ 9': '+ 9', '模型库': 'Biblioteca de modelos', '管理模型库': 'Gestionar biblioteca de modelos', '纪要模型': 'Modelos de resumen', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': 'Configura API para las notas de reunión. Toda la configuración es local y no se carga.', '管理纪要模型': 'Gestionar modelos de resumen', '总结提示词': 'Prompt de resumen', '编辑提示词': 'Editar prompt', '配置 JSON': 'JSON de configuración', '当前启用的纪要模型配置。': 'La configuración activa del modelo de resumen.'
});
Object.assign(catalog.zh.labels, {
  '分钟': '分钟', '本地录音': '本地录音', '本地保存': '本地保存', '本地会议': '本地会议',
  '← 返回会议库': '← 返回会议库', '说话人分离': '说话人分离', '自定义术语': '自定义术语', '暂无术语': '暂无术语',
  '说话人': '说话人', '等待识别说话人': '等待识别说话人',
  '原始录音与每版逐字稿均保存在本机': '原始录音与每版逐字稿均保存在本机',
  '会议摘要': '会议摘要', '尚未生成会议摘要': '尚未生成会议摘要', '转发': '转发',
  '会后精修': '会后精修', '精修': '精修', '正在精修…': '正在精修…',
  '会后精修已完成': '会后精修已完成', '已整理': '已整理', '决定': '决定', '待办': '待办'
});
Object.assign(catalog.en.labels, {
  '分钟': 'min', '本地录音': 'Local recording', '本地保存': 'Saved locally', '本地会议': 'Local meeting',
  '← 返回会议库': '← Back to library', '说话人分离': 'Speaker diarization', '自定义术语': 'Custom term', '暂无术语': 'No terms',
  '说话人': 'Speaker', '等待识别说话人': 'Waiting to identify speakers',
  '原始录音与每版逐字稿均保存在本机': 'The original recording and every transcript version stay on this device',
  '会议摘要': 'Meeting summary', '尚未生成会议摘要': 'No meeting summary yet', '转发': 'Share',
  '会后精修': 'Refine', '精修': 'Refine', '正在精修…': 'Refining…',
  '会后精修已完成': 'Refinement complete', '已整理': 'Complete', '决定': 'Decisions', '待办': 'Action items'
});
Object.assign(catalog.es.labels, {
  '分钟': 'min', '本地录音': 'Grabación local', '本地保存': 'Guardado localmente', '本地会议': 'Reunión local',
  '← 返回会议库': '← Volver a la biblioteca', '说话人分离': 'Separación de hablantes', '自定义术语': 'Término personalizado', '暂无术语': 'No hay términos',
  '说话人': 'Hablante', '等待识别说话人': 'Esperando identificar hablantes',
  '原始录音与每版逐字稿均保存在本机': 'La grabación original y cada versión de la transcripción se guardan en este dispositivo',
  '会议摘要': 'Resumen de la reunión', '尚未生成会议摘要': 'Aún no se ha generado el resumen', '转发': 'Compartir',
  '会后精修': 'Refinar', '精修': 'Refinar', '正在精修…': 'Refinando…',
  '会后精修已完成': 'Refinamiento completado', '已整理': 'Completado', '决定': 'Decisiones', '待办': 'Tareas'
});
const localeCopies = {
  ja: { views: ['すべての会議', '録音の準備', '録音中', '会議の詳細', '設定'], labels: { '所有会议': 'すべての会議', '最近删除': '最近削除した項目', '设置': '設定', '开始会议': '会議を開始', '会议库': '会議ライブラリ', '准备录制': '録音の準備', '实时字幕': 'ライブ字幕', '会议详情': '会議の詳細', '本地优先': 'ローカル優先', '音频与文本仅保存在此设备': '音声とテキストはこのデバイスにのみ保存されます', '搜索会议、逐字稿或标签': '会議、文字起こし、タグを検索', '所有分类': 'すべての分類', '最近 30 天': '過去30日間', '返回会议库': 'ライブラリに戻る', '开始一场会议': '会議を開始', '会议名称': '会議名', '会议语言': '会議の言語', '译文目标': '翻訳先', '录制音频': '音声を録音', '我的麦克风': 'マイク', '系统音频': 'システム音声', '输入良好': '入力は良好です', '已就绪': '準備完了', '当前模型': '現在のモデル', '正在录制': '録音中', '暂停': '一時停止', '继续': '再開', '结束会议': '会議を終了', '参与者': '参加者', '本场状态': 'セッションの状態', '逐字稿': '文字起こし', '摘要': '要約', '导出': 'エクスポート', '模型与本地数据': 'モデルとローカルデータ', '已安装模型': 'インストール済みモデル', '下载更多模型': 'さらにモデルをダウンロード', '术语库': '用語集', '管理术语库': '用語集を管理', '存储与隐私': 'ストレージとプライバシー', '查看本地存储': 'ローカルストレージを表示', '切换语言': '言語を切り替え', '切换主题': 'テーマを切り替え', '播放此段': '再生', '不需要翻译': '翻訳しない', '自动检测': '自動検出' }, messages: { recordingSaved: '録音を保存しました。文字起こしを準備しています。', located: '該当する音声位置に移動しました', playing: 'ミックス音声を再生中', paused: '再生を一時停止しました' } },
  ko: { views: ['모든 회의', '녹음 준비', '녹음 중', '회의 세부 정보', '설정'], labels: { '所有会议': '모든 회의', '最近删除': '최근 삭제됨', '设置': '설정', '开始会议': '회의 시작', '会议库': '회의 라이브러리', '准备录制': '녹음 준비', '实时字幕': '실시간 자막', '会议详情': '회의 세부 정보', '本地优先': '로컬 우선', '音频与文本仅保存在此设备': '오디오와 텍스트는 이 기기에만 저장됩니다', '搜索会议、逐字稿或标签': '회의, 녹취 또는 태그 검색', '所有分类': '모든 분류', '最近 30 天': '최근 30일', '返回会议库': '라이브러리로 돌아가기', '开始一场会议': '회의 시작', '会议名称': '회의 이름', '会议语言': '회의 언어', '译文目标': '번역 대상', '录制音频': '오디오 녹음', '我的麦克风': '내 마이크', '系统音频': '시스템 오디오', '输入良好': '입력 양호', '已就绪': '준비됨', '当前模型': '현재 모델', '正在录制': '녹음 중', '暂停': '일시 정지', '继续': '계속', '结束会议': '회의 종료', '参与者': '참가자', '本场状态': '세션 상태', '逐字稿': '녹취', '摘要': '요약', '导出': '내보내기', '模型与本地数据': '모델 및 로컬 데이터', '已安装模型': '설치된 모델', '下载更多模型': '모델 더 다운로드', '术语库': '용어집', '管理术语库': '용어집 관리', '存储与隐私': '저장 공간 및 개인정보', '查看本地存储': '로컬 저장 공간 보기', '切换语言': '언어 전환', '切换主题': '테마 전환', '播放此段': '재생', '不需要翻译': '번역 안 함', '自动检测': '자동 감지' }, messages: { recordingSaved: '녹음이 저장되었습니다. 녹취를 준비합니다.', located: '연결된 오디오 구간으로 이동했습니다', playing: '믹스 트랙 재생 중', paused: '재생이 일시 정지되었습니다' } },
  fr: { views: ['Toutes les réunions', 'Préparer la réunion', 'Enregistrement', 'Détails de la réunion', 'Paramètres'], labels: { '所有会议': 'Toutes les réunions', '最近删除': 'Supprimées récemment', '设置': 'Paramètres', '开始会议': 'Démarrer la réunion', '会议库': 'Bibliothèque de réunions', '准备录制': 'Préparer l’enregistrement', '实时字幕': 'Transcription en direct', '会议详情': 'Détails de la réunion', '本地优先': 'Priorité au local', '音频与文本仅保存在此设备': 'L’audio et le texte restent sur cet appareil', '搜索会议、逐字稿或标签': 'Rechercher des réunions, transcriptions ou étiquettes', '所有分类': 'Toutes les catégories', '最近 30 天': '30 derniers jours', '返回会议库': 'Retour à la bibliothèque', '开始一场会议': 'Démarrer une réunion', '会议名称': 'Nom de la réunion', '会议语言': 'Langue de la réunion', '译文目标': 'Langue cible', '录制音频': 'Capture audio', '我的麦克风': 'Mon microphone', '系统音频': 'Audio système', '输入良好': 'Entrée prête', '已就绪': 'Prêt', '当前模型': 'Modèle actuel', '正在录制': 'Enregistrement', '暂停': 'Pause', '继续': 'Reprendre', '结束会议': 'Terminer la réunion', '参与者': 'Participants', '本场状态': 'État de la session', '逐字稿': 'Transcription', '摘要': 'Résumé', '导出': 'Exporter', '模型与本地数据': 'Modèles et données locales', '已安装模型': 'Modèles installés', '下载更多模型': 'Télécharger des modèles', '术语库': 'Glossaire', '管理术语库': 'Gérer le glossaire', '存储与隐私': 'Stockage et confidentialité', '查看本地存储': 'Voir le stockage local', '切换语言': 'Changer de langue', '切换主题': 'Changer de thème', '播放此段': 'Lire', '不需要翻译': 'Aucune traduction', '自动检测': 'Détection automatique' }, messages: { recordingSaved: 'Enregistrement sauvegardé. Préparation de la transcription.', located: 'Positionné sur le segment audio lié', playing: 'Lecture de la piste mixée', paused: 'Lecture en pause' } },
  de: { views: ['Alle Besprechungen', 'Aufnahme vorbereiten', 'Aufnahme läuft', 'Besprechungsdetails', 'Einstellungen'], labels: { '所有会议': 'Alle Besprechungen', '最近删除': 'Kürzlich gelöscht', '设置': 'Einstellungen', '开始会议': 'Besprechung starten', '会议库': 'Besprechungsbibliothek', '准备录制': 'Aufnahme vorbereiten', '实时字幕': 'Live-Transkript', '会议详情': 'Besprechungsdetails', '本地优先': 'Lokal zuerst', '音频与文本仅保存在此设备': 'Audio und Text bleiben auf diesem Gerät', '搜索会议、逐字稿或标签': 'Besprechungen, Transkripte oder Tags suchen', '所有分类': 'Alle Kategorien', '最近 30 天': 'Letzte 30 Tage', '返回会议库': 'Zurück zur Bibliothek', '开始一场会议': 'Besprechung starten', '会议名称': 'Besprechungsname', '会议语言': 'Besprechungssprache', '译文目标': 'Zielsprache', '录制音频': 'Audio aufnehmen', '我的麦克风': 'Mein Mikrofon', '系统音频': 'Systemaudio', '输入良好': 'Eingang bereit', '已就绪': 'Bereit', '当前模型': 'Aktuelles Modell', '正在录制': 'Aufnahme läuft', '暂停': 'Pausieren', '继续': 'Fortsetzen', '结束会议': 'Besprechung beenden', '参与者': 'Teilnehmende', '本场状态': 'Sitzungsstatus', '逐字稿': 'Transkript', '摘要': 'Zusammenfassung', '导出': 'Exportieren', '模型与本地数据': 'Modelle und lokale Daten', '已安装模型': 'Installierte Modelle', '下载更多模型': 'Weitere Modelle herunterladen', '术语库': 'Terminologie', '管理术语库': 'Terminologie verwalten', '存储与隐私': 'Speicher und Datenschutz', '查看本地存储': 'Lokalen Speicher anzeigen', '切换语言': 'Sprache wechseln', '切换主题': 'Design wechseln', '播放此段': 'Wiedergabe', '不需要翻译': 'Keine Übersetzung', '自动检测': 'Automatisch erkennen' }, messages: { recordingSaved: 'Aufnahme gespeichert. Transkript wird vorbereitet.', located: 'Zum verknüpften Audiosegment gesprungen', playing: 'Gemischte Spur wird wiedergegeben', paused: 'Wiedergabe pausiert' } },
  ru: { views: ['Все встречи', 'Подготовка записи', 'Идёт запись', 'Сведения о встрече', 'Настройки'], labels: { '所有会议': 'Все встречи', '最近删除': 'Недавно удалённые', '设置': 'Настройки', '开始会议': 'Начать встречу', '会议库': 'Библиотека встреч', '准备录制': 'Подготовка записи', '实时字幕': 'Субтитры в реальном времени', '会议详情': 'Сведения о встрече', '本地优先': 'Локальное хранение', '音频与文本仅保存在此设备': 'Аудио и текст хранятся только на этом устройстве', '搜索会议、逐字稿或标签': 'Поиск встреч, расшифровок или тегов', '所有分类': 'Все категории', '最近 30 天': 'Последние 30 дней', '返回会议库': 'Вернуться в библиотеку', '开始一场会议': 'Начать встречу', '会议名称': 'Название встречи', '会议语言': 'Язык встречи', '译文目标': 'Язык перевода', '录制音频': 'Запись аудио', '我的麦克风': 'Мой микрофон', '系统音频': 'Системный звук', '输入良好': 'Вход готов', '已就绪': 'Готово', '当前模型': 'Текущая модель', '正在录制': 'Идёт запись', '暂停': 'Пауза', '继续': 'Продолжить', '结束会议': 'Завершить встречу', '参与者': 'Участники', '本场状态': 'Статус сеанса', '逐字稿': 'Расшифровка', '摘要': 'Сводка', '导出': 'Экспорт', '模型与本地数据': 'Модели и локальные данные', '已安装模型': 'Установленные модели', '下载更多模型': 'Скачать модели', '术语库': 'Глоссарий', '管理术语库': 'Управление глоссарием', '存储与隐私': 'Хранилище и конфиденциальность', '查看本地存储': 'Открыть локальное хранилище', '切换语言': 'Сменить язык', '切换主题': 'Сменить тему', '播放此段': 'Воспроизвести', '不需要翻译': 'Без перевода', '自动检测': 'Автоопределение' }, messages: { recordingSaved: 'Запись сохранена. Подготавливается расшифровка.', located: 'Переход к связанному фрагменту аудио', playing: 'Воспроизводится смешанная дорожка', paused: 'Воспроизведение приостановлено' } },
};
Object.entries(localeCopies).forEach(([code, copy]) => {
  const [home, prepare, live, detail, settings] = copy.views;
  catalog[code] = { views: { home, prepare, live, detail, settings }, labels: { ...catalog.en.labels, ...copy.labels }, messages: copy.messages };
});
const interfaceLabels = {
  zh: { '分类标签': '分类标签', '未分类': '未分类', '最近 7 天': '最近 7 天', '最近 90 天': '最近 90 天', '全部时间': '全部时间', '系统默认麦克风': '系统默认麦克风', '需要授予屏幕与系统音频权限': '需要授予屏幕与系统音频权限', '流式模型': '流式模型', '中文 / 英语': '中文 / 英语', '管理模型与术语': '管理模型与术语', '更多操作': '更多操作', '恢复': '恢复', '重命名': '重命名', '分类': '分类', '删除': '删除', '取消': '取消', '保存': '保存', '添加': '添加', '新分类名称': '新分类名称', '开始录制': '开始录制', '本地录音': '本地录音', '中文实时字幕 · sherpa-onnx': '中文实时字幕 · sherpa-onnx', '英文实时字幕 · sherpa-onnx': '英文实时字幕 · sherpa-onnx', '会后精修 · sherpa-onnx · CUDA': '会后精修 · sherpa-onnx · CUDA', '端点检测与说话人分配 · sherpa-onnx': '端点检测与说话人分配 · sherpa-onnx', '实时字幕 · 中文 / 英语 / 粤语': '实时字幕 · 中文 / 英语 / 粤语', '原生流式识别，持续更新当前字幕。': '原生流式识别，持续更新当前字幕。', '会后精修 · 多语种': '会后精修 · 多语种', '基于完整录音生成高精度修订版本。': '基于完整录音生成高精度修订版本。' },
  en: { '分类标签': 'Category', '未分类': 'Uncategorized', '最近 7 天': 'Last 7 days', '最近 90 天': 'Last 90 days', '全部时间': 'All time', '系统默认麦克风': 'System default microphone', '需要授予屏幕与系统音频权限': 'Screen and system-audio permission required', '流式模型': 'Streaming model', '中文 / 英语': 'Chinese / English', '管理模型与术语': 'Manage models and terms', '更多操作': 'More actions', '恢复': 'Restore', '重命名': 'Rename', '分类': 'Category', '删除': 'Delete', '取消': 'Cancel', '保存': 'Save', '添加': 'Add', '新分类名称': 'New category name', '开始录制': 'Start recording', '本地录音': 'Local recording', '中文实时字幕 · sherpa-onnx': 'Chinese live captions · sherpa-onnx', '英文实时字幕 · sherpa-onnx': 'English live captions · sherpa-onnx', '会后精修 · sherpa-onnx · CUDA': 'Post-meeting refinement · sherpa-onnx · CUDA', '端点检测与说话人分配 · sherpa-onnx': 'Endpoint detection and speaker assignment · sherpa-onnx', '实时字幕 · 中文 / 英语 / 粤语': 'Live captions · Chinese / English / Cantonese', '原生流式识别，持续更新当前字幕。': 'Native streaming recognition that continuously updates the active caption.', '会后精修 · 多语种': 'Post-meeting refinement · Multilingual', '基于完整录音生成高精度修订版本。': 'Creates a high-accuracy revision from the complete recording.' },
  es: { '分类标签': 'Categoría', '未分类': 'Sin categoría', '最近 7 天': 'Últimos 7 días', '最近 90 天': 'Últimos 90 días', '全部时间': 'Todo el tiempo', '系统默认麦克风': 'Micrófono predeterminado del sistema', '需要授予屏幕与系统音频权限': 'Se requiere permiso para pantalla y audio del sistema', '流式模型': 'Modelo en streaming', '中文 / 英语': 'Chino / inglés', '管理模型与术语': 'Gestionar modelos y términos', '更多操作': 'Más acciones', '恢复': 'Restaurar', '重命名': 'Renombrar', '分类': 'Categoría', '删除': 'Eliminar', '取消': 'Cancelar', '保存': 'Guardar', '添加': 'Añadir', '新分类名称': 'Nombre de categoría', '开始录制': 'Iniciar grabación', '本地录音': 'Grabación local' },
  ja: { '分类标签': 'カテゴリ', '未分类': '未分類', '最近 7 天': '過去7日間', '最近 90 天': '過去90日間', '全部时间': 'すべての期間', '系统默认麦克风': 'システムのデフォルトマイク', '需要授予屏幕与系统音频权限': '画面とシステム音声のアクセス許可が必要です', '流式模型': 'ストリーミングモデル', '中文 / 英语': '中国語 / 英語', '管理模型与术语': 'モデルと用語を管理', '更多操作': 'その他の操作', '恢复': '復元', '重命名': '名前を変更', '分类': 'カテゴリ', '删除': '削除', '取消': 'キャンセル', '保存': '保存', '添加': '追加', '新分类名称': '新しいカテゴリ名', '开始录制': '録音を開始', '本地录音': 'ローカル録音' },
  ko: { '分类标签': '분류', '未分类': '미분류', '最近 7 天': '최근 7일', '最近 90 天': '최근 90일', '全部时间': '전체 기간', '系统默认麦克风': '시스템 기본 마이크', '需要授予屏幕与系统音频权限': '화면 및 시스템 오디오 권한이 필요합니다', '流式模型': '스트리밍 모델', '中文 / 英语': '중국어 / 영어', '管理模型与术语': '모델 및 용어 관리', '更多操作': '추가 작업', '恢复': '복원', '重命名': '이름 바꾸기', '分类': '분류', '删除': '삭제', '取消': '취소', '保存': '저장', '添加': '추가', '新分类名称': '새 분류 이름', '开始录制': '녹음 시작', '本地录音': '로컬 녹음' },
  fr: { '分类标签': 'Catégorie', '未分类': 'Sans catégorie', '最近 7 天': '7 derniers jours', '最近 90 天': '90 derniers jours', '全部时间': 'Toute la période', '系统默认麦克风': 'Microphone système par défaut', '需要授予屏幕与系统音频权限': 'Autorisation d’écran et d’audio système requise', '流式模型': 'Modèle en continu', '中文 / 英语': 'Chinois / anglais', '管理模型与术语': 'Gérer les modèles et les termes', '更多操作': 'Plus d’actions', '恢复': 'Restaurer', '重命名': 'Renommer', '分类': 'Catégorie', '删除': 'Supprimer', '取消': 'Annuler', '保存': 'Enregistrer', '添加': 'Ajouter', '新分类名称': 'Nouveau nom de catégorie', '开始录制': 'Démarrer l’enregistrement', '本地录音': 'Enregistrement local' },
  de: { '分类标签': 'Kategorie', '未分类': 'Nicht kategorisiert', '最近 7 天': 'Letzte 7 Tage', '最近 90 天': 'Letzte 90 Tage', '全部时间': 'Gesamter Zeitraum', '系统默认麦克风': 'Standardmikrofon des Systems', '需要授予屏幕与系统音频权限': 'Berechtigung für Bildschirm und Systemaudio erforderlich', '流式模型': 'Streaming-Modell', '中文 / 英语': 'Chinesisch / Englisch', '管理模型与术语': 'Modelle und Begriffe verwalten', '更多操作': 'Weitere Aktionen', '恢复': 'Wiederherstellen', '重命名': 'Umbenennen', '分类': 'Kategorie', '删除': 'Löschen', '取消': 'Abbrechen', '保存': 'Speichern', '添加': 'Hinzufügen', '新分类名称': 'Neuer Kategoriename', '开始录制': 'Aufnahme starten', '本地录音': 'Lokale Aufnahme' },
  ru: { '分类标签': 'Категория', '未分类': 'Без категории', '最近 7 天': 'Последние 7 дней', '最近 90 天': 'Последние 90 дней', '全部时间': 'За всё время', '系统默认麦克风': 'Системный микрофон по умолчанию', '需要授予屏幕与系统音频权限': 'Требуется доступ к экрану и системному звуку', '流式模型': 'Потоковая модель', '中文 / 英语': 'Китайский / английский', '管理模型与术语': 'Управление моделями и терминами', '更多操作': 'Другие действия', '恢复': 'Восстановить', '重命名': 'Переименовать', '分类': 'Категория', '删除': 'Удалить', '取消': 'Отмена', '保存': 'Сохранить', '添加': 'Добавить', '新分类名称': 'Название категории', '开始录制': 'Начать запись', '本地录音': 'Локальная запись' },
};
Object.entries(interfaceLabels).forEach(([code, labels]) => Object.assign(catalog[code].labels, labels));
Object.assign(catalog.en.labels, { '正在精修': 'Refining', '原版逐字稿仍可查看': 'The original transcript remains available', '准备中': 'Preparing' });
Object.assign(catalog.es.labels, { '正在精修': 'Refinando', '原版逐字稿仍可查看': 'La transcripción original sigue disponible', '准备中': 'Preparando' });
Object.assign(catalog.ja.labels, { '计算设备': '演算デバイス', '会后精修': '会議後の高精度化', '正在精修': '高精度化中', '原版逐字稿仍可查看': '元の文字起こしは引き続き閲覧できます', '准备中': '準備中', '可用': '利用可能', '本地保存': 'ローカルに保存', '本地会议': 'ローカル会議', '← 返回会议库': '← ライブラリに戻る', '原始录音与每版逐字稿均保存在本机': '元の録音とすべての文字起こし版はこのデバイスに保存されます' });
Object.assign(catalog.ko.labels, { '计算设备': '연산 장치', '会后精修': '회의 후 정제', '正在精修': '정제 중', '原版逐字稿仍可查看': '원본 녹취는 계속 볼 수 있습니다', '准备中': '준비 중', '可用': '사용 가능', '本地保存': '로컬에 저장됨', '本地会议': '로컬 회의', '← 返回会议库': '← 라이브러리로 돌아가기', '原始录音与每版逐字稿均保存在本机': '원본 녹음과 모든 녹취 버전은 이 기기에 저장됩니다' });
Object.assign(catalog.fr.labels, { '计算设备': 'Appareil de calcul', '会后精修': 'Affinage après réunion', '正在精修': 'Affinage en cours', '原版逐字稿仍可查看': 'La transcription d’origine reste disponible', '准备中': 'Préparation', '可用': 'Disponible', '本地保存': 'Enregistré localement', '本地会议': 'Réunion locale', '← 返回会议库': '← Retour à la bibliothèque', '原始录音与每版逐字稿均保存在本机': 'L’enregistrement original et toutes les versions de la transcription restent sur cet appareil' });
Object.assign(catalog.de.labels, { '计算设备': 'Rechengerät', '会后精修': 'Nachbearbeitung', '正在精修': 'Nachbearbeitung läuft', '原版逐字稿仍可查看': 'Das ursprüngliche Transkript bleibt verfügbar', '准备中': 'Vorbereitung', '可用': 'Verfügbar', '本地保存': 'Lokal gespeichert', '本地会议': 'Lokale Besprechung', '← 返回会议库': '← Zurück zur Bibliothek', '原始录音与每版逐字稿均保存在本机': 'Die Originalaufnahme und jede Transkriptversion bleiben auf diesem Gerät' });
Object.assign(catalog.ru.labels, { '计算设备': 'Вычислительное устройство', '会后精修': 'Обработка после встречи', '正在精修': 'Идёт обработка', '原版逐字稿仍可查看': 'Исходная расшифровка остаётся доступна', '准备中': 'Подготовка', '可用': 'Доступно', '本地保存': 'Сохранено локально', '本地会议': 'Локальная встреча', '← 返回会议库': '← Вернуться в библиотеку', '原始录音与每版逐字稿均保存在本机': 'Исходная запись и все версии расшифровки хранятся на этом устройстве' });
const settingsLabels = {
  ja: { '会议摘要': '会議の要約', '尚未生成会议摘要': '会議の要約はまだありません', '生成完整会议纪要': '会議メモを生成', '转发': '共有', '已整理': '完了', '已完成': '完了', '处理中': '処理中', '纪要模型': '要約モデル', '管理纪要模型': '要約モデルを管理', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': '会議メモを生成する API を設定します。すべての設定はローカルに保存されます。', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': '会議データはこの Mac に保存されます。外部 LLM への送信には明示的な確認が必要です。', '返回会议库': 'ライブラリに戻る', '暂无术语': '用語はありません', '软件更新': 'ソフトウェアアップデート', '当前版本 0.1.0': '現在のバージョン 0.1.0', '检查更新': 'アップデートを確認' },
  ko: { '会议摘要': '회의 요약', '尚未生成会议摘要': '아직 회의 요약이 없습니다', '生成完整会议纪要': '회의록 생성', '转发': '공유', '已整理': '완료', '已完成': '완료', '处理中': '처리 중', '纪要模型': '요약 모델', '管理纪要模型': '요약 모델 관리', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': '회의록 생성 API를 설정합니다. 모든 설정은 로컬에만 저장됩니다.', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': '회의 데이터는 이 Mac에 저장됩니다. 외부 LLM 전송 전 명시적 확인이 필요합니다.', '返回会议库': '라이브러리로 돌아가기', '暂无术语': '용어 없음', '软件更新': '소프트웨어 업데이트', '当前版本 0.1.0': '현재 버전 0.1.0', '检查更新': '업데이트 확인' },
  fr: { '会议摘要': 'Résumé de la réunion', '尚未生成会议摘要': 'Aucun résumé de réunion', '生成完整会议纪要': 'Générer les notes de réunion', '转发': 'Partager', '已整理': 'Terminé', '已完成': 'Terminé', '处理中': 'En cours', '纪要模型': 'Modèles de résumé', '管理纪要模型': 'Gérer les modèles de résumé', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': 'Configurez les API pour les notes de réunion. Toute la configuration reste locale.', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': 'Les données de réunion restent sur ce Mac. Les LLM externes exigent une confirmation explicite.', '返回会议库': 'Retour à la bibliothèque', '暂无术语': 'Aucun terme', '软件更新': 'Mises à jour logicielles', '当前版本 0.1.0': 'Version actuelle 0.1.0', '检查更新': 'Rechercher des mises à jour' },
  de: { '会议摘要': 'Besprechungszusammenfassung', '尚未生成会议摘要': 'Noch keine Zusammenfassung', '生成完整会议纪要': 'Besprechungsnotizen erstellen', '转发': 'Teilen', '已整理': 'Abgeschlossen', '已完成': 'Abgeschlossen', '处理中': 'Wird verarbeitet', '纪要模型': 'Zusammenfassungsmodelle', '管理纪要模型': 'Zusammenfassungsmodelle verwalten', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': 'APIs für Besprechungsnotizen konfigurieren. Alle Einstellungen bleiben lokal.', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': 'Besprechungsdaten bleiben auf diesem Mac. Externe LLMs erfordern eine ausdrückliche Bestätigung.', '返回会议库': 'Zurück zur Bibliothek', '暂无术语': 'Keine Begriffe', '软件更新': 'Softwareupdates', '当前版本 0.1.0': 'Aktuelle Version 0.1.0', '检查更新': 'Nach Updates suchen' },
  ru: { '会议摘要': 'Сводка встречи', '尚未生成会议摘要': 'Сводки встречи пока нет', '生成完整会议纪要': 'Создать заметки встречи', '转发': 'Поделиться', '已整理': 'Готово', '已完成': 'Готово', '处理中': 'Обработка', '纪要模型': 'Модели сводки', '管理纪要模型': 'Управление моделями сводки', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': 'Настройте API для заметок встречи. Все настройки хранятся локально.', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': 'Данные встречи хранятся на этом Mac. Для внешних LLM требуется явное подтверждение.', '返回会议库': 'Вернуться в библиотеку', '暂无术语': 'Нет терминов', '软件更新': 'Обновления ПО', '当前版本 0.1.0': 'Текущая версия 0.1.0', '检查更新': 'Проверить обновления' }
};
Object.entries(settingsLabels).forEach(([code, labels]) => Object.assign(catalog[code].labels, labels));

window.BreviaLocaleData = { catalog };
})();
