(() => {
const catalog = {
  zh: {
    views: { home: '所有会议', prepare: '准备录制', live: '正在录制', detail: '会议详情', settings: '设置' },
    labels: { '所有会议': '所有会议', '最近删除': '最近删除', '设置': '设置', '开始会议': '开始会议', '会议库': '会议库', '准备录制': '准备录制', '实时字幕': '实时字幕', '会议详情': '会议详情', '本地优先': '本地优先', '音频与文本仅保存在此设备': '音频与文本仅保存在此设备', '每一场对话，都留有依据。': '每一场对话，都留有依据。', '录音、逐字稿和纪要只在你明确操作时导出或发送。': '录音、逐字稿和纪要只在你明确操作时导出或发送。', '搜索会议、逐字稿或标签': '搜索会议、逐字稿或标签', '所有分类': '所有分类', '最近 30 天': '最近 30 天', '返回会议库': '返回会议库', '开始一场会议': '开始一场会议', '先确认语言与音频输入。模型会在开始前加载，录制过程不会因网络状态中断。': '先确认语言与音频输入。模型会在开始前加载，录制过程不会因网络状态中断。', '录制音频': '录制音频', '会议名称': '会议名称', '会议语言': '会议语言', '译文目标': '译文目标', '我的麦克风': '我的麦克风', '系统音频': '系统音频', '输入良好': '输入良好', '已就绪': '已就绪', '当前模型': '当前模型', '中文确认文本与说话人分离': '中文确认文本与说话人分离', '管理模型与术语': '管理模型与术语', '正在录制': '正在录制', '暂停': '暂停', '继续': '继续', '结束会议': '结束会议', '保持在当下': '保持在当下', '译文: 开': '译文: 开', '译文: 关': '译文: 关', '回到最新': '回到最新', '参与者': '参与者', '本场状态': '本场状态', '我': '我', '麦克风': '麦克风', '系统音频': '系统音频', '打开会议面板': '打开会议面板', '导出': '导出', '逐字稿': '逐字稿', '摘要': '摘要', '纪要与待办': '纪要与待办', '播放此段': '播放此段', '生成完整会议纪要': '生成完整会议纪要', '模型与本地数据': '模型与本地数据', '已安装模型': '已安装模型', '下载更多模型': '下载更多模型', '术语库': '术语库', '12 个词条可用于会议准备、搜索和纪要。仅支持的模型会将其用于转写。': '12 个词条可用于会议准备、搜索和纪要。仅支持的模型会将其用于转写。', '管理术语库': '管理术语库', '存储与隐私': '存储与隐私', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。', '查看本地存储': '查看本地存储', '中文': '中文', '英语': '英语', '不需要翻译': '不需要翻译', '自动检测': '自动检测', '切换语言': '切换语言', '切换主题': '切换主题', 'Brevia': 'Brevia', '向量数据库': '向量数据库', 'CAM++': 'CAM++' },
    messages: { recordingSaved: '录音已安全保存，正在整理逐字稿', located: '已定位到对应音频片段', playing: '正在播放混音轨道', paused: '播放已暂停' }
  },
  en: {
    views: { home: 'All meetings', prepare: 'Prepare meeting', live: 'Recording', detail: 'Meeting details', settings: 'Settings' },
    labels: { '所有会议': 'All meetings', '最近删除': 'Recently deleted', '设置': 'Settings', '开始会议': 'Start meeting', '会议库': 'Meeting library', '准备录制': 'Prepare recording', '实时字幕': 'Live transcript', '会议详情': 'Meeting details', '本地优先': 'Local first', '音频与文本仅保存在此设备': 'Audio and text stay on this device', '每一场对话，都留有依据。': 'Every conversation leaves a traceable record.', '录音、逐字稿和纪要只在你明确操作时导出或发送。': 'Audio, transcripts, and notes are exported or shared only when you choose to.', '搜索会议、逐字稿或标签': 'Search meetings, transcripts, or tags', '所有分类': 'All categories', '最近 30 天': 'Last 30 days', '返回会议库': 'Back to library', '开始一场会议': 'Start a meeting', '先确认语言与音频输入。模型会在开始前加载，录制过程不会因网络状态中断。': 'Confirm language and audio input first. The model loads before recording and keeps working without a network connection.', '录制音频': 'Audio capture', '会议名称': 'Meeting name', '会议语言': 'Meeting language', '译文目标': 'Translation target', '我的麦克风': 'My microphone', '系统音频': 'System audio', '输入良好': 'Input ready', '已就绪': 'Ready', '当前模型': 'Current model', '中文确认文本与说话人分离': 'Chinese final transcription and speaker separation', '管理模型与术语': 'Manage models and terms', '正在录制': 'Recording', '暂停': 'Pause', '继续': 'Resume', '结束会议': 'End meeting', '保持在当下': 'Stay with the conversation', '译文: 开': 'Translation: On', '译文: 关': 'Translation: Off', '回到最新': 'Back to latest', '参与者': 'Participants', '本场状态': 'Session status', '我': 'Me', '麦克风': 'Microphone', '系统音频': 'System audio', '打开会议面板': 'Open meeting panel', '导出': 'Export', '逐字稿': 'Transcript', '摘要': 'Summary', '纪要与待办': 'Notes and actions', '播放此段': 'Play this segment', '生成完整会议纪要': 'Generate meeting notes', '模型与本地数据': 'Models and local data', '已安装模型': 'Installed models', '下载更多模型': 'Download more models', '术语库': 'Term library', '12 个词条可用于会议准备、搜索和纪要。仅支持的模型会将其用于转写。': '12 terms are available for meeting preparation, search, and notes. Only supported models use them during transcription.', '管理术语库': 'Manage terms', '存储与隐私': 'Storage and privacy', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': 'Meeting data stays on this Mac. External LLMs require explicit confirmation before receiving a transcript.', '查看本地存储': 'View local storage', '中文': 'Chinese', '英语': 'English', '不需要翻译': 'No translation', '自动检测': 'Auto detect', '切换语言': 'Switch language', '切换主题': 'Switch theme', 'Brevia': 'Brevia', '向量数据库': 'Vector database', 'CAM++': 'CAM++' },
    messages: { recordingSaved: 'Recording saved safely. Preparing transcript.', located: 'Moved to the linked audio segment', playing: 'Playing mixed track', paused: 'Playback paused' }
  },
  es: {
    views: { home: 'Todas las reuniones', prepare: 'Preparar reunión', live: 'Grabando', detail: 'Detalles de la reunión', settings: 'Configuración' },
    labels: { '所有会议': 'Todas las reuniones', '最近删除': 'Eliminadas recientemente', '设置': 'Configuración', '开始会议': 'Iniciar reunión', '会议库': 'Biblioteca de reuniones', '准备录制': 'Preparar grabación', '实时字幕': 'Transcripción en vivo', '会议详情': 'Detalles de la reunión', '本地优先': 'Primero local', '音频与文本仅保存在此设备': 'El audio y el texto permanecen en este dispositivo', '每一场对话，都留有依据。': 'Cada conversación conserva un registro verificable.', '录音、逐字稿和纪要只在你明确操作时导出或发送。': 'El audio, las transcripciones y las notas se exportan o comparten solo cuando lo eliges.', '搜索会议、逐字稿或标签': 'Buscar reuniones, transcripciones o etiquetas', '所有分类': 'Todas las categorías', '最近 30 天': 'Últimos 30 días', '返回会议库': 'Volver a la biblioteca', '开始一场会议': 'Iniciar una reunión', '先确认语言与音频输入。模型会在开始前加载，录制过程不会因网络状态中断。': 'Primero confirma el idioma y la entrada de audio. El modelo carga antes de grabar y sigue funcionando sin conexión.', '录制音频': 'Captura de audio', '会议名称': 'Nombre de la reunión', '会议语言': 'Idioma de la reunión', '译文目标': 'Idioma de traducción', '我的麦克风': 'Mi micrófono', '系统音频': 'Audio del sistema', '输入良好': 'Entrada lista', '已就绪': 'Listo', '当前模型': 'Modelo actual', '中文确认文本与说话人分离': 'Transcripción final en chino y separación de hablantes', '管理模型与术语': 'Gestionar modelos y términos', '正在录制': 'Grabando', '暂停': 'Pausar', '继续': 'Reanudar', '结束会议': 'Finalizar reunión', '保持在当下': 'Sigue la conversación', '译文: 开': 'Traducción: Sí', '译文: 关': 'Traducción: No', '回到最新': 'Volver a lo último', '参与者': 'Participantes', '本场状态': 'Estado de la sesión', '我': 'Yo', '麦克风': 'Micrófono', '系统音频': 'Audio del sistema', '打开会议面板': 'Abrir panel de reunión', '导出': 'Exportar', '逐字稿': 'Transcripción', '摘要': 'Resumen', '纪要与待办': 'Notas y tareas', '播放此段': 'Reproducir este segmento', '生成完整会议纪要': 'Generar notas de reunión', '模型与本地数据': 'Modelos y datos locales', '已安装模型': 'Modelos instalados', '下载更多模型': 'Descargar más modelos', '术语库': 'Biblioteca de términos', '12 个词条可用于会议准备、搜索和纪要。仅支持的模型会将其用于转写。': 'Hay 12 términos para preparar reuniones, buscar y crear notas. Solo los modelos compatibles los usan durante la transcripción.', '管理术语库': 'Gestionar términos', '存储与隐私': 'Almacenamiento y privacidad', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': 'Los datos de la reunión permanecen en este Mac. Los LLM externos requieren confirmación antes de recibir una transcripción.', '查看本地存储': 'Ver almacenamiento local', '中文': 'Chino', '英语': 'Inglés', '不需要翻译': 'Sin traducción', '自动检测': 'Detección automática', '切换语言': 'Cambiar idioma', '切换主题': 'Cambiar tema', 'Brevia': 'Brevia', '向量数据库': 'Base de datos vectorial', 'CAM++': 'CAM++' },
    messages: { recordingSaved: 'Grabación guardada. Preparando la transcripción.', located: 'Se abrió el segmento de audio vinculado', playing: 'Reproduciendo pista mezclada', paused: 'Reproducción pausada' }
  }
};
Object.assign(catalog.zh.labels, { '播放此段': '播放' });
Object.assign(catalog.en.labels, { '播放此段': 'Play' });
Object.assign(catalog.es.labels, { '播放此段': 'Reproducir' });
Object.assign(catalog.zh.labels, {
  '开始录制': '开始录制', '继续会议': '继续会议', '我 · 麦克风': '我 · 麦克风', '计算设备': '计算设备', '预计空间': '预计空间', '识别模型': '识别模型', '已应用术语': '已应用术语', '12 个词条': '12 个词条', '可用': '可用', '已完成精修': '已完成精修', '中文确认文本 · 1.2 GB': '中文确认文本 · 1.2 GB', '英文与其他语言 · 466 MB': '英文与其他语言 · 466 MB', '+ 9': '+ 9', '模型库': '模型库', '管理模型库': '管理模型库', '纪要模型': '纪要模型', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。', '管理纪要模型': '管理纪要模型', '总结提示词': '总结提示词', '编辑提示词': '编辑提示词', '配置 JSON': '配置 JSON', '当前启用的纪要模型配置。': '当前启用的纪要模型配置。'
});
Object.assign(catalog.en.labels, {
  '开始录制': 'Start recording', '继续会议': 'Resume meeting', '我 · 麦克风': 'Me · Microphone', '计算设备': 'Compute device', '预计空间': 'Estimated storage', '识别模型': 'Recognition model', '已应用术语': 'Applied terms', '12 个词条': '12 terms', '可用': 'Available', '已完成精修': 'Refinement complete', '中文确认文本 · 1.2 GB': 'Chinese final transcription · 1.2 GB', '英文与其他语言 · 466 MB': 'English and other languages · 466 MB', '+ 9': '+ 9', '模型库': 'Model library', '管理模型库': 'Manage model library', '纪要模型': 'Summary models', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': 'Configure APIs for meeting notes. All configuration stays local and is never uploaded.', '管理纪要模型': 'Manage summary models', '总结提示词': 'Summary prompt', '编辑提示词': 'Edit prompt', '配置 JSON': 'Configuration JSON', '当前启用的纪要模型配置。': 'The active summary model configuration.'
});
Object.assign(catalog.es.labels, {
  '开始录制': 'Iniciar grabación', '继续会议': 'Reanudar reunión', '我 · 麦克风': 'Yo · Micrófono', '计算设备': 'Dispositivo de cálculo', '预计空间': 'Almacenamiento estimado', '识别模型': 'Modelo de reconocimiento', '已应用术语': 'Términos aplicados', '12 个词条': '12 términos', '可用': 'Disponible', '已完成精修': 'Refinamiento completo', '中文确认文本 · 1.2 GB': 'Transcripción final en chino · 1.2 GB', '英文与其他语言 · 466 MB': 'Inglés y otros idiomas · 466 MB', '+ 9': '+ 9', '模型库': 'Biblioteca de modelos', '管理模型库': 'Gestionar biblioteca de modelos', '纪要模型': 'Modelos de resumen', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': 'Configura API para las notas de reunión. Toda la configuración es local y no se carga.', '管理纪要模型': 'Gestionar modelos de resumen', '总结提示词': 'Prompt de resumen', '编辑提示词': 'Editar prompt', '配置 JSON': 'JSON de configuración', '当前启用的纪要模型配置。': 'La configuración activa del modelo de resumen.'
});
Object.assign(catalog.zh.labels, {
  '分钟': '分钟', '本地录音': '本地录音', '本地保存': '本地保存', '本地会议': '本地会议',
  '← 返回会议库': '← 返回会议库', '说话人分离': '说话人分离', '自定义术语': '自定义术语', '暂无术语': '暂无术语',
  '说话人': '说话人', '等待识别说话人': '等待识别说话人',
  '原始录音与每版逐字稿均保存在本机': '原始录音与每版逐字稿均保存在本机',
  '会议摘要': '会议摘要', '尚未生成会议摘要': '尚未生成会议摘要', '转发': '转发',
  '会后精修': '会后精修', '精修': '精修', '正在精修…': '正在精修…',
  '会后精修已完成': '会后精修已完成', '已整理': '已整理', '决定': '决定', '待办': '待办'
});
Object.assign(catalog.en.labels, {
  '分钟': 'min', '本地录音': 'Local recording', '本地保存': 'Saved locally', '本地会议': 'Local meeting',
  '← 返回会议库': '← Back to library', '说话人分离': 'Speaker diarization', '自定义术语': 'Custom term', '暂无术语': 'No terms',
  '说话人': 'Speaker', '等待识别说话人': 'Waiting to identify speakers',
  '原始录音与每版逐字稿均保存在本机': 'The original recording and every transcript version stay on this device',
  '会议摘要': 'Meeting summary', '尚未生成会议摘要': 'No meeting summary yet', '转发': 'Share',
  '会后精修': 'Refine', '精修': 'Refine', '正在精修…': 'Refining…',
  '会后精修已完成': 'Refinement complete', '已整理': 'Complete', '决定': 'Decisions', '待办': 'Action items'
});
Object.assign(catalog.es.labels, {
  '分钟': 'min', '本地录音': 'Grabación local', '本地保存': 'Guardado localmente', '本地会议': 'Reunión local',
  '← 返回会议库': '← Volver a la biblioteca', '说话人分离': 'Separación de hablantes', '自定义术语': 'Término personalizado', '暂无术语': 'No hay términos',
  '说话人': 'Hablante', '等待识别说话人': 'Esperando identificar hablantes',
  '原始录音与每版逐字稿均保存在本机': 'La grabación original y cada versión de la transcripción se guardan en este dispositivo',
  '会议摘要': 'Resumen de la reunión', '尚未生成会议摘要': 'Aún no se ha generado el resumen', '转发': 'Compartir',
  '会后精修': 'Refinar', '精修': 'Refinar', '正在精修…': 'Refinando…',
  '会后精修已完成': 'Refinamiento completado', '已整理': 'Completado', '决定': 'Decisiones', '待办': 'Tareas'
});
const localeCopies = {
  ja: { views: ['すべての会議', '録音の準備', '録音中', '会議の詳細', '設定'], labels: { '所有会议': 'すべての会議', '最近删除': '最近削除した項目', '设置': '設定', '开始会议': '会議を開始', '会议库': '会議ライブラリ', '准备录制': '録音の準備', '实时字幕': 'ライブ字幕', '会议详情': '会議の詳細', '本地优先': 'ローカル優先', '音频与文本仅保存在此设备': '音声とテキストはこのデバイスにのみ保存されます', '搜索会议、逐字稿或标签': '会議、文字起こし、タグを検索', '所有分类': 'すべての分類', '最近 30 天': '過去30日間', '返回会议库': 'ライブラリに戻る', '开始一场会议': '会議を開始', '会议名称': '会議名', '会议语言': '会議の言語', '译文目标': '翻訳先', '录制音频': '音声を録音', '我的麦克风': 'マイク', '系统音频': 'システム音声', '输入良好': '入力は良好です', '已就绪': '準備完了', '当前模型': '現在のモデル', '正在录制': '録音中', '暂停': '一時停止', '继续': '再開', '结束会议': '会議を終了', '参与者': '参加者', '本场状态': 'セッションの状態', '逐字稿': '文字起こし', '摘要': '要約', '导出': 'エクスポート', '模型与本地数据': 'モデルとローカルデータ', '已安装模型': 'インストール済みモデル', '下载更多模型': 'さらにモデルをダウンロード', '术语库': '用語集', '管理术语库': '用語集を管理', '存储与隐私': 'ストレージとプライバシー', '查看本地存储': 'ローカルストレージを表示', '切换语言': '言語を切り替え', '切换主题': 'テーマを切り替え', '播放此段': '再生', '不需要翻译': '翻訳しない', '自动检测': '自動検出' }, messages: { recordingSaved: '録音を保存しました。文字起こしを準備しています。', located: '該当する音声位置に移動しました', playing: 'ミックス音声を再生中', paused: '再生を一時停止しました' } },
  ko: { views: ['모든 회의', '녹음 준비', '녹음 중', '회의 세부 정보', '설정'], labels: { '所有会议': '모든 회의', '最近删除': '최근 삭제됨', '设置': '설정', '开始会议': '회의 시작', '会议库': '회의 라이브러리', '准备录制': '녹음 준비', '实时字幕': '실시간 자막', '会议详情': '회의 세부 정보', '本地优先': '로컬 우선', '音频与文本仅保存在此设备': '오디오와 텍스트는 이 기기에만 저장됩니다', '搜索会议、逐字稿或标签': '회의, 녹취 또는 태그 검색', '所有分类': '모든 분류', '最近 30 天': '최근 30일', '返回会议库': '라이브러리로 돌아가기', '开始一场会议': '회의 시작', '会议名称': '회의 이름', '会议语言': '회의 언어', '译文目标': '번역 대상', '录制音频': '오디오 녹음', '我的麦克风': '내 마이크', '系统音频': '시스템 오디오', '输入良好': '입력 양호', '已就绪': '준비됨', '当前模型': '현재 모델', '正在录制': '녹음 중', '暂停': '일시 정지', '继续': '계속', '结束会议': '회의 종료', '参与者': '참가자', '本场状态': '세션 상태', '逐字稿': '녹취', '摘要': '요약', '导出': '내보내기', '模型与本地数据': '모델 및 로컬 데이터', '已安装模型': '설치된 모델', '下载更多模型': '모델 더 다운로드', '术语库': '용어집', '管理术语库': '용어집 관리', '存储与隐私': '저장 공간 및 개인정보', '查看本地存储': '로컬 저장 공간 보기', '切换语言': '언어 전환', '切换主题': '테마 전환', '播放此段': '재생', '不需要翻译': '번역 안 함', '自动检测': '자동 감지' }, messages: { recordingSaved: '녹음이 저장되었습니다. 녹취를 준비합니다.', located: '연결된 오디오 구간으로 이동했습니다', playing: '믹스 트랙 재생 중', paused: '재생이 일시 정지되었습니다' } },
  fr: { views: ['Toutes les réunions', 'Préparer la réunion', 'Enregistrement', 'Détails de la réunion', 'Paramètres'], labels: { '所有会议': 'Toutes les réunions', '最近删除': 'Supprimées récemment', '设置': 'Paramètres', '开始会议': 'Démarrer la réunion', '会议库': 'Bibliothèque de réunions', '准备录制': 'Préparer l’enregistrement', '实时字幕': 'Transcription en direct', '会议详情': 'Détails de la réunion', '本地优先': 'Priorité au local', '音频与文本仅保存在此设备': 'L’audio et le texte restent sur cet appareil', '搜索会议、逐字稿或标签': 'Rechercher des réunions, transcriptions ou étiquettes', '所有分类': 'Toutes les catégories', '最近 30 天': '30 derniers jours', '返回会议库': 'Retour à la bibliothèque', '开始一场会议': 'Démarrer une réunion', '会议名称': 'Nom de la réunion', '会议语言': 'Langue de la réunion', '译文目标': 'Langue cible', '录制音频': 'Capture audio', '我的麦克风': 'Mon microphone', '系统音频': 'Audio système', '输入良好': 'Entrée prête', '已就绪': 'Prêt', '当前模型': 'Modèle actuel', '正在录制': 'Enregistrement', '暂停': 'Pause', '继续': 'Reprendre', '结束会议': 'Terminer la réunion', '参与者': 'Participants', '本场状态': 'État de la session', '逐字稿': 'Transcription', '摘要': 'Résumé', '导出': 'Exporter', '模型与本地数据': 'Modèles et données locales', '已安装模型': 'Modèles installés', '下载更多模型': 'Télécharger des modèles', '术语库': 'Glossaire', '管理术语库': 'Gérer le glossaire', '存储与隐私': 'Stockage et confidentialité', '查看本地存储': 'Voir le stockage local', '切换语言': 'Changer de langue', '切换主题': 'Changer de thème', '播放此段': 'Lire', '不需要翻译': 'Aucune traduction', '自动检测': 'Détection automatique' }, messages: { recordingSaved: 'Enregistrement sauvegardé. Préparation de la transcription.', located: 'Positionné sur le segment audio lié', playing: 'Lecture de la piste mixée', paused: 'Lecture en pause' } },
  de: { views: ['Alle Besprechungen', 'Aufnahme vorbereiten', 'Aufnahme läuft', 'Besprechungsdetails', 'Einstellungen'], labels: { '所有会议': 'Alle Besprechungen', '最近删除': 'Kürzlich gelöscht', '设置': 'Einstellungen', '开始会议': 'Besprechung starten', '会议库': 'Besprechungsbibliothek', '准备录制': 'Aufnahme vorbereiten', '实时字幕': 'Live-Transkript', '会议详情': 'Besprechungsdetails', '本地优先': 'Lokal zuerst', '音频与文本仅保存在此设备': 'Audio und Text bleiben auf diesem Gerät', '搜索会议、逐字稿或标签': 'Besprechungen, Transkripte oder Tags suchen', '所有分类': 'Alle Kategorien', '最近 30 天': 'Letzte 30 Tage', '返回会议库': 'Zurück zur Bibliothek', '开始一场会议': 'Besprechung starten', '会议名称': 'Besprechungsname', '会议语言': 'Besprechungssprache', '译文目标': 'Zielsprache', '录制音频': 'Audio aufnehmen', '我的麦克风': 'Mein Mikrofon', '系统音频': 'Systemaudio', '输入良好': 'Eingang bereit', '已就绪': 'Bereit', '当前模型': 'Aktuelles Modell', '正在录制': 'Aufnahme läuft', '暂停': 'Pausieren', '继续': 'Fortsetzen', '结束会议': 'Besprechung beenden', '参与者': 'Teilnehmende', '本场状态': 'Sitzungsstatus', '逐字稿': 'Transkript', '摘要': 'Zusammenfassung', '导出': 'Exportieren', '模型与本地数据': 'Modelle und lokale Daten', '已安装模型': 'Installierte Modelle', '下载更多模型': 'Weitere Modelle herunterladen', '术语库': 'Terminologie', '管理术语库': 'Terminologie verwalten', '存储与隐私': 'Speicher und Datenschutz', '查看本地存储': 'Lokalen Speicher anzeigen', '切换语言': 'Sprache wechseln', '切换主题': 'Design wechseln', '播放此段': 'Wiedergabe', '不需要翻译': 'Keine Übersetzung', '自动检测': 'Automatisch erkennen' }, messages: { recordingSaved: 'Aufnahme gespeichert. Transkript wird vorbereitet.', located: 'Zum verknüpften Audiosegment gesprungen', playing: 'Gemischte Spur wird wiedergegeben', paused: 'Wiedergabe pausiert' } },
  ru: { views: ['Все встречи', 'Подготовка записи', 'Идёт запись', 'Сведения о встрече', 'Настройки'], labels: { '所有会议': 'Все встречи', '最近删除': 'Недавно удалённые', '设置': 'Настройки', '开始会议': 'Начать встречу', '会议库': 'Библиотека встреч', '准备录制': 'Подготовка записи', '实时字幕': 'Субтитры в реальном времени', '会议详情': 'Сведения о встрече', '本地优先': 'Локальное хранение', '音频与文本仅保存在此设备': 'Аудио и текст хранятся только на этом устройстве', '搜索会议、逐字稿或标签': 'Поиск встреч, расшифровок или тегов', '所有分类': 'Все категории', '最近 30 天': 'Последние 30 дней', '返回会议库': 'Вернуться в библиотеку', '开始一场会议': 'Начать встречу', '会议名称': 'Название встречи', '会议语言': 'Язык встречи', '译文目标': 'Язык перевода', '录制音频': 'Запись аудио', '我的麦克风': 'Мой микрофон', '系统音频': 'Системный звук', '输入良好': 'Вход готов', '已就绪': 'Готово', '当前模型': 'Текущая модель', '正在录制': 'Идёт запись', '暂停': 'Пауза', '继续': 'Продолжить', '结束会议': 'Завершить встречу', '参与者': 'Участники', '本场状态': 'Статус сеанса', '逐字稿': 'Расшифровка', '摘要': 'Сводка', '导出': 'Экспорт', '模型与本地数据': 'Модели и локальные данные', '已安装模型': 'Установленные модели', '下载更多模型': 'Скачать модели', '术语库': 'Глоссарий', '管理术语库': 'Управление глоссарием', '存储与隐私': 'Хранилище и конфиденциальность', '查看本地存储': 'Открыть локальное хранилище', '切换语言': 'Сменить язык', '切换主题': 'Сменить тему', '播放此段': 'Воспроизвести', '不需要翻译': 'Без перевода', '自动检测': 'Автоопределение' }, messages: { recordingSaved: 'Запись сохранена. Подготавливается расшифровка.', located: 'Переход к связанному фрагменту аудио', playing: 'Воспроизводится смешанная дорожка', paused: 'Воспроизведение приостановлено' } },
};
Object.entries(localeCopies).forEach(([code, copy]) => {
  const [home, prepare, live, detail, settings] = copy.views;
  catalog[code] = { views: { home, prepare, live, detail, settings }, labels: { ...catalog.en.labels, ...copy.labels }, messages: copy.messages };
});
const interfaceLabels = {
  zh: { '分类标签': '分类标签', '未分类': '未分类', '最近 7 天': '最近 7 天', '最近 90 天': '最近 90 天', '全部时间': '全部时间', '系统默认麦克风': '系统默认麦克风', '需要授予屏幕与系统音频权限': '需要授予屏幕与系统音频权限', '流式模型': '流式模型', '中文 / 英语': '中文 / 英语', '管理模型与术语': '管理模型与术语', '更多操作': '更多操作', '恢复': '恢复', '重命名': '重命名', '分类': '分类', '删除': '删除', '取消': '取消', '保存': '保存', '添加': '添加', '新分类名称': '新分类名称', '开始录制': '开始录制', '本地录音': '本地录音', '中文实时字幕 · sherpa-onnx': '中文实时字幕 · sherpa-onnx', '英文实时字幕 · sherpa-onnx': '英文实时字幕 · sherpa-onnx', '会后精修 · sherpa-onnx · CUDA': '会后精修 · sherpa-onnx · CUDA', '端点检测与说话人分配 · sherpa-onnx': '端点检测与说话人分配 · sherpa-onnx', '实时字幕 · 中文 / 英语 / 粤语': '实时字幕 · 中文 / 英语 / 粤语', '原生流式识别，持续更新当前字幕。': '原生流式识别，持续更新当前字幕。', '会后精修 · 多语种': '会后精修 · 多语种', '基于完整录音生成高精度修订版本。': '基于完整录音生成高精度修订版本。' },
  en: { '分类标签': 'Category', '未分类': 'Uncategorized', '最近 7 天': 'Last 7 days', '最近 90 天': 'Last 90 days', '全部时间': 'All time', '系统默认麦克风': 'System default microphone', '需要授予屏幕与系统音频权限': 'Screen and system-audio permission required', '流式模型': 'Streaming model', '中文 / 英语': 'Chinese / English', '管理模型与术语': 'Manage models and terms', '更多操作': 'More actions', '恢复': 'Restore', '重命名': 'Rename', '分类': 'Category', '删除': 'Delete', '取消': 'Cancel', '保存': 'Save', '添加': 'Add', '新分类名称': 'New category name', '开始录制': 'Start recording', '本地录音': 'Local recording', '中文实时字幕 · sherpa-onnx': 'Chinese live captions · sherpa-onnx', '英文实时字幕 · sherpa-onnx': 'English live captions · sherpa-onnx', '会后精修 · sherpa-onnx · CUDA': 'Post-meeting refinement · sherpa-onnx · CUDA', '端点检测与说话人分配 · sherpa-onnx': 'Endpoint detection and speaker assignment · sherpa-onnx', '实时字幕 · 中文 / 英语 / 粤语': 'Live captions · Chinese / English / Cantonese', '原生流式识别，持续更新当前字幕。': 'Native streaming recognition that continuously updates the active caption.', '会后精修 · 多语种': 'Post-meeting refinement · Multilingual', '基于完整录音生成高精度修订版本。': 'Creates a high-accuracy revision from the complete recording.' },
  es: { '分类标签': 'Categoría', '未分类': 'Sin categoría', '最近 7 天': 'Últimos 7 días', '最近 90 天': 'Últimos 90 días', '全部时间': 'Todo el tiempo', '系统默认麦克风': 'Micrófono predeterminado del sistema', '需要授予屏幕与系统音频权限': 'Se requiere permiso para pantalla y audio del sistema', '流式模型': 'Modelo en streaming', '中文 / 英语': 'Chino / inglés', '管理模型与术语': 'Gestionar modelos y términos', '更多操作': 'Más acciones', '恢复': 'Restaurar', '重命名': 'Renombrar', '分类': 'Categoría', '删除': 'Eliminar', '取消': 'Cancelar', '保存': 'Guardar', '添加': 'Añadir', '新分类名称': 'Nombre de categoría', '开始录制': 'Iniciar grabación', '本地录音': 'Grabación local' },
  ja: { '分类标签': 'カテゴリ', '未分类': '未分類', '最近 7 天': '過去7日間', '最近 90 天': '過去90日間', '全部时间': 'すべての期間', '系统默认麦克风': 'システムのデフォルトマイク', '需要授予屏幕与系统音频权限': '画面とシステム音声のアクセス許可が必要です', '流式模型': 'ストリーミングモデル', '中文 / 英语': '中国語 / 英語', '管理模型与术语': 'モデルと用語を管理', '更多操作': 'その他の操作', '恢复': '復元', '重命名': '名前を変更', '分类': 'カテゴリ', '删除': '削除', '取消': 'キャンセル', '保存': '保存', '添加': '追加', '新分类名称': '新しいカテゴリ名', '开始录制': '録音を開始', '本地录音': 'ローカル録音' },
  ko: { '分类标签': '분류', '未分类': '미분류', '最近 7 天': '최근 7일', '最近 90 天': '최근 90일', '全部时间': '전체 기간', '系统默认麦克风': '시스템 기본 마이크', '需要授予屏幕与系统音频权限': '화면 및 시스템 오디오 권한이 필요합니다', '流式模型': '스트리밍 모델', '中文 / 英语': '중국어 / 영어', '管理模型与术语': '모델 및 용어 관리', '更多操作': '추가 작업', '恢复': '복원', '重命名': '이름 바꾸기', '分类': '분류', '删除': '삭제', '取消': '취소', '保存': '저장', '添加': '추가', '新分类名称': '새 분류 이름', '开始录制': '녹음 시작', '本地录音': '로컬 녹음' },
  fr: { '分类标签': 'Catégorie', '未分类': 'Sans catégorie', '最近 7 天': '7 derniers jours', '最近 90 天': '90 derniers jours', '全部时间': 'Toute la période', '系统默认麦克风': 'Microphone système par défaut', '需要授予屏幕与系统音频权限': 'Autorisation d’écran et d’audio système requise', '流式模型': 'Modèle en continu', '中文 / 英语': 'Chinois / anglais', '管理模型与术语': 'Gérer les modèles et les termes', '更多操作': 'Plus d’actions', '恢复': 'Restaurer', '重命名': 'Renommer', '分类': 'Catégorie', '删除': 'Supprimer', '取消': 'Annuler', '保存': 'Enregistrer', '添加': 'Ajouter', '新分类名称': 'Nouveau nom de catégorie', '开始录制': 'Démarrer l’enregistrement', '本地录音': 'Enregistrement local' },
  de: { '分类标签': 'Kategorie', '未分类': 'Nicht kategorisiert', '最近 7 天': 'Letzte 7 Tage', '最近 90 天': 'Letzte 90 Tage', '全部时间': 'Gesamter Zeitraum', '系统默认麦克风': 'Standardmikrofon des Systems', '需要授予屏幕与系统音频权限': 'Berechtigung für Bildschirm und Systemaudio erforderlich', '流式模型': 'Streaming-Modell', '中文 / 英语': 'Chinesisch / Englisch', '管理模型与术语': 'Modelle und Begriffe verwalten', '更多操作': 'Weitere Aktionen', '恢复': 'Wiederherstellen', '重命名': 'Umbenennen', '分类': 'Kategorie', '删除': 'Löschen', '取消': 'Abbrechen', '保存': 'Speichern', '添加': 'Hinzufügen', '新分类名称': 'Neuer Kategoriename', '开始录制': 'Aufnahme starten', '本地录音': 'Lokale Aufnahme' },
  ru: { '分类标签': 'Категория', '未分类': 'Без категории', '最近 7 天': 'Последние 7 дней', '最近 90 天': 'Последние 90 дней', '全部时间': 'За всё время', '系统默认麦克风': 'Системный микрофон по умолчанию', '需要授予屏幕与系统音频权限': 'Требуется доступ к экрану и системному звуку', '流式模型': 'Потоковая модель', '中文 / 英语': 'Китайский / английский', '管理模型与术语': 'Управление моделями и терминами', '更多操作': 'Другие действия', '恢复': 'Восстановить', '重命名': 'Переименовать', '分类': 'Категория', '删除': 'Удалить', '取消': 'Отмена', '保存': 'Сохранить', '添加': 'Добавить', '新分类名称': 'Название категории', '开始录制': 'Начать запись', '本地录音': 'Локальная запись' },
};
Object.entries(interfaceLabels).forEach(([code, labels]) => Object.assign(catalog[code].labels, labels));
Object.assign(catalog.en.labels, { '正在精修': 'Refining', '原版逐字稿仍可查看': 'The original transcript remains available', '准备中': 'Preparing' });
Object.assign(catalog.es.labels, { '正在精修': 'Refinando', '原版逐字稿仍可查看': 'La transcripción original sigue disponible', '准备中': 'Preparando' });
Object.assign(catalog.ja.labels, { '计算设备': '演算デバイス', '会后精修': '会議後の高精度化', '正在精修': '高精度化中', '原版逐字稿仍可查看': '元の文字起こしは引き続き閲覧できます', '准备中': '準備中', '可用': '利用可能', '本地保存': 'ローカルに保存', '本地会议': 'ローカル会議', '← 返回会议库': '← ライブラリに戻る', '原始录音与每版逐字稿均保存在本机': '元の録音とすべての文字起こし版はこのデバイスに保存されます' });
Object.assign(catalog.ko.labels, { '计算设备': '연산 장치', '会后精修': '회의 후 정제', '正在精修': '정제 중', '原版逐字稿仍可查看': '원본 녹취는 계속 볼 수 있습니다', '准备中': '준비 중', '可用': '사용 가능', '本地保存': '로컬에 저장됨', '本地会议': '로컬 회의', '← 返回会议库': '← 라이브러리로 돌아가기', '原始录音与每版逐字稿均保存在本机': '원본 녹음과 모든 녹취 버전은 이 기기에 저장됩니다' });
Object.assign(catalog.fr.labels, { '计算设备': 'Appareil de calcul', '会后精修': 'Affinage après réunion', '正在精修': 'Affinage en cours', '原版逐字稿仍可查看': 'La transcription d’origine reste disponible', '准备中': 'Préparation', '可用': 'Disponible', '本地保存': 'Enregistré localement', '本地会议': 'Réunion locale', '← 返回会议库': '← Retour à la bibliothèque', '原始录音与每版逐字稿均保存在本机': 'L’enregistrement original et toutes les versions de la transcription restent sur cet appareil' });
Object.assign(catalog.de.labels, { '计算设备': 'Rechengerät', '会后精修': 'Nachbearbeitung', '正在精修': 'Nachbearbeitung läuft', '原版逐字稿仍可查看': 'Das ursprüngliche Transkript bleibt verfügbar', '准备中': 'Vorbereitung', '可用': 'Verfügbar', '本地保存': 'Lokal gespeichert', '本地会议': 'Lokale Besprechung', '← 返回会议库': '← Zurück zur Bibliothek', '原始录音与每版逐字稿均保存在本机': 'Die Originalaufnahme und jede Transkriptversion bleiben auf diesem Gerät' });
Object.assign(catalog.ru.labels, { '计算设备': 'Вычислительное устройство', '会后精修': 'Обработка после встречи', '正在精修': 'Идёт обработка', '原版逐字稿仍可查看': 'Исходная расшифровка остаётся доступна', '准备中': 'Подготовка', '可用': 'Доступно', '本地保存': 'Сохранено локально', '本地会议': 'Локальная встреча', '← 返回会议库': '← Вернуться в библиотеку', '原始录音与每版逐字稿均保存在本机': 'Исходная запись и все версии расшифровки хранятся на этом устройстве' });
const settingsLabels = {
  ja: { '会议摘要': '会議の要約', '尚未生成会议摘要': '会議の要約はまだありません', '生成完整会议纪要': '会議メモを生成', '转发': '共有', '已整理': '完了', '已完成': '完了', '处理中': '処理中', '纪要模型': '要約モデル', '管理纪要模型': '要約モデルを管理', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': '会議メモを生成する API を設定します。すべての設定はローカルに保存されます。', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': '会議データはこの Mac に保存されます。外部 LLM への送信には明示的な確認が必要です。', '返回会议库': 'ライブラリに戻る', '暂无术语': '用語はありません', '软件更新': 'ソフトウェアアップデート', '当前版本 0.1.0': '現在のバージョン 0.1.0', '检查更新': 'アップデートを確認' },
  ko: { '会议摘要': '회의 요약', '尚未生成会议摘要': '아직 회의 요약이 없습니다', '生成完整会议纪要': '회의록 생성', '转发': '공유', '已整理': '완료', '已完成': '완료', '处理中': '처리 중', '纪要模型': '요약 모델', '管理纪要模型': '요약 모델 관리', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': '회의록 생성 API를 설정합니다. 모든 설정은 로컬에만 저장됩니다.', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': '회의 데이터는 이 Mac에 저장됩니다. 외부 LLM 전송 전 명시적 확인이 필요합니다.', '返回会议库': '라이브러리로 돌아가기', '暂无术语': '용어 없음', '软件更新': '소프트웨어 업데이트', '当前版本 0.1.0': '현재 버전 0.1.0', '检查更新': '업데이트 확인' },
  fr: { '会议摘要': 'Résumé de la réunion', '尚未生成会议摘要': 'Aucun résumé de réunion', '生成完整会议纪要': 'Générer les notes de réunion', '转发': 'Partager', '已整理': 'Terminé', '已完成': 'Terminé', '处理中': 'En cours', '纪要模型': 'Modèles de résumé', '管理纪要模型': 'Gérer les modèles de résumé', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': 'Configurez les API pour les notes de réunion. Toute la configuration reste locale.', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': 'Les données de réunion restent sur ce Mac. Les LLM externes exigent une confirmation explicite.', '返回会议库': 'Retour à la bibliothèque', '暂无术语': 'Aucun terme', '软件更新': 'Mises à jour logicielles', '当前版本 0.1.0': 'Version actuelle 0.1.0', '检查更新': 'Rechercher des mises à jour' },
  de: { '会议摘要': 'Besprechungszusammenfassung', '尚未生成会议摘要': 'Noch keine Zusammenfassung', '生成完整会议纪要': 'Besprechungsnotizen erstellen', '转发': 'Teilen', '已整理': 'Abgeschlossen', '已完成': 'Abgeschlossen', '处理中': 'Wird verarbeitet', '纪要模型': 'Zusammenfassungsmodelle', '管理纪要模型': 'Zusammenfassungsmodelle verwalten', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': 'APIs für Besprechungsnotizen konfigurieren. Alle Einstellungen bleiben lokal.', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': 'Besprechungsdaten bleiben auf diesem Mac. Externe LLMs erfordern eine ausdrückliche Bestätigung.', '返回会议库': 'Zurück zur Bibliothek', '暂无术语': 'Keine Begriffe', '软件更新': 'Softwareupdates', '当前版本 0.1.0': 'Aktuelle Version 0.1.0', '检查更新': 'Nach Updates suchen' },
  ru: { '会议摘要': 'Сводка встречи', '尚未生成会议摘要': 'Сводки встречи пока нет', '生成完整会议纪要': 'Создать заметки встречи', '转发': 'Поделиться', '已整理': 'Готово', '已完成': 'Готово', '处理中': 'Обработка', '纪要模型': 'Модели сводки', '管理纪要模型': 'Управление моделями сводки', '配置用于生成会议纪要的 API。所有配置信息仅保存在本地，不会上传。': 'Настройте API для заметок встречи. Все настройки хранятся локально.', '会议资料保存在此 Mac。外部 LLM 需要在发送逐字稿前明确确认。': 'Данные встречи хранятся на этом Mac. Для внешних LLM требуется явное подтверждение.', '返回会议库': 'Вернуться в библиотеку', '暂无术语': 'Нет терминов', '软件更新': 'Обновления ПО', '当前版本 0.1.0': 'Текущая версия 0.1.0', '检查更新': 'Проверить обновления' }
};
Object.entries(settingsLabels).forEach(([code, labels]) => Object.assign(catalog[code].labels, labels));
const modelLibraryLabels = {
  zh: { '模型库': '模型库', '管理模型库': '管理模型库', '管理语言识别模型的下载、删除与版本信息。': '管理语言识别模型的下载、删除与版本信息。' },
  en: { '模型库': 'Model library', '管理模型库': 'Manage model library', '管理语言识别模型的下载、删除与版本信息。': 'Manage downloads, removal, and version details for speech-recognition models.' },
  es: { '模型库': 'Biblioteca de modelos', '管理模型库': 'Gestionar la biblioteca de modelos', '管理语言识别模型的下载、删除与版本信息。': 'Gestiona las descargas, eliminaciones y versiones de los modelos de reconocimiento de voz.' },
  ja: { '模型库': 'モデルライブラリ', '管理模型库': 'モデルライブラリを管理', '管理语言识别模型的下载、删除与版本信息。': '音声認識モデルのダウンロード、削除、バージョン情報を管理します。' },
  ko: { '模型库': '모델 라이브러리', '管理模型库': '모델 라이브러리 관리', '管理语言识别模型的下载、删除与版本信息。': '음성 인식 모델의 다운로드, 삭제 및 버전 정보를 관리합니다.' },
  fr: { '模型库': 'Bibliothèque de modèles', '管理模型库': 'Gérer la bibliothèque de modèles', '管理语言识别模型的下载、删除与版本信息。': 'Gérez les téléchargements, la suppression et les versions des modèles de reconnaissance vocale.' },
  de: { '模型库': 'Modellbibliothek', '管理模型库': 'Modellbibliothek verwalten', '管理语言识别模型的下载、删除与版本信息。': 'Verwalten Sie Downloads, Löschungen und Versionsinformationen von Spracherkennungsmodellen.' },
  ru: { '模型库': 'Библиотека моделей', '管理模型库': 'Управление библиотекой моделей', '管理语言识别模型的下载、删除与版本信息。': 'Управляйте загрузкой, удалением и сведениями о версиях моделей распознавания речи.' },
};
Object.entries(modelLibraryLabels).forEach(([code, labels]) => Object.assign(catalog[code].labels, labels));
const appCopy = {
  stageLabels: { 标点恢复: { zh: '标点恢复', en: 'Punctuation restoration', es: 'Restauración de puntuación' }, '预期说话人数': { zh: '预期说话人数', en: 'Expected speakers', es: 'Hablantes esperados' }, '留空自动匹配': { zh: '留空自动匹配', en: 'Leave blank for automatic matching', es: 'Déjalo vacío para la selección automática' }, '自动匹配': { zh: '自动匹配', en: 'Automatic matching', es: 'Selección automática' } },
  themeLabels: { zh: { light: '切换至浅色主题', dark: '切换至深色主题' }, en: { light: 'Switch to light theme', dark: 'Switch to dark theme' }, es: { light: 'Cambiar al tema claro', dark: 'Cambiar al tema oscuro' } },
  updateLabels: { zh: { title: '软件更新', description: '当前版本 0.1.0', action: '检查更新', checking: '正在检查…', available: '发现新版本 0.2.0', update: '更新至 0.2.0', floating: '更新 Brevia', updating: '正在更新…', current: '已是最新版本' }, en: { title: 'Software updates', description: 'Current version 0.1.0', action: 'Check for updates', checking: 'Checking…', available: 'Version 0.2.0 is available', update: 'Update to 0.2.0', floating: 'Update Brevia', updating: 'Updating…', current: 'Up to date' }, es: { title: 'Actualizaciones', description: 'Versión actual 0.1.0', action: 'Buscar actualizaciones', checking: 'Comprobando…', available: 'La versión 0.2.0 está disponible', update: 'Actualizar a 0.2.0', floating: 'Actualizar Brevia', updating: 'Actualizando…', current: 'Ya está actualizado' } },
  modelLabels: { zh: { manage: '管理模型库', download: '下载', downloading: '下载中…', installed: '已安装', remove: '删除' }, en: { manage: 'Manage model library', download: 'Download', downloading: 'Downloading…', installed: 'Installed', remove: 'Delete' }, es: { manage: 'Gestionar biblioteca de modelos', download: 'Descargar', downloading: 'Descargando…', installed: 'Instalado', remove: 'Eliminar' } },
  summaryModelCopy: { zh: { title: '管理纪要模型', intro: '所有配置信息仅保存在本地，不会上传。', name: '配置名', provider: '供应商', key: 'API Key', endpoint: '请求地址', format: 'API 格式', model: '主模型', save: '保存配置', add: '新建配置', remove: '删除配置', configured: '已配置模型', active: '正在使用', promptTitle: '总结提示词', promptIntro: '该提示词将用于生成 AI 会议纪要。', jsonTitle: '配置 JSON', jsonIntro: '当前启用的纪要模型配置。', ollama: '本地 Ollama', openAIFormat: 'OpenAI 格式', claudeFormat: 'Claude 格式' }, en: { title: 'Manage summary models', intro: 'All configuration stays on this device and is never uploaded.', name: 'Configuration name', provider: 'Provider', key: 'API Key', endpoint: 'Request URL', format: 'API format', model: 'Primary model', save: 'Save configuration', add: 'New configuration', remove: 'Delete configuration', configured: 'Configured models', active: 'In use', promptTitle: 'Summary prompt', promptIntro: 'This prompt is used to generate AI meeting notes.', jsonTitle: 'Configuration JSON', jsonIntro: 'The active summary model configuration.', ollama: 'Local Ollama', openAIFormat: 'OpenAI format', claudeFormat: 'Claude format' }, es: { title: 'Gestionar modelos de resumen', intro: 'Toda la configuración se guarda en este dispositivo y no se carga.', name: 'Nombre de configuración', provider: 'Proveedor', key: 'API Key', endpoint: 'URL de solicitud', format: 'Formato de API', model: 'Modelo principal', save: 'Guardar configuración', add: 'Nueva configuración', remove: 'Eliminar configuración', configured: 'Modelos configurados', active: 'En uso', promptTitle: 'Prompt de resumen', promptIntro: 'Este prompt se usa para generar notas de reunión con IA.', jsonTitle: 'JSON de configuración', jsonIntro: 'La configuración activa del modelo de resumen.', ollama: 'Ollama local', openAIFormat: 'Formato OpenAI', claudeFormat: 'Formato Claude' } },
  speakerProfileCopy: {
    zh: { title: '说话人识别', intro: '仅保存用户明确提交的单人语音，用于会议片段的说话人识别与命名。', name: '人员姓名', add: '从语音添加', addSample: '补充语音样本', remove: '删除', samples: '条样本', empty: '还没有已识别人员。上传一段清晰的单人语音开始识别。' },
    en: { title: 'Speaker recognition', intro: 'Only explicitly submitted single-speaker audio is saved for identifying and naming meeting speakers.', name: 'Name', add: 'Add from audio', addSample: 'Add voice sample', remove: 'Delete', samples: 'samples', empty: 'No identified speakers yet. Upload a clear recording of one person to begin.' },
    es: { title: 'Reconocimiento de hablantes', intro: 'Solo se guarda audio de una persona enviado expresamente para identificar y nombrar a los hablantes de la reunión.', name: 'Nombre', add: 'Añadir desde audio', addSample: 'Añadir muestra de voz', remove: 'Eliminar', samples: 'muestras', empty: 'Aún no hay hablantes identificados. Sube una grabación clara de una persona para empezar.' },
    ja: { title: '話者認識', intro: '明示的に送信した単一話者の音声だけを保存し、会議中の話者の識別と命名に使用します。', name: '名前', add: '音声から追加', addSample: '音声サンプルを追加', remove: '削除', samples: 'サンプル', empty: '識別済みの話者はいません。1 人だけの明瞭な音声をアップロードしてください。' },
    ko: { title: '화자 인식', intro: '명시적으로 제출한 1인 음성만 저장하며, 회의 화자를 식별하고 이름을 지정하는 데 사용합니다.', name: '이름', add: '오디오에서 추가', addSample: '음성 샘플 추가', remove: '삭제', samples: '개 샘플', empty: '식별된 화자가 없습니다. 한 사람의 선명한 음성을 업로드하세요.' },
    fr: { title: 'Reconnaissance du locuteur', intro: 'Seuls les audios à un seul locuteur soumis explicitement sont enregistrés pour identifier et nommer les locuteurs de la réunion.', name: 'Nom', add: 'Ajouter depuis un audio', addSample: 'Ajouter un échantillon vocal', remove: 'Supprimer', samples: 'échantillons', empty: 'Aucun locuteur identifié. Importez un enregistrement clair d’une personne pour commencer.' },
    de: { title: 'Sprechererkennung', intro: 'Nur ausdrücklich übermittelte Einzelsprecher-Aufnahmen werden gespeichert, um Besprechungssprecher zu erkennen und zu benennen.', name: 'Name', add: 'Aus Audio hinzufügen', addSample: 'Sprachprobe hinzufügen', remove: 'Löschen', samples: 'Proben', empty: 'Noch keine Sprecher erkannt. Laden Sie eine klare Aufnahme einer Person hoch.' },
    ru: { title: 'Распознавание говорящих', intro: 'Сохраняются только явно отправленные записи одного человека для распознавания и именования говорящих на встрече.', name: 'Имя', add: 'Добавить из аудио', addSample: 'Добавить образец голоса', remove: 'Удалить', samples: 'образцов', empty: 'Пока нет распознанных говорящих. Загрузите чистую запись одного человека, чтобы начать.' },
  },
  modalCopy: {
    zh: { models: { title: '模型库', intro: '所有转写模型都在本地运行，不会将您的隐私上传到网络。', languages: '建议语言', items: [['实时字幕', 'Streaming Paraformer', '中文 / 英语 / 粤语', '原生流式识别，持续更新当前字幕。', '⌁'], ['实时字幕', 'Streaming Zipformer English', '英语', '英语原生流式识别。', 'Z'], ['标点恢复', 'English Punctuation and Casing', '英语', '恢复英文标点与大小写。', '·'], ['标点恢复', '中英文标点恢复', '中文 / 英语 / 粤语', '为实时字幕补全逗号、句号和问号。', '·'], ['会后精修', 'Qwen3-ASR', '多语种', '基于完整录音生成高精度修订版本。', 'Q'], ['说话人分离', 'Pyannote Segmentation 3.0', '语言无关', '检测单轨录音中的说话区间。', 'P'], ['说话人分离', '3D-Speaker ERes2Net Base', '中文', '提取声纹并离线聚类说话人。', '3D'], ['实时字幕', 'Streaming Zipformer Chinese XLarge', '中文', '更高精度的中文流式识别。', 'Z']] }, terms: { title: '管理术语库', intro: '术语用于会议准备、搜索和纪要。仅支持的模型会在转写中使用它们。', items: [['Brevia', '产品名称'], ['向量数据库', '技术术语'], ['CAM++', '说话人模型']], add: '添加术语', edit: '编辑', save: '保存', cancel: '取消', remove: '删除', placeholder: '输入术语或短语' }, storage: { title: '本地存储', intro: '所有会议资料均保存在此设备。', items: [['会议与录音', '8.4 GB'], ['模型文件', '1.7 GB'], ['导出文件', '240 MB']] }, close: '关闭', download: '下载' },
    en: { models: { title: 'Model library', intro: 'All transcription models run locally. Your private data is never uploaded to the network.', languages: 'Recommended languages', items: [['Live captions', 'Streaming Paraformer', 'Chinese / English / Cantonese', 'Native streaming recognition that continuously updates the active caption.', '⌁'], ['Live captions', 'Streaming Zipformer English', 'English', 'Native streaming recognition for English.', 'Z'], ['Punctuation restoration', 'English Punctuation and Casing', 'English', 'Restores English punctuation and casing.', '·'], ['Punctuation restoration', 'Chinese and English Punctuation', 'Chinese / English / Cantonese', 'Adds commas, full stops, and question marks to live captions.', '·'], ['Post-meeting refinement', 'Qwen3-ASR', 'Multilingual', 'Creates a high-accuracy revision from the complete recording.', 'Q'], ['Speaker diarization', 'Pyannote Segmentation 3.0', 'Language independent', 'Detects regions of speech in a single-track recording.', 'P'], ['Speaker diarization', '3D-Speaker ERes2Net Base', 'Chinese', 'Extracts speaker embeddings for offline clustering.', '3D'], ['Live captions', 'Streaming Zipformer Chinese XLarge', 'Chinese', 'Higher-accuracy Chinese streaming recognition.', 'Z']] }, terms: { title: 'Manage terms', intro: 'Terms support meeting preparation, search, and notes. Only supported models use them in transcription.', items: [['Brevia', 'Product name'], ['Vector database', 'Technical term'], ['CAM++', 'Speaker model']], add: 'Add term', edit: 'Edit', save: 'Save', cancel: 'Cancel', remove: 'Delete', placeholder: 'Enter a term or phrase' }, storage: { title: 'Local storage', intro: 'All meeting data stays on this device.', items: [['Meetings and recordings', '8.4 GB'], ['Model files', '1.7 GB'], ['Exports', '240 MB']] }, close: 'Close', download: 'Download' },
    es: { models: { title: 'Biblioteca de modelos', intro: 'Todos los modelos de transcripción se ejecutan localmente. Tus datos privados nunca se suben a la red.', languages: 'Idiomas recomendados', items: [['Subtítulos en vivo', 'Streaming Paraformer', 'Chino / inglés / cantonés', 'Reconocimiento nativo en streaming que actualiza el subtítulo activo.', '⌁'], ['Subtítulos en vivo', 'Streaming Zipformer English', 'Inglés', 'Reconocimiento nativo para inglés.', 'Z'], ['Restauración de puntuación', 'English Punctuation and Casing', 'Inglés', 'Restaura puntuación y mayúsculas.', '·'], ['Restauración de puntuación', 'Puntuación chino-inglés', 'Chino / inglés / cantonés', 'Añade comas, puntos y signos de interrogación a los subtítulos en vivo.', '·'], ['Refinamiento posterior', 'Qwen3-ASR', 'Multilingüe', 'Crea una revisión precisa a partir de la grabación completa.', 'Q'], ['Separación de hablantes', 'Pyannote Segmentation 3.0', 'Independiente del idioma', 'Detecta regiones de habla en una grabación de una pista.', 'P'], ['Separación de hablantes', '3D-Speaker ERes2Net Base', 'Chino', 'Extrae huellas de voz para agrupar hablantes sin conexión.', '3D'], ['Subtítulos en vivo', 'Streaming Zipformer Chinese XLarge', 'Chino', 'Reconocimiento chino en streaming de mayor precisión.', 'Z']] }, terms: { title: 'Gestionar términos', intro: 'Los términos sirven para preparar reuniones, buscar y crear notas. Solo los modelos compatibles los usan al transcribir.', items: [['Brevia', 'Nombre del producto'], ['Base de datos vectorial', 'Término técnico'], ['CAM++', 'Modelo de hablantes']], add: 'Añadir término', edit: 'Editar', save: 'Guardar', cancel: 'Cancelar', remove: 'Eliminar', placeholder: 'Escribe un término o frase' }, storage: { title: 'Almacenamiento local', intro: 'Todos los datos de reuniones permanecen en este dispositivo.', items: [['Reuniones y grabaciones', '8.4 GB'], ['Archivos de modelos', '1.7 GB'], ['Exportaciones', '240 MB']] }, close: 'Cerrar', download: 'Descargar' },
  },
};
const appCopyLocales = {
  ja: { theme: { light: 'ライトテーマに切り替え', dark: 'ダークテーマに切り替え' }, update: { title: 'ソフトウェアアップデート', description: '現在のバージョン 0.1.0', action: 'アップデートを確認', checking: '確認中…', available: 'バージョン 0.2.0 を利用できます', update: '0.2.0 に更新', floating: 'Brevia を更新', updating: '更新中…', current: '最新です' }, model: { manage: 'モデルライブラリを管理', download: 'ダウンロード', downloading: 'ダウンロード中…', installed: 'インストール済み', remove: '削除' }, summary: { title: '要約モデルを管理', intro: 'すべての設定はこのデバイスにのみ保存され、アップロードされません。', name: '設定名', provider: 'プロバイダー', key: 'API キー', endpoint: 'リクエスト URL', format: 'API 形式', model: 'メインモデル', save: '設定を保存', add: '新しい設定', remove: '設定を削除', configured: '設定済みモデル', active: '使用中', promptTitle: '要約プロンプト', promptIntro: 'このプロンプトは AI 会議メモの生成に使われます。', jsonTitle: '設定 JSON', jsonIntro: '現在有効な要約モデル設定です。', ollama: 'ローカル Ollama', openAIFormat: 'OpenAI 形式', claudeFormat: 'Claude 形式' }, modal: { models: { title: 'モデルライブラリ', intro: 'すべての文字起こしモデルはローカルで実行され、個人データがネットワークに送信されることはありません。', languages: '推奨言語' }, terms: { title: '用語集を管理', intro: '用語は会議準備、検索、メモに使用されます。対応モデルだけが文字起こしに利用します。', add: '用語を追加', edit: '編集', save: '保存', cancel: 'キャンセル', remove: '削除', placeholder: '用語またはフレーズを入力' }, storage: { title: 'ローカルストレージ', intro: 'すべての会議データはこのデバイスに保存されます。' }, close: '閉じる', download: 'ダウンロード' } },
  ko: { theme: { light: '라이트 테마로 전환', dark: '다크 테마로 전환' }, update: { title: '소프트웨어 업데이트', description: '현재 버전 0.1.0', action: '업데이트 확인', checking: '확인 중…', available: '버전 0.2.0을 사용할 수 있습니다', update: '0.2.0으로 업데이트', floating: 'Brevia 업데이트', updating: '업데이트 중…', current: '최신 버전입니다' }, model: { manage: '모델 라이브러리 관리', download: '다운로드', downloading: '다운로드 중…', installed: '설치됨', remove: '삭제' }, summary: { title: '요약 모델 관리', intro: '모든 설정은 이 기기에만 저장되며 업로드되지 않습니다.', name: '구성 이름', provider: '제공자', key: 'API 키', endpoint: '요청 URL', format: 'API 형식', model: '기본 모델', save: '구성 저장', add: '새 구성', remove: '구성 삭제', configured: '구성된 모델', active: '사용 중', promptTitle: '요약 프롬프트', promptIntro: '이 프롬프트는 AI 회의록 생성에 사용됩니다.', jsonTitle: '구성 JSON', jsonIntro: '현재 활성 요약 모델 구성입니다.', ollama: '로컬 Ollama', openAIFormat: 'OpenAI 형식', claudeFormat: 'Claude 형식' }, modal: { models: { title: '모델 라이브러리', intro: '모든 전사 모델은 로컬에서 실행되며 개인 데이터가 네트워크로 업로드되지 않습니다.', languages: '권장 언어' }, terms: { title: '용어집 관리', intro: '용어는 회의 준비, 검색 및 회의록에 사용됩니다. 지원 모델만 전사에 사용합니다.', add: '용어 추가', edit: '편집', save: '저장', cancel: '취소', remove: '삭제', placeholder: '용어 또는 문구 입력' }, storage: { title: '로컬 저장소', intro: '모든 회의 데이터는 이 기기에 저장됩니다.' }, close: '닫기', download: '다운로드' } },
  fr: { theme: { light: 'Passer au thème clair', dark: 'Passer au thème sombre' }, update: { title: 'Mises à jour logicielles', description: 'Version actuelle 0.1.0', action: 'Rechercher des mises à jour', checking: 'Recherche…', available: 'La version 0.2.0 est disponible', update: 'Mettre à jour vers 0.2.0', floating: 'Mettre à jour Brevia', updating: 'Mise à jour…', current: 'À jour' }, model: { manage: 'Gérer la bibliothèque de modèles', download: 'Télécharger', downloading: 'Téléchargement…', installed: 'Installé', remove: 'Supprimer' }, summary: { title: 'Gérer les modèles de résumé', intro: 'Toute la configuration reste sur cet appareil et n’est jamais envoyée.', name: 'Nom de configuration', provider: 'Fournisseur', key: 'Clé API', endpoint: 'URL de requête', format: 'Format d’API', model: 'Modèle principal', save: 'Enregistrer la configuration', add: 'Nouvelle configuration', remove: 'Supprimer la configuration', configured: 'Modèles configurés', active: 'Utilisé', promptTitle: 'Invite de résumé', promptIntro: 'Cette invite sert à générer les notes de réunion IA.', jsonTitle: 'JSON de configuration', jsonIntro: 'Configuration du modèle de résumé actif.', ollama: 'Ollama local', openAIFormat: 'Format OpenAI', claudeFormat: 'Format Claude' }, modal: { models: { title: 'Bibliothèque de modèles', intro: 'Tous les modèles de transcription s’exécutent localement. Vos données ne sont jamais envoyées sur le réseau.', languages: 'Langues recommandées' }, terms: { title: 'Gérer le glossaire', intro: 'Les termes servent à préparer les réunions, rechercher et créer des notes. Seuls les modèles compatibles les utilisent.', add: 'Ajouter un terme', edit: 'Modifier', save: 'Enregistrer', cancel: 'Annuler', remove: 'Supprimer', placeholder: 'Saisir un terme ou une expression' }, storage: { title: 'Stockage local', intro: 'Toutes les données de réunion restent sur cet appareil.' }, close: 'Fermer', download: 'Télécharger' } },
  de: { theme: { light: 'Zum hellen Design wechseln', dark: 'Zum dunklen Design wechseln' }, update: { title: 'Softwareupdates', description: 'Aktuelle Version 0.1.0', action: 'Nach Updates suchen', checking: 'Suche läuft…', available: 'Version 0.2.0 ist verfügbar', update: 'Auf 0.2.0 aktualisieren', floating: 'Brevia aktualisieren', updating: 'Aktualisierung läuft…', current: 'Aktuell' }, model: { manage: 'Modellbibliothek verwalten', download: 'Herunterladen', downloading: 'Wird heruntergeladen…', installed: 'Installiert', remove: 'Löschen' }, summary: { title: 'Zusammenfassungsmodelle verwalten', intro: 'Alle Einstellungen bleiben auf diesem Gerät und werden nie hochgeladen.', name: 'Konfigurationsname', provider: 'Anbieter', key: 'API-Schlüssel', endpoint: 'Anfrage-URL', format: 'API-Format', model: 'Hauptmodell', save: 'Konfiguration speichern', add: 'Neue Konfiguration', remove: 'Konfiguration löschen', configured: 'Konfigurierte Modelle', active: 'In Verwendung', promptTitle: 'Zusammenfassungs-Prompt', promptIntro: 'Dieser Prompt wird für KI-Besprechungsnotizen verwendet.', jsonTitle: 'Konfigurations-JSON', jsonIntro: 'Aktive Konfiguration des Zusammenfassungsmodells.', ollama: 'Lokales Ollama', openAIFormat: 'OpenAI-Format', claudeFormat: 'Claude-Format' }, modal: { models: { title: 'Modellbibliothek', intro: 'Alle Transkriptionsmodelle laufen lokal. Ihre privaten Daten werden nie ins Netzwerk übertragen.', languages: 'Empfohlene Sprachen' }, terms: { title: 'Glossar verwalten', intro: 'Begriffe werden für Besprechungsvorbereitung, Suche und Notizen verwendet. Nur unterstützte Modelle verwenden sie bei der Transkription.', add: 'Begriff hinzufügen', edit: 'Bearbeiten', save: 'Speichern', cancel: 'Abbrechen', remove: 'Löschen', placeholder: 'Begriff oder Ausdruck eingeben' }, storage: { title: 'Lokaler Speicher', intro: 'Alle Besprechungsdaten bleiben auf diesem Gerät.' }, close: 'Schließen', download: 'Herunterladen' } },
  ru: { theme: { light: 'Светлая тема', dark: 'Тёмная тема' }, update: { title: 'Обновления ПО', description: 'Текущая версия 0.1.0', action: 'Проверить обновления', checking: 'Проверка…', available: 'Доступна версия 0.2.0', update: 'Обновить до 0.2.0', floating: 'Обновить Brevia', updating: 'Обновление…', current: 'Установлена последняя версия' }, model: { manage: 'Управление библиотекой моделей', download: 'Скачать', downloading: 'Скачивание…', installed: 'Установлено', remove: 'Удалить' }, summary: { title: 'Управление моделями сводки', intro: 'Все настройки хранятся только на этом устройстве и не загружаются.', name: 'Имя конфигурации', provider: 'Поставщик', key: 'Ключ API', endpoint: 'URL запроса', format: 'Формат API', model: 'Основная модель', save: 'Сохранить конфигурацию', add: 'Новая конфигурация', remove: 'Удалить конфигурацию', configured: 'Настроенные модели', active: 'Используется', promptTitle: 'Промпт сводки', promptIntro: 'Этот промпт используется для создания заметок встречи ИИ.', jsonTitle: 'JSON конфигурации', jsonIntro: 'Активная конфигурация модели сводки.', ollama: 'Локальный Ollama', openAIFormat: 'Формат OpenAI', claudeFormat: 'Формат Claude' }, modal: { models: { title: 'Библиотека моделей', intro: 'Все модели расшифровки работают локально. Ваши данные никогда не передаются в сеть.', languages: 'Рекомендуемые языки' }, terms: { title: 'Управление глоссарием', intro: 'Термины используются для подготовки встреч, поиска и заметок. При расшифровке их используют только поддерживаемые модели.', add: 'Добавить термин', edit: 'Изменить', save: 'Сохранить', cancel: 'Отмена', remove: 'Удалить', placeholder: 'Введите термин или фразу' }, storage: { title: 'Локальное хранилище', intro: 'Все данные встреч остаются на этом устройстве.' }, close: 'Закрыть', download: 'Скачать' } },
};
Object.entries(appCopyLocales).forEach(([code, copy]) => {
  appCopy.themeLabels[code] = copy.theme;
  appCopy.updateLabels[code] = copy.update;
  appCopy.modelLabels[code] = copy.model;
  appCopy.summaryModelCopy[code] = copy.summary;
  appCopy.modalCopy[code] = {
    ...appCopy.modalCopy.en,
    ...copy.modal,
    models: { ...appCopy.modalCopy.en.models, ...copy.modal.models, items: (copy.modal.models.items || appCopy.modalCopy.en.models.items).map((item) => [...item]) },
    terms: { ...appCopy.modalCopy.en.terms, ...copy.modal.terms },
    storage: { ...appCopy.modalCopy.en.storage, ...copy.modal.storage },
  };
});
appCopy.modalCopy.fr.models.items = [
  ['Sous-titres en direct', 'Streaming Paraformer', 'Chinois / anglais / cantonais', 'Reconnaissance vocale en continu qui actualise le sous-titre actif.', '⌁'],
  ['Sous-titres en direct', 'Streaming Zipformer English', 'Anglais', 'Reconnaissance vocale en continu native pour l’anglais.', 'Z'],
  ['Restauration de la ponctuation', 'English Punctuation and Casing', 'Anglais', 'Restaure la ponctuation et les majuscules en anglais.', '·'],
  ['Restauration de la ponctuation', 'Chinese and English Punctuation', 'Chinois / anglais / cantonais', 'Ajoute des virgules, des points et des points d’interrogation aux sous-titres.', '·'],
  ['Affinage après réunion', 'Qwen3-ASR', 'Multilingue', 'Crée une version révisée très précise à partir de l’enregistrement complet.', 'Q'],
  ['Séparation des locuteurs', 'Pyannote Segmentation 3.0', 'Indépendant de la langue', 'Détecte les segments de parole dans un enregistrement mono.', 'P'],
  ['Séparation des locuteurs', '3D-Speaker ERes2Net Base', 'Chinois', 'Extrait des empreintes vocales pour regrouper les locuteurs hors ligne.', '3D'],
  ['Sous-titres en direct', 'Streaming Zipformer Chinese XLarge', 'Chinois', 'Reconnaissance vocale chinoise en continu de plus haute précision.', 'Z'],
];
const storageItemLabels = {
  ja: ['会議と録音', 'モデルファイル', 'エクスポート'], ko: ['회의 및 녹음', '모델 파일', '내보내기'], fr: ['Réunions et enregistrements', 'Fichiers de modèles', 'Exportations'], de: ['Besprechungen und Aufnahmen', 'Modelldateien', 'Exporte'], ru: ['Встречи и записи', 'Файлы моделей', 'Экспорты'],
};
Object.entries(storageItemLabels).forEach(([code, labels]) => { appCopy.modalCopy[code].storage.items = labels.map((label, index) => [label, appCopy.modalCopy.en.storage.items[index][1]]); });
const highPrecisionModelIntro = {
  zh: '更大规模的会后精修模型，适合优先准确率的场景。', en: 'Larger post-meeting refinement model for accuracy-first work.', es: 'Modelo de refinamiento más grande para priorizar la precisión.',
  ja: '精度を優先するための大規模な会議後高精度化モデル。', ko: '정확도를 우선하는 대규모 회의 후 정제 모델입니다.', fr: 'Modèle d’affinage plus grand, conçu pour privilégier la précision.',
  de: 'Größeres Nachbearbeitungsmodell für Szenarien mit Genauigkeitspriorität.', ru: 'Более крупная модель обработки после встречи для максимальной точности.',
};
Object.entries(highPrecisionModelIntro).forEach(([code, intro]) => {
  const items = appCopy.modalCopy[code].models.items;
  const index = items.findIndex(([, name]) => name === 'Qwen3-ASR');
  items.splice(index + 1, 0, [items[index][0], 'Qwen3-ASR 1.7B int8', items[index][2], intro, 'Q']);
});
const newRefinementModelCopy = {
  zh: ['中文 / 英语 / 粤语', '高准确率中文会议精修。', '快速离线中英文精修。'],
  en: ['Chinese / English / Cantonese', 'High-accuracy Chinese meeting refinement.', 'Fast offline Chinese and English refinement.'],
  es: ['Chino / inglés / cantonés', 'Refinamiento de reuniones en chino de alta precisión.', 'Refinamiento rápido sin conexión para chino e inglés.'],
  ja: ['中国語 / 英語 / 広東語', '高精度な中国語会議の後処理。', '中国語と英語を高速にオフライン処理。'],
  ko: ['중국어 / 영어 / 광둥어', '정확도를 우선하는 중국어 회의 정제.', '중국어와 영어를 빠르게 오프라인 정제.'],
  fr: ['Chinois / anglais / cantonais', 'Affinage haute précision des réunions en chinois.', 'Affinage hors ligne rapide pour le chinois et l’anglais.'],
  de: ['Chinesisch / Englisch / Kantonesisch', 'Hochpräzise Nachbearbeitung chinesischer Besprechungen.', 'Schnelle Offline-Nachbearbeitung für Chinesisch und Englisch.'],
  ru: ['Китайский / английский / кантонский', 'Высокоточная обработка китайских встреч.', 'Быстрая автономная обработка китайского и английского.'],
};
Object.entries(appCopy.modalCopy).forEach(([code, copy]) => {
  const items = copy.models.items;
  const index = items.findIndex(([, name]) => name === 'Qwen3-ASR');
  const [languages, funasr, fireRed] = newRefinementModelCopy[code] || newRefinementModelCopy.en;
  items.splice(index, 0, [items[index][0], 'FunASR Nano int8', languages, funasr, 'F'], [items[index][0], 'FireRedASR2 CTC', languages, fireRed, 'R']);
});
const addedModelCopy = {
  zh: { vad: '语音活动检测', all: '所有语言', silero: '为分段式实时转写检测语音边界。', ten: '用于分段式实时转写的另一种语音边界检测器。', senseLanguages: '中文 / 英语 / 日语 / 韩语 / 粤语', sense: '支持基于 VAD 分段的实时字幕和离线精修。', whisperLanguages: '多语种', whisper: '为导入与录制的会议提供离线转写精修。', segmentation: '语音分段', embedding: '声纹嵌入', independent: '语言无关', pyannote: '检测单轨录音中的语音区间。', reverb: '用于说话人分离的轻量级语音分段模型。', nemoLanguages: '英语', nemo: '提取英文声纹嵌入，用于离线说话人聚类。', campLanguages: '中文 / 英语', camp: '提取中英文声纹嵌入，用于离线说话人聚类。' },
  en: { vad: 'Voice activity detection', all: 'All languages', silero: 'Detects speech boundaries for segmented live transcription.', ten: 'Alternative speech-boundary detector for segmented live transcription.', senseLanguages: 'Chinese / English / Japanese / Korean / Cantonese', sense: 'VAD-segmented live captions and offline refinement.', whisperLanguages: 'Multilingual', whisper: 'Offline transcription refinement for imported and recorded meetings.', segmentation: 'Speech segmentation', embedding: 'Speaker embeddings', independent: 'Language independent', pyannote: 'Detects speech regions in a single-track recording.', reverb: 'Lightweight speech-segmentation model for speaker diarization.', nemoLanguages: 'English', nemo: 'Extracts English speaker embeddings for offline clustering.', campLanguages: 'Chinese / English', camp: 'Extracts Chinese and English speaker embeddings for offline clustering.' },
  es: { vad: 'Detección de actividad de voz', all: 'Todos los idiomas', silero: 'Detecta límites de voz para la transcripción en vivo segmentada.', ten: 'Detector alternativo de límites de voz para la transcripción en vivo segmentada.', senseLanguages: 'Chino / inglés / japonés / coreano / cantonés', sense: 'Subtítulos en vivo segmentados por VAD y refinamiento sin conexión.', whisperLanguages: 'Multilingüe', whisper: 'Refinamiento de transcripción sin conexión para reuniones importadas y grabadas.', segmentation: 'Segmentación de voz', embedding: 'Huella de voz', independent: 'Independiente del idioma', pyannote: 'Detecta regiones de voz en una grabación de una sola pista.', reverb: 'Modelo ligero de segmentación de voz para separar hablantes.', nemoLanguages: 'Inglés', nemo: 'Extrae huellas de voz en inglés para agrupar hablantes sin conexión.', campLanguages: 'Chino / inglés', camp: 'Extrae huellas de voz en chino e inglés para agrupar hablantes sin conexión.' },
  ja: { vad: '音声活動検出', all: 'すべての言語', silero: '分割型ライブ文字起こしのために発話境界を検出します。', ten: '分割型ライブ文字起こし向けの代替発話境界検出器。', senseLanguages: '中国語 / 英語 / 日本語 / 韓国語 / 広東語', sense: 'VAD 分割のライブ字幕とオフライン高精度化に対応。', whisperLanguages: '多言語', whisper: 'インポートおよび録音済み会議のオフライン文字起こしを高精度化します。', segmentation: '音声区間分割', embedding: '話者埋め込み', independent: '言語非依存', pyannote: '単一トラック録音内の発話区間を検出します。', reverb: '話者分離のための軽量音声区間分割モデル。', nemoLanguages: '英語', nemo: 'オフライン話者クラスタリング用の英語話者埋め込みを抽出します。', campLanguages: '中国語 / 英語', camp: 'オフライン話者クラスタリング用の中英語話者埋め込みを抽出します。' },
  ko: { vad: '음성 활동 감지', all: '모든 언어', silero: '분할형 실시간 전사를 위한 음성 경계를 감지합니다.', ten: '분할형 실시간 전사를 위한 대체 음성 경계 감지기입니다.', senseLanguages: '중국어 / 영어 / 일본어 / 한국어 / 광둥어', sense: 'VAD 분할 실시간 자막 및 오프라인 정제를 지원합니다.', whisperLanguages: '다국어', whisper: '가져온 회의와 녹음 회의를 위한 오프라인 전사 정제입니다.', segmentation: '음성 구간 분할', embedding: '화자 임베딩', independent: '언어 독립', pyannote: '단일 트랙 녹음에서 음성 구간을 감지합니다.', reverb: '화자 분리를 위한 경량 음성 구간 분할 모델입니다.', nemoLanguages: '영어', nemo: '오프라인 화자 클러스터링용 영어 화자 임베딩을 추출합니다.', campLanguages: '중국어 / 영어', camp: '오프라인 화자 클러스터링용 중국어 및 영어 화자 임베딩을 추출합니다.' },
  fr: { vad: 'Détection d’activité vocale', all: 'Toutes les langues', silero: 'Détecte les limites de parole pour la transcription en direct segmentée.', ten: 'Détecteur alternatif de limites de parole pour la transcription en direct segmentée.', senseLanguages: 'Chinois / anglais / japonais / coréen / cantonais', sense: 'Sous-titres en direct segmentés par VAD et affinage hors ligne.', whisperLanguages: 'Multilingue', whisper: 'Affinage de transcription hors ligne pour les réunions importées et enregistrées.', segmentation: 'Segmentation de la parole', embedding: 'Empreintes vocales', independent: 'Indépendant de la langue', pyannote: 'Détecte les zones de parole dans un enregistrement mono.', reverb: 'Modèle léger de segmentation de la parole pour la séparation des locuteurs.', nemoLanguages: 'Anglais', nemo: 'Extrait des empreintes vocales anglaises pour le regroupement hors ligne.', campLanguages: 'Chinois / anglais', camp: 'Extrait des empreintes vocales chinoises et anglaises pour le regroupement hors ligne.' },
  de: { vad: 'Sprachaktivitätserkennung', all: 'Alle Sprachen', silero: 'Erkennt Sprachgrenzen für segmentierte Live-Transkription.', ten: 'Alternativer Sprachgrenzendetektor für segmentierte Live-Transkription.', senseLanguages: 'Chinesisch / Englisch / Japanisch / Koreanisch / Kantonesisch', sense: 'VAD-segmentierte Live-Untertitel und Offline-Nachbearbeitung.', whisperLanguages: 'Mehrsprachig', whisper: 'Offline-Nachbearbeitung für importierte und aufgezeichnete Besprechungen.', segmentation: 'Sprachsegmentierung', embedding: 'Sprecher-Embeddings', independent: 'Sprachunabhängig', pyannote: 'Erkennt Sprachbereiche in einer einkanaligen Aufnahme.', reverb: 'Leichtgewichtiges Sprachsegmentierungsmodell für Sprechertrennung.', nemoLanguages: 'Englisch', nemo: 'Extrahiert englische Sprecher-Embeddings für Offline-Clustering.', campLanguages: 'Chinesisch / Englisch', camp: 'Extrahiert chinesische und englische Sprecher-Embeddings für Offline-Clustering.' },
  ru: { vad: 'Обнаружение речи', all: 'Все языки', silero: 'Определяет границы речи для сегментированной потоковой транскрипции.', ten: 'Альтернативный детектор границ речи для сегментированной потоковой транскрипции.', senseLanguages: 'Китайский / английский / японский / корейский / кантонский', sense: 'Потоковые субтитры с сегментацией VAD и автономная обработка.', whisperLanguages: 'Многоязычный', whisper: 'Автономная обработка транскрипции импортированных и записанных встреч.', segmentation: 'Сегментация речи', embedding: 'Голосовые эмбеддинги', independent: 'Независимо от языка', pyannote: 'Определяет участки речи в однодорожечной записи.', reverb: 'Легковесная модель сегментации речи для разделения говорящих.', nemoLanguages: 'Английский', nemo: 'Извлекает английские голосовые эмбеддинги для автономной кластеризации.', campLanguages: 'Китайский / английский', camp: 'Извлекает китайские и английские голосовые эмбеддинги для автономной кластеризации.' },
};
Object.entries(appCopy.modalCopy).forEach(([code, copy]) => {
  const localized = addedModelCopy[code] || addedModelCopy.en;
  const items = copy.models.items;
  const punctuation = items.findIndex(([, name]) => name === 'English Punctuation and Casing');
  items.splice(punctuation, 0, [localized.vad, 'Silero VAD', localized.all, localized.silero, 'V'], [localized.vad, 'TEN-VAD', localized.all, localized.ten, 'V']);
  const refined = items.findIndex(([, name]) => name === 'Qwen3-ASR');
  items.splice(refined + 1, 0, [items[refined][0], 'Whisper Turbo', localized.whisperLanguages, localized.whisper, 'W']);
  const segmentation = items.findIndex(([, name]) => name === 'Pyannote Segmentation 3.0');
  items[segmentation].splice(0, 4, localized.segmentation, 'Pyannote Segmentation 3.0', localized.independent, localized.pyannote);
  items.splice(segmentation + 1, 0, [localized.segmentation, 'Reverb Diarization v1', localized.independent, localized.reverb, 'R']);
  const embedding = items.findIndex(([, name]) => name === '3D-Speaker ERes2Net Base');
  items[embedding].splice(0, 4, localized.embedding, '3D-Speaker ERes2Net Base', items[embedding][2] === 'Chinese' ? localized.campLanguages.split(' / ')[0] : items[embedding][2], items[embedding][3]);
  items.splice(embedding + 1, 0, [localized.embedding, 'NeMo Titanet Small', localized.nemoLanguages, localized.nemo, 'N'], [localized.embedding, '3D-Speaker CAM++', localized.campLanguages, localized.camp, 'C']);
});
const liveDenoiserCopy = {
  zh: ['实时降噪', '所有语言', '实时消除环境噪声后再进行字幕识别。'],
  en: ['Live denoising', 'All languages', 'Removes background noise before live transcription.'],
  es: ['Reducción de ruido en directo', 'Todos los idiomas', 'Elimina el ruido ambiental antes de la transcripción en directo.'],
  ja: ['リアルタイムノイズ除去', 'すべての言語', 'ライブ文字起こしの前に環境ノイズを除去します。'],
  ko: ['실시간 노이즈 제거', '모든 언어', '실시간 전사 전에 주변 소음을 제거합니다.'],
  fr: ['Réduction du bruit en direct', 'Toutes les langues', 'Supprime le bruit ambiant avant la transcription en direct.'],
  de: ['Live-Rauschunterdrückung', 'Alle Sprachen', 'Entfernt Umgebungsgeräusche vor der Live-Transkription.'],
  ru: ['Шумоподавление в реальном времени', 'Все языки', 'Убирает фоновый шум перед потоковой расшифровкой.'],
};
Object.entries(appCopy.modalCopy).forEach(([code, copy]) => {
  const [stage, languages, intro] = liveDenoiserCopy[code] || liveDenoiserCopy.en;
  copy.models.items.push([stage, 'GTCRN Live Denoiser', languages, intro, 'N']);
});
const voiceFeaturesCopy = {
  zh: { source: '声源分离', sourceIntro: '将会议录音拆分为人声与非人声轨。', tts: '语音合成与克隆', ttsIntro: '使用本地参考音频，以注册人员的声音合成中英文语音。', chat: '语音聊天', voice: '声音', reference: '参考文本', verify: '验证声音', send: '发送语音', placeholder: '输入要朗读的内容…', ready: '语音已生成', separated: '已生成人声和非人声轨' },
  en: { source: 'Source separation', sourceIntro: 'Splits meeting audio into vocal and non-vocal tracks.', tts: 'Speech synthesis and cloning', ttsIntro: 'Uses local reference audio to synthesize Chinese and English in a registered voice.', chat: 'Voice chat', voice: 'Voice', reference: 'Reference transcript', verify: 'Verify voice', send: 'Send voice', placeholder: 'Enter text to speak…', ready: 'Speech generated', separated: 'Vocal and non-vocal tracks generated' },
  es: { source: 'Separación de fuentes', sourceIntro: 'Separa el audio de la reunión en pistas vocales y no vocales.', tts: 'Síntesis y clonación de voz', ttsIntro: 'Usa audio local para sintetizar chino e inglés con una voz registrada.', chat: 'Chat de voz', voice: 'Voz', reference: 'Transcripción de referencia', verify: 'Verificar voz', send: 'Enviar voz', placeholder: 'Escribe el texto que se leerá…', ready: 'Voz generada', separated: 'Pistas vocales y no vocales generadas' },
  ja: { source: '音源分離', sourceIntro: '会議音声をボーカルと非ボーカルのトラックに分けます。', tts: '音声合成とクローン', ttsIntro: 'ローカル参照音声で登録済みの声による中英語音声を合成します。', chat: '音声チャット', voice: '音声', reference: '参照テキスト', verify: '音声を確認', send: '音声を送信', placeholder: '読み上げる内容を入力…', ready: '音声を生成しました', separated: 'ボーカルと非ボーカルのトラックを生成しました' },
  ko: { source: '음원 분리', sourceIntro: '회의 오디오를 음성과 비음성 트랙으로 분리합니다.', tts: '음성 합성 및 복제', ttsIntro: '로컬 참조 오디오로 등록된 목소리의 중국어·영어 음성을 합성합니다.', chat: '음성 채팅', voice: '음성', reference: '참조 스크립트', verify: '음성 확인', send: '음성 보내기', placeholder: '읽을 내용을 입력하세요…', ready: '음성이 생성되었습니다', separated: '음성 및 비음성 트랙이 생성되었습니다' },
  fr: { source: 'Séparation des sources', sourceIntro: 'Sépare l’audio de réunion en pistes vocale et non vocale.', tts: 'Synthèse et clonage vocal', ttsIntro: 'Utilise un audio local pour synthétiser du chinois et de l’anglais avec une voix enregistrée.', chat: 'Chat vocal', voice: 'Voix', reference: 'Transcription de référence', verify: 'Vérifier la voix', send: 'Envoyer la voix', placeholder: 'Saisissez le texte à lire…', ready: 'Voix générée', separated: 'Pistes vocale et non vocale générées' },
  de: { source: 'Quellentrennung', sourceIntro: 'Trennt Besprechungsaudio in Sprach- und Nichtsprachspuren.', tts: 'Sprachsynthese und Klonen', ttsIntro: 'Erzeugt Chinesisch und Englisch mit einer lokalen registrierten Stimme.', chat: 'Sprachchat', voice: 'Stimme', reference: 'Referenztranskript', verify: 'Stimme prüfen', send: 'Sprache senden', placeholder: 'Text zum Vorlesen eingeben…', ready: 'Sprache erzeugt', separated: 'Sprach- und Nichtsprachspuren erzeugt' },
  ru: { source: 'Разделение источников', sourceIntro: 'Разделяет аудио встречи на голосовую и неголосовую дорожки.', tts: 'Синтез и клонирование голоса', ttsIntro: 'Использует локальный образец для синтеза китайской и английской речи зарегистрированным голосом.', chat: 'Голосовой чат', voice: 'Голос', reference: 'Текст образца', verify: 'Проверить голос', send: 'Отправить голос', placeholder: 'Введите текст для озвучивания…', ready: 'Речь создана', separated: 'Голосовая и неголосовая дорожки созданы' },
};
appCopy.voiceFeaturesCopy = voiceFeaturesCopy;
Object.entries(appCopy.modalCopy).forEach(([code, copy]) => {
  const localized = voiceFeaturesCopy[code] || voiceFeaturesCopy.en;
  copy.models.items.push([localized.source, 'Spleeter 2 Stems', localized.source === 'Source separation' ? 'All languages' : '所有语言', localized.sourceIntro, 'S'], [localized.tts, 'ZipVoice Chinese and English', localized.source === 'Source separation' ? 'Chinese / English' : '中文 / 英语', localized.ttsIntro, 'Z']);
});
const additionalStreamingModels = {
  zh: [['Streaming Zipformer Chinese', '中文', '轻量级中文实时识别。'], ['Streaming Zipformer Chinese and English', '中文 / 英语', '支持中英文混说的实时识别。'], ['Streaming Zipformer Multilingual', '阿拉伯语 / 英语 / 印尼语 / 日语 / 俄语 / 泰语 / 越南语 / 中文', '支持八种语言的实时识别。'], ['Streaming Zipformer Korean', '韩语', '原生韩语实时识别。'], ['Streaming Zipformer French', '法语', '原生法语实时识别。']],
  en: [['Streaming Zipformer Chinese', 'Chinese', 'Compact Chinese live transcription model.'], ['Streaming Zipformer Chinese and English', 'Chinese / English', 'Live transcription for mixed Chinese and English.'], ['Streaming Zipformer Multilingual', 'Arabic / English / Indonesian / Japanese / Russian / Thai / Vietnamese / Chinese', 'Live transcription for eight languages.'], ['Streaming Zipformer Korean', 'Korean', 'Native Korean live transcription.'], ['Streaming Zipformer French', 'French', 'Native French live transcription.']],
  es: [['Streaming Zipformer Chinese', 'Chino', 'Transcripción en vivo compacta para chino.'], ['Streaming Zipformer Chinese and English', 'Chino / inglés', 'Transcripción en vivo para chino e inglés mezclados.'], ['Streaming Zipformer Multilingual', 'Árabe / inglés / indonesio / japonés / ruso / tailandés / vietnamita / chino', 'Transcripción en vivo para ocho idiomas.'], ['Streaming Zipformer Korean', 'Coreano', 'Transcripción en vivo nativa para coreano.'], ['Streaming Zipformer French', 'Francés', 'Transcripción en vivo nativa para francés.']],
  ja: [['Streaming Zipformer Chinese', '中国語', '軽量な中国語ライブ文字起こしモデル。'], ['Streaming Zipformer Chinese and English', '中国語 / 英語', '中国語と英語が混在する音声をライブ文字起こしします。'], ['Streaming Zipformer Multilingual', 'アラビア語 / 英語 / インドネシア語 / 日本語 / ロシア語 / タイ語 / ベトナム語 / 中国語', '8 言語対応のライブ文字起こし。'], ['Streaming Zipformer Korean', '韓国語', '韓国語のライブ文字起こし。'], ['Streaming Zipformer French', 'フランス語', 'フランス語のライブ文字起こし。']],
  ko: [['Streaming Zipformer Chinese', '중국어', '경량 중국어 실시간 전사 모델입니다.'], ['Streaming Zipformer Chinese and English', '중국어 / 영어', '중국어와 영어 혼용 음성을 실시간 전사합니다.'], ['Streaming Zipformer Multilingual', '아랍어 / 영어 / 인도네시아어 / 일본어 / 러시아어 / 태국어 / 베트남어 / 중국어', '8개 언어 실시간 전사 모델입니다.'], ['Streaming Zipformer Korean', '한국어', '한국어 실시간 전사 모델입니다.'], ['Streaming Zipformer French', '프랑스어', '프랑스어 실시간 전사 모델입니다.']],
  fr: [['Streaming Zipformer Chinese', 'Chinois', 'Modèle compact de transcription en direct pour le chinois.'], ['Streaming Zipformer Chinese and English', 'Chinois / anglais', 'Transcription en direct pour le chinois et l’anglais mélangés.'], ['Streaming Zipformer Multilingual', 'Arabe / anglais / indonésien / japonais / russe / thaï / vietnamien / chinois', 'Transcription en direct pour huit langues.'], ['Streaming Zipformer Korean', 'Coréen', 'Transcription en direct native pour le coréen.'], ['Streaming Zipformer French', 'Français', 'Transcription en direct native pour le français.']],
  de: [['Streaming Zipformer Chinese', 'Chinesisch', 'Kompaktes Live-Transkriptionsmodell für Chinesisch.'], ['Streaming Zipformer Chinese and English', 'Chinesisch / Englisch', 'Live-Transkription für gemischtes Chinesisch und Englisch.'], ['Streaming Zipformer Multilingual', 'Arabisch / Englisch / Indonesisch / Japanisch / Russisch / Thailändisch / Vietnamesisch / Chinesisch', 'Live-Transkription für acht Sprachen.'], ['Streaming Zipformer Korean', 'Koreanisch', 'Native Live-Transkription für Koreanisch.'], ['Streaming Zipformer French', 'Französisch', 'Native Live-Transkription für Französisch.']],
  ru: [['Streaming Zipformer Chinese', 'Китайский', 'Компактная потоковая транскрипция китайской речи.'], ['Streaming Zipformer Chinese and English', 'Китайский / английский', 'Потоковая транскрипция смешанной китайской и английской речи.'], ['Streaming Zipformer Multilingual', 'Арабский / английский / индонезийский / японский / русский / тайский / вьетнамский / китайский', 'Потоковая транскрипция для восьми языков.'], ['Streaming Zipformer Korean', 'Корейский', 'Нативная потоковая транскрипция корейской речи.'], ['Streaming Zipformer French', 'Французский', 'Нативная потоковая транскрипция французской речи.']],
};
Object.entries(appCopy.modalCopy).forEach(([code, copy]) => {
  const items = copy.models.items;
  const index = items.findIndex(([stage]) => stage !== items[0][0]);
  items.splice(index < 0 ? items.length : index, 0, ...(additionalStreamingModels[code] || additionalStreamingModels.en).filter(([name]) => name !== 'Streaming Zipformer Chinese and English').map(([name, detail, intro]) => [items[0][0], name, detail, intro, 'Z']));
});
const prepareModelLabels = {
  zh: { '实时字幕模型': '实时字幕模型', '说话人分离模型': '说话人分离模型', '会后精修模型': '会后精修模型' },
  en: { '实时字幕模型': 'Live caption model', '说话人分离模型': 'Speaker diarization model', '会后精修模型': 'Post-meeting refinement model' },
  es: { '实时字幕模型': 'Modelo de subtítulos en vivo', '说话人分离模型': 'Modelo de separación de hablantes', '会后精修模型': 'Modelo de refinamiento posterior' },
  ja: { '实时字幕模型': 'ライブ字幕モデル', '说话人分离模型': '話者分離モデル', '会后精修模型': '会議後の高精度化モデル' },
  ko: { '实时字幕模型': '실시간 자막 모델', '说话人分离模型': '화자 분리 모델', '会后精修模型': '회의 후 정제 모델' },
  fr: { '实时字幕模型': 'Modèle de sous-titres en direct', '说话人分离模型': 'Modèle de séparation des locuteurs', '会后精修模型': 'Modèle d’affinage après réunion' },
  de: { '实时字幕模型': 'Live-Untertitelmodell', '说话人分离模型': 'Sprechertrennungsmodell', '会后精修模型': 'Nachbearbeitungsmodell' },
  ru: { '实时字幕模型': 'Модель субтитров в реальном времени', '说话人分离模型': 'Модель разделения говорящих', '会后精修模型': 'Модель обработки после встречи' },
};
Object.entries(prepareModelLabels).forEach(([code, labels]) => Object.assign(catalog[code].labels, labels));
Object.entries({
  zh: '管理模型 →', en: 'Manage models →', es: 'Gestionar modelos →', ja: 'モデルを管理 →',
  ko: '모델 관리 →', fr: 'Gérer les modèles →', de: 'Modelle verwalten →', ru: 'Управление моделями →',
}).forEach(([code, label]) => { catalog[code].labels['管理模型与术语 →'] = label; });
Object.entries({
  zh: { '从文件夹打开': '从文件夹打开', '未找到录音文件': '未找到录音文件', '未找到模型文件': '未找到模型文件', '准备中': '准备中', '需要下载以下模型': '需要下载以下模型：', '前往模型库': '前往模型库', '精修': '精修' },
  en: { '从文件夹打开': 'Open in folder', '未找到录音文件': 'Recording file not found', '未找到模型文件': 'Model files not found', '准备中': 'Preparing', '需要下载以下模型': 'Download required models:', '前往模型库': 'Go to model library', '精修': 'Refine' },
  es: { '从文件夹打开': 'Abrir en la carpeta', '未找到录音文件': 'No se encontró el archivo de grabación', '未找到模型文件': 'No se encontraron archivos del modelo', '准备中': 'Preparando', '需要下载以下模型': 'Descarga los modelos necesarios:', '前往模型库': 'Ir a la biblioteca de modelos', '精修': 'Refinar' },
  ja: { '从文件夹打开': 'フォルダで開く', '未找到录音文件': '録音ファイルが見つかりません', '未找到模型文件': 'モデルファイルが見つかりません', '准备中': '準備中', '需要下载以下模型': '次のモデルをダウンロードしてください：', '前往模型库': 'モデルライブラリへ', '精修': '再調整' },
  ko: { '从文件夹打开': '폴더에서 열기', '未找到录音文件': '녹음 파일을 찾을 수 없습니다', '未找到模型文件': '모델 파일을 찾을 수 없습니다', '准备中': '준비 중', '需要下载以下模型': '필요한 모델을 다운로드하세요:', '前往模型库': '모델 라이브러리로', '精修': '정교화' },
  fr: { '从文件夹打开': 'Ouvrir dans le dossier', '未找到录音文件': 'Fichier d’enregistrement introuvable', '未找到模型文件': 'Fichiers du modèle introuvables', '准备中': 'Préparation', '需要下载以下模型': 'Téléchargez les modèles requis :', '前往模型库': 'Aller à la bibliothèque de modèles', '精修': 'Affiner' },
  de: { '从文件夹打开': 'Im Ordner öffnen', '未找到录音文件': 'Aufnahmedatei nicht gefunden', '未找到模型文件': 'Modelldateien nicht gefunden', '准备中': 'Wird vorbereitet', '需要下载以下模型': 'Erforderliche Modelle herunterladen:', '前往模型库': 'Zur Modellbibliothek', '精修': 'Verfeinern' },
  ru: { '从文件夹打开': 'Открыть в папке', '未找到录音文件': 'Файл записи не найден', '未找到模型文件': 'Файлы модели не найдены', '准备中': 'Подготовка', '需要下载以下模型': 'Скачайте необходимые модели:', '前往模型库': 'К библиотеке моделей', '精修': 'Уточнить' },
}).forEach(([code, labels]) => Object.assign(catalog[code].labels, labels));
Object.entries({
  zh: '调整识别、端点检测、说话人分离和本地模型运行参数。',
  en: 'Adjust recognition, endpoint detection, speaker diarization, and local model runtime parameters.',
  es: 'Ajusta el reconocimiento, la detección de final, la separación de hablantes y los parámetros locales de los modelos.',
  ja: '認識、終端検出、話者分離、ローカルモデルの実行パラメーターを調整します。',
  ko: '인식, 종점 감지, 화자 분리 및 로컬 모델 실행 매개변수를 조정합니다.',
  fr: 'Ajustez la reconnaissance, la détection de fin, la séparation des locuteurs et les paramètres locaux des modèles.',
  de: 'Passen Sie Erkennung, Endpunkterkennung, Sprechertrennung und lokale Modelllaufzeitparameter an.',
  ru: 'Настройте распознавание, определение конца фразы, разделение говорящих и параметры локальных моделей.',
}).forEach(([code, value]) => { catalog[code].labels['调整识别、端点检测、说话人分离和本地模型运行参数。'] = value; });
const workflowLabels = {
  '双轨录音': 'Dual-track audio', '人声轨': 'Vocal track', '非人声轨': 'Non-vocal track',
  '正在分离人声与非人声': 'Separating vocal and non-vocal tracks', '声源分离已完成': 'Source separation complete',
  '完成声源分离后，人声与非人声录音会显示在这里。': 'Vocal and non-vocal recordings appear here after source separation.',
  '开始声源分离': 'Start source separation', '声源分离结果': 'Source-separation result', '请先完成声源分离': 'Run source separation first',
  '下载': 'Download', '下载中': 'Downloading', '全部下载': 'Download all',
  '导出会议': 'Export meeting', '导出完成': 'Export complete', '字幕文件': 'Subtitle file',
  '原录音': 'Original recording', '带说话人和时间戳的逐字稿': 'Transcript with speakers and timestamps',
  '标准时间轴字幕': 'Standard timed subtitles', '未修改的会议混音': 'Unmodified meeting mix',
  '内置': 'Built in', '查看录音': 'View recordings', '收起': 'Collapse',
  '选择录音并添加': 'Choose recording and add', '播放录音': 'Play recording', '未填写文本': 'No transcript',
};
Object.assign(catalog.en.labels, workflowLabels);
Object.assign(catalog.zh.labels, Object.fromEntries(Object.keys(workflowLabels).map((key) => [key, key])));
Object.entries({
  es: { '双轨录音':'Audio de doble pista','人声轨':'Pista vocal','非人声轨':'Pista no vocal','正在分离人声与非人声':'Separando pistas vocal y no vocal','声源分离已完成':'Separación de fuentes completada','完成声源分离后，人声与非人声录音会显示在这里。':'Las grabaciones vocales y no vocales aparecerán aquí al terminar.','开始声源分离':'Iniciar separación de fuentes','声源分离结果':'Resultado de separación de fuentes','请先完成声源分离':'Primero completa la separación de fuentes','下载':'Descargar','下载中':'Descargando','全部下载':'Descargar todo','导出会议':'Exportar reunión','导出完成':'Exportación completada','字幕文件':'Archivo de subtítulos','原录音':'Grabación original','带说话人和时间戳的逐字稿':'Transcripción con hablantes y marcas de tiempo','标准时间轴字幕':'Subtítulos cronometrados estándar','未修改的会议混音':'Mezcla de reunión sin modificar','内置':'Integrado','查看录音':'Ver grabaciones','收起':'Contraer','选择录音并添加':'Elegir grabación y añadir','播放录音':'Reproducir grabación','未填写文本':'Sin transcripción' },
  ja: { '双轨录音':'デュアルトラック音声','人声轨':'音声トラック','非人声轨':'非音声トラック','正在分离人声与非人声':'音声と非音声を分離しています','声源分离已完成':'音源分離が完了しました','完成声源分离后，人声与非人声录音会显示在这里。':'分離完了後、音声と非音声の録音がここに表示されます。','开始声源分离':'音源分離を開始','声源分离结果':'音源分離の結果','请先完成声源分离':'先に音源分離を完了してください','下载':'ダウンロード','下载中':'ダウンロード中','全部下载':'すべてダウンロード','导出会议':'会議をエクスポート','导出完成':'エクスポート完了','字幕文件':'字幕ファイル','原录音':'元の録音','带说话人和时间戳的逐字稿':'話者と時刻付き文字起こし','标准时间轴字幕':'標準タイムコード字幕','未修改的会议混音':'未変更の会議ミックス','内置':'内蔵','查看录音':'録音を表示','收起':'折りたたむ','选择录音并添加':'録音を選択して追加','播放录音':'録音を再生','未填写文本':'文字起こしなし' },
  ko: { '双轨录音':'이중 트랙 오디오','人声轨':'음성 트랙','非人声轨':'비음성 트랙','正在分离人声与非人声':'음성 및 비음성 트랙을 분리하는 중','声源分离已完成':'음원 분리 완료','完成声源分离后，人声与非人声录音会显示在这里。':'분리 완료 후 음성 및 비음성 녹음이 여기에 표시됩니다.','开始声源分离':'음원 분리 시작','声源分离结果':'음원 분리 결과','请先完成声源分离':'먼저 음원 분리를 완료하세요','下载':'다운로드','下载中':'다운로드 중','全部下载':'모두 다운로드','导出会议':'회의 내보내기','导出完成':'내보내기 완료','字幕文件':'자막 파일','原录音':'원본 녹음','带说话人和时间戳的逐字稿':'화자 및 시간 정보가 있는 녹취','标准时间轴字幕':'표준 시간 자막','未修改的会议混音':'수정하지 않은 회의 믹스','内置':'내장','查看录音':'녹음 보기','收起':'접기','选择录音并添加':'녹음 선택 및 추가','播放录音':'녹음 재생','未填写文本':'녹취 없음' },
  fr: { '双轨录音':'Audio à deux pistes','人声轨':'Piste vocale','非人声轨':'Piste non vocale','正在分离人声与非人声':'Séparation des pistes vocale et non vocale','声源分离已完成':'Séparation des sources terminée','完成声源分离后，人声与非人声录音会显示在这里。':'Les enregistrements vocaux et non vocaux apparaîtront ici après la séparation.','开始声源分离':'Démarrer la séparation des sources','声源分离结果':'Résultat de la séparation des sources','请先完成声源分离':'Terminez d’abord la séparation des sources','下载':'Télécharger','下载中':'Téléchargement','全部下载':'Tout télécharger','导出会议':'Exporter la réunion','导出完成':'Exportation terminée','字幕文件':'Fichier de sous-titres','原录音':'Enregistrement original','带说话人和时间戳的逐字稿':'Transcription avec locuteurs et horodatage','标准时间轴字幕':'Sous-titres temporels standard','未修改的会议混音':'Mixage de réunion non modifié','内置':'Intégré','查看录音':'Voir les enregistrements','收起':'Réduire','选择录音并添加':'Choisir un enregistrement et ajouter','播放录音':'Lire l’enregistrement','未填写文本':'Aucune transcription' },
  de: { '双轨录音':'Zweispur-Audio','人声轨':'Stimmspur','非人声轨':'Nicht-Stimmspur','正在分离人声与非人声':'Stimm- und Nicht-Stimmspur werden getrennt','声源分离已完成':'Quellentrennung abgeschlossen','完成声源分离后，人声与非人声录音会显示在这里。':'Nach der Trennung erscheinen Stimm- und Nicht-Stimmaufnahmen hier.','开始声源分离':'Quellentrennung starten','声源分离结果':'Ergebnis der Quellentrennung','请先完成声源分离':'Schließen Sie zuerst die Quellentrennung ab','下载':'Herunterladen','下载中':'Wird heruntergeladen','全部下载':'Alle herunterladen','导出会议':'Besprechung exportieren','导出完成':'Export abgeschlossen','字幕文件':'Untertiteldatei','原录音':'Originalaufnahme','带说话人和时间戳的逐字稿':'Transkript mit Sprechern und Zeitstempeln','标准时间轴字幕':'Standard-Timeline-Untertitel','未修改的会议混音':'Unveränderter Besprechungsmix','内置':'Integriert','查看录音':'Aufnahmen anzeigen','收起':'Einklappen','选择录音并添加':'Aufnahme auswählen und hinzufügen','播放录音':'Aufnahme abspielen','未填写文本':'Kein Transkript' },
  ru: { '双轨录音':'Двухдорожечное аудио','人声轨':'Голосовая дорожка','非人声轨':'Неголосовая дорожка','正在分离人声与非人声':'Разделяются голосовая и неголосовая дорожки','声源分离已完成':'Разделение источников завершено','完成声源分离后，人声与非人声录音会显示在这里。':'После разделения здесь появятся голосовая и неголосовая записи.','开始声源分离':'Начать разделение источников','声源分离结果':'Результат разделения источников','请先完成声源分离':'Сначала завершите разделение источников','下载':'Скачать','下载中':'Скачивание','全部下载':'Скачать всё','导出会议':'Экспортировать встречу','导出完成':'Экспорт завершён','字幕文件':'Файл субтитров','原录音':'Исходная запись','带说话人和时间戳的逐字稿':'Расшифровка с говорящими и метками времени','标准时间轴字幕':'Стандартные субтитры по времени','未修改的会议混音':'Неизменённый микс встречи','内置':'Встроено','查看录音':'Просмотреть записи','收起':'Свернуть','选择录音并添加':'Выбрать и добавить запись','播放录音':'Воспроизвести запись','未填写文本':'Нет расшифровки' },
}).forEach(([code, labels]) => Object.assign(catalog[code].labels, labels));
Object.entries({
  zh: { '进阶设置':'进阶设置','配置进阶设置':'配置进阶设置','恢复默认':'恢复默认','确定':'确定','已保存':'已保存','标记说话人':'标记说话人','选择已注册声纹或新建说话人。':'选择已注册声纹或新建说话人。','已注册声纹':'已注册声纹','新建说话人':'新建说话人','说话人名称':'说话人名称','可修改模型、端点静音、说话人分离及 sherpa-onnx 运行参数。':'可修改模型、端点静音、说话人分离及 sherpa-onnx 运行参数。','修改后会立即应用于下一次会议与精修。':'修改后会立即应用于下一次会议与精修。' },
  en: { '进阶设置':'Advanced settings','配置进阶设置':'Configure advanced settings','恢复默认':'Restore defaults','确定':'Confirm','已保存':'Saved','标记说话人':'Assign speaker','选择已注册声纹或新建说话人。':'Choose a registered voiceprint or create a speaker.','已注册声纹':'Registered voiceprint','新建说话人':'New speaker','说话人名称':'Speaker name','可修改模型、端点静音、说话人分离及 sherpa-onnx 运行参数。':'Configure model, endpoint, diarization, and sherpa-onnx runtime parameters.','修改后会立即应用于下一次会议与精修。':'Changes apply to the next meeting and refinement.' }
  , es: { '进阶设置':'Configuración avanzada','配置进阶设置':'Configurar opciones avanzadas','恢复默认':'Restaurar valores predeterminados','确定':'Confirmar','已保存':'Guardado','标记说话人':'Asignar hablante','选择已注册声纹或新建说话人。':'Elige una huella de voz registrada o crea un hablante.','已注册声纹':'Huella de voz registrada','新建说话人':'Nuevo hablante','说话人名称':'Nombre del hablante','可修改模型、端点静音、说话人分离及 sherpa-onnx 运行参数。':'Configura modelos, detección de final, separación de hablantes y parámetros de sherpa-onnx.','修改后会立即应用于下一次会议与精修。':'Los cambios se aplican a la próxima reunión y refinamiento.' }
  , ja: { '进阶设置':'詳細設定','配置进阶设置':'詳細設定を構成','恢复默认':'既定値に戻す','确定':'確認','已保存':'保存しました','标记说话人':'話者を割り当て','选择已注册声纹或新建说话人。':'登録済みの声紋を選択するか、話者を新規作成します。','已注册声纹':'登録済みの声紋','新建说话人':'新しい話者','说话人名称':'話者名','可修改模型、端点静音、说话人分离及 sherpa-onnx 运行参数。':'モデル、終端の無音、話者分離、sherpa-onnx の実行パラメーターを設定します。','修改后会立即应用于下一次会议与精修。':'変更は次回の会議と高精度化に適用されます。' }
  , ko: { '进阶设置':'고급 설정','配置进阶设置':'고급 설정 구성','恢复默认':'기본값 복원','确定':'확인','已保存':'저장됨','标记说话人':'화자 지정','选择已注册声纹或新建说话人。':'등록된 음성 지문을 선택하거나 화자를 새로 만드세요.','已注册声纹':'등록된 음성 지문','新建说话人':'새 화자','说话人名称':'화자 이름','可修改模型、端点静音、说话人分离及 sherpa-onnx 运行参数。':'모델, 종점 무음, 화자 분리 및 sherpa-onnx 실행 매개변수를 구성합니다.','修改后会立即应用于下一次会议与精修。':'변경 사항은 다음 회의와 정교화에 적용됩니다.' }
  , fr: { '进阶设置':'Paramètres avancés','配置进阶设置':'Configurer les paramètres avancés','恢复默认':'Rétablir les valeurs par défaut','确定':'Confirmer','已保存':'Enregistré','标记说话人':'Attribuer un locuteur','选择已注册声纹或新建说话人。':'Choisissez une empreinte vocale enregistrée ou créez un locuteur.','已注册声纹':'Empreinte vocale enregistrée','新建说话人':'Nouveau locuteur','说话人名称':'Nom du locuteur','可修改模型、端点静音、说话人分离及 sherpa-onnx 运行参数。':'Configurez les modèles, le silence de fin, la séparation des locuteurs et les paramètres sherpa-onnx.','修改后会立即应用于下一次会议与精修。':'Les modifications s’appliquent à la prochaine réunion et à l’affinage.' }
  , de: { '进阶设置':'Erweiterte Einstellungen','配置进阶设置':'Erweiterte Einstellungen konfigurieren','恢复默认':'Standardwerte wiederherstellen','确定':'Bestätigen','已保存':'Gespeichert','标记说话人':'Sprecher zuordnen','选择已注册声纹或新建说话人。':'Wählen Sie einen registrierten Stimmabdruck oder erstellen Sie einen Sprecher.','已注册声纹':'Registrierter Stimmabdruck','新建说话人':'Neuer Sprecher','说话人名称':'Sprechername','可修改模型、端点静音、说话人分离及 sherpa-onnx 运行参数。':'Konfigurieren Sie Modelle, Endpunktstille, Sprechertrennung und sherpa-onnx-Laufzeitparameter.','修改后会立即应用于下一次会议与精修。':'Änderungen gelten für die nächste Besprechung und Nachbearbeitung.' }
  , ru: { '进阶设置':'Расширенные настройки','配置进阶设置':'Настроить расширенные параметры','恢复默认':'Восстановить значения по умолчанию','确定':'Подтвердить','已保存':'Сохранено','标记说话人':'Назначить говорящего','选择已注册声纹或新建说话人。':'Выберите зарегистрированный голосовой отпечаток или создайте говорящего.','已注册声纹':'Зарегистрированный голосовой отпечаток','新建说话人':'Новый говорящий','说话人名称':'Имя говорящего','可修改模型、端点静音、说话人分离及 sherpa-onnx 运行参数。':'Настройте модели, тишину конца фразы, разделение говорящих и параметры sherpa-onnx.','修改后会立即应用于下一次会议与精修。':'Изменения применяются к следующей встрече и обработке.' }
}).forEach(([code, labels]) => Object.assign(catalog[code].labels, labels));

Object.entries({
  zh: { '添加录音到声纹库':'添加录音到声纹库', '暂无已注册声纹':'暂无已注册声纹', '已添加录音到声纹库':'已添加录音到声纹库', '新增声纹':'新增声纹', '声纹名称':'声纹名称', '已创建声纹并添加录音':'已创建声纹并添加录音' },
  en: { '添加录音到声纹库':'Add recording to voiceprint', '暂无已注册声纹':'No registered voiceprints', '已添加录音到声纹库':'Recording added to voiceprint', '新增声纹':'Create voiceprint', '声纹名称':'Voiceprint name', '已创建声纹并添加录音':'Voiceprint created and recording added' },
  es: { '添加录音到声纹库':'Añadir grabación a la huella de voz', '暂无已注册声纹':'No hay huellas de voz registradas', '已添加录音到声纹库':'Grabación añadida a la huella de voz', '新增声纹':'Crear huella de voz', '声纹名称':'Nombre de huella de voz', '已创建声纹并添加录音':'Huella de voz creada y grabación añadida' },
  ja: { '添加录音到声纹库':'録音を声紋に追加', '暂无已注册声纹':'登録済みの声紋はありません', '已添加录音到声纹库':'録音を声紋に追加しました', '新增声纹':'声紋を作成', '声纹名称':'声紋名', '已创建声纹并添加录音':'声紋を作成し録音を追加しました' },
  ko: { '添加录音到声纹库':'음성 지문에 녹음 추가', '暂无已注册声纹':'등록된 음성 지문이 없습니다', '已添加录音到声纹库':'녹음이 음성 지문에 추가되었습니다', '新增声纹':'음성 지문 만들기', '声纹名称':'음성 지문 이름', '已创建声纹并添加录音':'음성 지문을 만들고 녹음을 추가했습니다' },
  fr: { '添加录音到声纹库':'Ajouter l’enregistrement à l’empreinte vocale', '暂无已注册声纹':'Aucune empreinte vocale enregistrée', '已添加录音到声纹库':'Enregistrement ajouté à l’empreinte vocale', '新增声纹':'Créer une empreinte vocale', '声纹名称':'Nom de l’empreinte vocale', '已创建声纹并添加录音':'Empreinte vocale créée et enregistrement ajouté' },
  de: { '添加录音到声纹库':'Aufnahme zum Stimmabdruck hinzufügen', '暂无已注册声纹':'Keine registrierten Stimmabdrücke', '已添加录音到声纹库':'Aufnahme zum Stimmabdruck hinzugefügt', '新增声纹':'Stimmabdruck erstellen', '声纹名称':'Name des Stimmabdrucks', '已创建声纹并添加录音':'Stimmabdruck erstellt und Aufnahme hinzugefügt' },
  ru: { '添加录音到声纹库':'Добавить запись в голосовой отпечаток', '暂无已注册声纹':'Нет зарегистрированных голосовых отпечатков', '已添加录音到声纹库':'Запись добавлена в голосовой отпечаток', '新增声纹':'Создать голосовой отпечаток', '声纹名称':'Имя голосового отпечатка', '已创建声纹并添加录音':'Голосовой отпечаток создан, запись добавлена' },
}).forEach(([code, labels]) => Object.assign(catalog[code].labels, labels));

window.BreviaLocaleData = { catalog, appCopy };
})();
