import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { runInNewContext } from 'node:vm';

const [html, css, app, meetings, meetingDetail, uiData, components, i18n, i18nData] = await Promise.all(['index.html', 'styles.css', 'app.js', 'app-meetings.js', 'app-meeting-detail.js', 'ui-data.js', 'ui-components.js', 'i18n.js', 'i18n-data.js'].map((file) => readFile(file)));
const js = Buffer.concat([app, meetings, meetingDetail]);
const [backendClient, logo] = await Promise.all(['backend-client.js', 'assets/brevia-logo.svg'].map((file) => readFile(file)));
const electronMain = await readFile('../electron/main.js');
const asr = await readFile('../backend/asr.py');
const text = (value) => value.toString();
const componentContext = {};
runInNewContext(text(components), componentContext);
const localeContext = { window: {} };
runInNewContext(text(i18nData), localeContext);
const advancedDescription = '调整识别、端点检测、说话人分离和本地模型运行参数。';
for (const code of ['en', 'es', 'ja', 'ko', 'fr', 'de', 'ru']) assert.notEqual(localeContext.window.BreviaLocaleData.catalog[code].labels[advancedDescription], advancedDescription);
for (const code of ['en', 'es', 'ja', 'ko', 'fr', 'de', 'ru']) assert.notEqual(localeContext.window.BreviaLocaleData.catalog[code].labels['添加录音到声纹库'], '添加录音到声纹库');
assert.equal(componentContext.rectanglesIntersect({ left: 0, right: 10, top: 0, bottom: 10 }, { left: 8, right: 12, top: 8, bottom: 12 }), true);
assert.equal(componentContext.rectanglesIntersect({ left: 0, right: 2, top: 0, bottom: 2 }, { left: 3, right: 5, top: 3, bottom: 5 }), false);

for (const id of ['home-view', 'prepare-view', 'live-view', 'detail-view', 'settings-view', 'meeting-form', 'end-meeting']) {
  assert.match(text(html), new RegExp(`id="${id}"`));
}
assert.match(text(css), /prefers-reduced-motion:\s*reduce/);
assert.match(text(css), /\.window-bar\{[^}]*-webkit-app-region:drag/);
assert.match(text(css), /\.window-bar\{[^}]*position:sticky/);
assert.match(text(css), /\.library-toolbar \.search input,.library-toolbar \.flow-select-toggle\{[^}]*height:/);
assert.match(text(css), /\.window-actions\{[^}]*-webkit-app-region:no-drag/);
assert.match(text(js), /showView\('live'\)/);
assert.match(text(js), /function setLiveTranslationEnabled/);
assert.match(text(js), /setLiveTranslationEnabled\(Boolean\(payload\.target_language\)\)/);
assert.match(text(js), /showView\('detail'\)/);
assert.match(text(html), /id="language-toggle"/);
assert.match(text(html), /id="all-meetings"/);
assert.match(text(html), /id="category-filter"/);
assert.match(text(html), /id="home-slogan"/);
assert.match(text(html), /id="home-eyebrow"[^>]*disabled/);
assert.match(text(html), /id="mini-meeting"/);
assert.match(text(html), /id="refinement-progress"/);
assert.doesNotMatch(text(html), /原版逐字稿仍可查看|data-refine-meeting/);
assert.match(text(html), /id="mic-level"/);
assert.match(text(html), /id="mic-input-state"/);
assert.match(text(html), /id="playback-rate"/);
assert.match(text(i18nData), /catalog\s*=\s*{/);
assert.match(text(js), /window\.BreviaLocaleData/);
assert.match(text(js), /renderSlogan/);
assert.match(text(js), /activeLibraryNav === 'recently-deleted' \? t\('最近删除'\)/);
assert.match(text(js), /if \(name === 'home'\) selectLibraryNav\(activeLibraryNav\)/);
assert.match(text(js), /async function showLibraryNav/);
assert.match(text(js), /async function transitionPage/);
assert.match(text(js), /transitionPage\(home, home/);
assert.match(text(js), /minimizeMeeting/);
assert.match(text(css), /page-in/);
assert.match(text(css), /language-out/);
assert.match(text(uiData), /modal: 'summary-model'/);
assert.match(text(js), /summaryProviders/);
assert.match(text(js), /persistSummaryConfig/);
assert.match(text(components), /function renderTranscriptSegment/);
assert.match(text(components), /inline-segment-speaker-form/);
assert.match(text(components), /function renderMeetingSummary/);
assert.match(text(components), /function flowSelect/);
assert.match(text(js), /renderMeetingDetail\(\);/);
assert.match(text(js), /function saveInlineSegmentSpeaker/);
assert.match(text(components), /function renderMeetingRow/);
assert.match(text(components), /function renderModelRow/);
assert.match(text(components), /function renderSettingsCard/);
assert.match(text(components), /function renderParticipant/);
assert.match(text(components), /function renderStatusList/);
assert.match(text(js), /renderStaticViews\(\);/);
assert.match(text(js), /function renderPrepareSelects/);
assert.match(text(js), /function renderCategoryFilter/);
assert.match(text(js), /meeting\.list\(\{ include_deleted: includeDeleted, query: meetingSearch\.value\.trim\(\) \}\)/);
assert.match(text(js), /addEventListener\('pointerdown'/);
assert.match(text(js), /addEventListener\('dragstart'/);
assert.match(text(js), /meetingSelectionSurface\.setPointerCapture/);
assert.match(text(js), /meetingSelectionSurface = document\.querySelector\('#home-view'\)/);
assert.match(text(js), /event\.clientY < libraryToolbar\.getBoundingClientRect\(\)\.top/);
assert.doesNotMatch(text(js), /pointerdown[\s\S]{0,300}event\.preventDefault\(\)/);
assert.match(text(js), /pointermove[\s\S]{0,500}meetingSelectionSurface\.setPointerCapture/);
assert.doesNotMatch(text(js), /closest\('button, input, \.meeting-actions/);
assert.match(text(js), /meetingSelectionSurface\.addEventListener\('click',[\s\S]{0,200}stopImmediatePropagation\(\)[\s\S]{0,20}true\)/);
assert.match(text(js), /data-batch-export/);
assert.match(text(js), /data-batch-restore/);
assert.match(text(js), /mutateMeetings\(permanently \? 'purge' : 'delete', meetings\)/);
assert.match(text(js), /async function mutateMeetings/);
assert.match(text(js), /async function openMeetingRow/);
assert.match(text(components), /data-meeting-action="purge"/);
assert.match(text(electronMain), /meeting\.purge/);
assert.match(text(js), /exportMany/);
assert.match(text(js), /flowSelect\('library-category'/);
assert.match(text(js), /flowSelect\('library-date'/);
assert.match(text(js), /closeMeetingMenus/);
assert.match(text(js), /closeCategoryMenu/);
assert.match(text(components), /data-meeting-action="category"/);
assert.match(text(components), /data-rename-meeting/);
assert.match(text(components), /data-delete-meeting-category/);
assert.match(text(components), /data-selection-key/);
assert.match(text(js), /data-new-meeting-category/);
assert.match(text(js), /meeting-category/);
assert.match(text(uiData), /const uiData/);
assert.match(text(uiData), /Streaming Paraformer/);
assert.match(text(uiData), /Qwen3-ASR/);
assert.match(text(i18nData), /Qwen3-ASR 1\.7B int8/);
assert.doesNotMatch(text(uiData), /VAD \+ Speaker/);
assert.doesNotMatch(text(uiData), /SenseVoice Small|Whisper Small/);
assert.match(text(i18nData), /所有转写模型都在本地运行，不会将您的隐私上传到网络/);
assert.match(text(i18nData), /Réunions et enregistrements/);
assert.match(text(i18nData), /Modèle de sous-titres en direct/);
assert.match(text(i18nData), /Gérer les modèles →/);
assert.match(text(js), /whisper-turbo/);
assert.match(text(i18nData), /实时字幕/);
assert.match(text(i18nData), /会后精修/);
assert.match(text(js), /const languageModelDefaults/);
assert.match(text(js), /en: \{ streaming: 'zipformer-en-streaming-int8', refined: 'whisper-turbo'/);
assert.match(text(js), /const compatibleStreamingModels/);
assert.match(text(html), /src="\.\/i18n\.js"/);
assert.match(text(js), /BreviaI18n\.languageOptions\(locale, t/);
assert.match(text(js), /Object\.values\(modalCopy\)\.forEach/);
assert.match(text(i18n), /new Intl\.DisplayNames/);
assert.match(text(i18n), /defaultMeetingTitle/);
assert.match(text(i18n), /selectionOverview/);
assert.match(text(js), /renderDefaultMeetingTitle\(\)/);
assert.match(text(js), /\(themeLabels\[locale\] \|\| themeLabels\.en\)/);
for (const code of ['ja', 'ko', 'fr', 'de', 'ru']) assert.match(text(html), new RegExp(`data-language="${code}"`));
assert.doesNotMatch(text(js), /音频分析/);
assert.match(text(js), /data-download-model/);
assert.match(text(js), /prepareModelChoices/);
assert.match(text(js), /qwen3-asr-1\.7b-int8/);
assert.match(text(js), /'silero-vad',\s*'ten-vad',\s*'online-punct-en-int8'/);
assert.match(text(js), /zipformer-multilingual-streaming/);
assert.match(text(js), /active-diarization-model/);
assert.doesNotMatch(text(html), /id="active-model-name"/);
assert.doesNotMatch(text(js), /createElement\('select'\)/);
assert.match(text(js), /modelPicker/);
assert.match(text(logo), /<svg/);
assert.match(text(backendClient), /this\.stopPromise/);
assert.match(text(css), /\.confirmation-actions \.secondary\{margin-top:0/);
assert.match(text(css), /\.model-card \.model-picker\{/);
assert.match(text(js), /prepareModelCard\.addEventListener\('dblclick'/);
assert.match(text(i18nData), /管理语言识别模型的下载、删除与版本信息/);
assert.match(text(i18nData), /Bibliothèque de modèles/);
assert.match(text(html), /data-model="zipformer-zh-xlarge-streaming-int8"/);
assert.match(text(js), /model\.progress/);
assert.match(text(js), /model-download-progress/);
assert.match(text(js), /function formatBytes\(bytes = 0\)/);
assert.match(text(js), /showRefinementComplete/);
assert.doesNotMatch(text(js), /function missingModelIds/);
assert.doesNotMatch(text(js), /function openModelLibraryAt/);
assert.match(text(js), /window\.brevia\.on\('model\.required'/);
assert.match(text(js), /const requiredModelIds = new Set/);
assert.match(text(js), /Promise\.all\(\[\.\.\.requiredModelIds\]\.map\(downloadRequiredModel\)\)/);
assert.match(text(js), /pending\.task === 'meeting\.start'/);
assert.match(text(js), /queueModelTask\('meeting\.start', \{ \.\.\.payload, inputs \}/);
assert.match(text(html), /id="task-cards"/);
assert.match(text(html), /data-dismiss-task-card/);
assert.match(text(js), /data-dismiss-task-card/);
assert.match(text(js), /function hideRefinementProgress/);
assert.match(text(js), /transcript\.scrollTop = transcript\.scrollHeight/);
assert.match(text(js), /const isAtLiveBottom = \(\) => transcript\.scrollHeight - transcript\.clientHeight - transcript\.scrollTop <= 32/);
assert.match(text(js), /currentCaption\.scrollLeft = currentCaption\.scrollWidth/);
assert.match(text(js), /currentCaption\.classList\.add\('caption-increment'\)/);
assert.doesNotMatch(text(html), /id="latest"/);
assert.match(text(css), /caption-increment/);
assert.doesNotMatch(text(css), /html\{zoom:/);
assert.match(text(css), /#live-view\.active/);
assert.match(text(css), /\.workspace:has\(#live-view\.active\)/);
assert.match(text(css), /\.transcript\{[^}]*min-width:0/);
assert.match(text(css), /\.transcript\{[^}]*grid-template-rows:auto minmax\(0,1fr\) auto/);
assert.match(text(css), /\.transcript-scroll \.segment\{[^}]*grid-template-columns:5\.5rem minmax\(0,1fr\)[^}]*padding-left:0/);
assert.match(text(css), /\.transcript-scroll \.segment-meta\{[^}]*align-self:flex-start/);
assert.doesNotMatch(text(css), /\.transcript-scroll \.segment p\{[^}]*-webkit-line-clamp/);
assert.match(text(css), /participants-list/);
assert.match(text(js), /function renderExportModal/);
assert.match(text(js), /data-track="vocals"/);
assert.match(text(js), /data-track="accompaniment"/);
assert.doesNotMatch(text(js), /data-export-detail[\s\S]{0,300}prompt\(/);
assert.match(text(components), /data-detail-tab="tracks"/);
assert.match(text(components), /双轨录音/);
assert.match(text(components), /data-view-full-summary/);
assert.match(text(components), /查看完整内容/);
assert.match(text(js), /function showSeparationProgress/);
assert.match(text(js), /function showSummaryConfigCard/);
assert.match(text(js), /isSummaryAuthenticationError/);
assert.match(text(js), /summary\?\.configuration_required/);
assert.match(text(js), /function showSummaryProgress/);
assert.match(text(js), /summary\.started/);
assert.match(text(js), /pendingModelTasks/);
assert.match(text(js), /pending\.task === 'tts\.synthesize'/);
assert.match(text(js), /function playTts/);
assert.match(text(js), /let ttsSubmitting = false/);
assert.match(text(js), /if \(ttsSubmitting\) return/);
assert.match(text(js), /submit\.setAttribute\('aria-busy', 'true'\)/);
assert.match(text(css), /\.tts-selects \.flow-select-options\.opens-up/);
assert.doesNotMatch(text(js), /将逐字稿发送到所选模型供应商以生成纪要/);
assert.match(text(js), /openModal\('summary-model'\)/);
assert.match(text(js), /renderSummaryDetailModal/);
assert.match(text(js), /data-summary-export-choice/);
assert.match(text(js), /data-format="pdf"/);
assert.match(text(js), /data-regenerate-summary/);
assert.match(text(js), /content: 'notes'/);
assert.match(text(js), /separation\.progress/);
assert.match(text(js), /speakerProfile\.samples/);
assert.match(text(js), /speakerProfile\.deleteSample/);
assert.match(text(asr), /Models \{segmentation_id\}, \{embedding_id\} are not installed/);
assert.match(text(electronMain), /meeting\.bundle/);
assert.match(text(electronMain), /error\.code === 'ENOENT'/);
assert.match(text(electronMain), /configuration_required: true/);
assert.match(text(electronMain), /summary\.config\.save/);
assert.doesNotMatch(text(electronMain), /ShareMenu/);
assert.match(text(js), /punct-ct-transformer-zh-en-int8/);
assert.match(text(js), /online-punct-en-int8/);
assert.match(text(js), /const modelSizes = \[1047319737, 310414022/);
assert.match(text(js), /data-delete-model/);
assert.match(text(css), /::-webkit-scrollbar-thumb\{/);
assert.match(text(css), /:hover,\.is-scrolling\{scrollbar-color:#aaa transparent/);
assert.match(text(css), /html\[data-theme=dark\] :hover,html\[data-theme=dark\] \.is-scrolling\{scrollbar-color:#666 transparent/);
assert.match(text(css), /html\[data-theme=dark\] \.brand img\{filter:invert\(\)/);
assert.match(text(css), /html\[data-theme=dark\] \.secondary,html\[data-theme=dark\] \.meeting-color,html\[data-theme=dark\] \.model-icon\{color:#eee;border-color:#eee/);
assert.match(text(css), /html\[data-theme=dark\] \.processing-bar i,html\[data-theme=dark\] \.model-download-progress i\{background-color:#fff/);
assert.match(text(js), /document\.addEventListener\('scroll',[\s\S]{0,300}is-scrolling/);
assert.match(text(js), /meeting\.exampleLocale === locale/);
assert.match(text(js), /function selectLibraryNav/);
assert.match(text(js), /await refreshBackendMeetings\(\)/);
assert.match(text(js), /let updateAvailable = false/);
assert.match(text(backendClient), /async prepare\(\{ mic, system \}\)/);
assert.match(text(backendClient), /async previewMic\(\)/);
assert.match(text(backendClient), /async stopPreview\(\)/);
assert.match(text(js), /async function previewMicrophone/);
assert.match(text(js), /transcript\.discarded/);
assert.match(text(js), /window\.brevia\.meeting\.refine\(\{ meeting_id: meeting\.id \}\)/);
assert.match(text(backendClient), /await this\.capture\.prepare\(inputs\)[\s\S]*window\.brevia\.meeting\.start\(payload\)/);
assert.match(text(backendClient), /系统音频.*未产生音频数据/);
assert.match(text(backendClient), /this\.state\.meeting\?\.id \|\| this\.capture\?\.meetingId/);
assert.match(text(backendClient), /await this\.capture\.stop\(\)/);
assert.match(text(electronMain), /function promptInitialPermissions/);
assert.match(text(electronMain), /desktopCapturer\.getSources/);
assert.match(text(electronMain), /microphone === 'not-determined'/);
assert.match(text(electronMain), /screen === 'not-determined'/);
assert.doesNotMatch(text(electronMain), /permissions-v2|Privacy_ScreenCapture/);
assert.match(text(electronMain), /setDisplayMediaRequestHandler/);
assert.doesNotMatch(text(electronMain), /useSystemPicker/);
assert.match(text(electronMain), /MacCatapLoopbackAudioForScreenShare/);
assert.match(text(electronMain), /requestSingleInstanceLock/);
assert.match(text(electronMain), /meeting\.export-many/);
assert.match(text(js), /const button = event\.currentTarget/);
assert.doesNotMatch(text(js), /await breviaClient\.pause\(!paused\)[\s\S]{0,200}event\.currentTarget/);
assert.match(text(js), /let followLiveTranscript = true/);
assert.match(text(js), /transcript\.scrollTop = transcript\.scrollHeight/);
assert.doesNotMatch(text(js), /segment\.offsetTop - \(transcript\.clientHeight - segment\.offsetHeight\) \/ 2/);
assert.match(text(js), /liveSpeakers\.set/);
assert.match(text(js), /uiData\.live\.status\[0\]\.value = streamingModelName/);
assert.match(text(js), /segment\.classList\.remove\('is-active'\)/);
assert.match(text(js), /示例会议及录音已删除/);
assert.match(text(js), /function syncPlaybackTranscript/);
assert.match(text(js), /if \(!voiceId\) \{ showToast/);
assert.match(text(js), /function showRefinementProgress/);
assert.match(text(js), /\$\{copy\.title\} - \$\{refinementMeetingTitle\}/);
assert.match(text(js), /segment\.version\.startsWith\('postprocess'\)/);
assert.match(text(js), /playback\.mix \|\| meeting\.audio\.playback\.mic/);
assert.match(text(js), /segment\.is-active/);
assert.match(text(js), /body\.scrollTo/);
assert.match(text(i18nData), /Aún no se ha generado el resumen/);
assert.match(text(i18nData), /Speaker diarization/);
for (const copy of ['ローカル会議', '로컬 회의', 'Réunion locale', 'Lokale Besprechung', 'Локальная встреча']) assert.match(text(i18nData), new RegExp(copy));
assert.doesNotMatch(text(css), /\.status\.complete:before/);
assert.match(text(css), /\.page-head>div\{[^}]*min-height:/);
assert.doesNotMatch(text(js), /renderModelRow/);
assert.match(text(components), /id="installed-models"[\s\S]*data-settings-modal="models"/);
assert.match(text(js), /Object\.values\(modalCopy\)\.forEach/);
assert.match(text(components), /class="transcript-body"/);
assert.match(text(components), /data-start=/);
assert.match(text(components), /data-segment-id=/);
assert.match(text(components), /class="segment-copy"/);
assert.match(text(js), /segmentContextMenu/);
assert.match(text(js), /addProfileSample/);
assert.match(text(js), /data-create-segment-profile/);
assert.match(text(i18nData), /Create voiceprint/);
assert.match(text(css), /\.final-transcript\{[^}]*height:100%[^}]*overflow:hidden/);
assert.match(text(css), /#prepare-view\.active\{[^}]*height:calc\(100dvh - 4rem\)/);
assert.match(text(css), /#detail-view\.active\{[^}]*height:calc\(100dvh - 4rem\)/);
assert.match(text(css), /\.transcript-body\{[^}]*overflow-y:auto/);
assert.match(text(css), /scrollbar-gutter:stable/);
assert.match(text(css), /@media \(min-width:851px\) and \(max-width:1100px\),\(min-width:851px\) and \(max-height:760px\)/);
assert.match(text(css), /\.transcript\{[^}]*grid-template-rows:auto minmax\(0,1fr\) auto/);
assert.match(text(css), /::-webkit-scrollbar-thumb/);
assert.match(text(css), /\.sidebar\{[^}]*position:sticky/);
assert.match(text(css), /\.input-meter/);
assert.match(text(css), /\.selection-marquee\{/);
assert.match(text(css), /\.meeting-row\.is-selected\{/);
assert.match(text(html), /ui-data\.js[\s\S]*ui-components\.js[\s\S]*app\.js/);
console.log('UI structure checks passed.');
