import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const [html, css, js, uiData, components] = await Promise.all(['index.html', 'styles.css', 'app.js', 'ui-data.js', 'ui-components.js'].map((file) => readFile(file)));
const backendClient = await readFile('backend-client.js');
const electronMain = await readFile('../electron/main.js');
const text = (value) => value.toString();

for (const id of ['home-view', 'prepare-view', 'live-view', 'detail-view', 'settings-view', 'meeting-form', 'end-meeting']) {
  assert.match(text(html), new RegExp(`id="${id}"`));
}
assert.match(text(css), /prefers-reduced-motion:\s*reduce/);
assert.match(text(css), /\.window-bar\{[^}]*-webkit-app-region:drag/);
assert.match(text(css), /\.window-actions\{[^}]*-webkit-app-region:no-drag/);
assert.match(text(js), /showView\('live'\)/);
assert.match(text(js), /showView\('detail'\)/);
assert.match(text(html), /id="language-toggle"/);
assert.match(text(html), /id="all-meetings"/);
assert.match(text(html), /id="category-filter"/);
assert.match(text(html), /id="home-slogan"/);
assert.match(text(html), /id="mini-meeting"/);
assert.match(text(js), /catalog\s*=\s*{/);
assert.match(text(js), /renderSlogan/);
assert.match(text(js), /minimizeMeeting/);
assert.match(text(css), /page-in/);
assert.match(text(css), /language-out/);
assert.match(text(html), /data-settings-modal="summary-model"/);
assert.match(text(js), /summaryProviders/);
assert.match(text(js), /persistSummaryConfig/);
assert.match(text(components), /function renderTranscriptSegment/);
assert.match(text(components), /function renderMeetingSummary/);
assert.match(text(components), /function flowSelect/);
assert.match(text(js), /renderMeetingDetail\(\);/);
assert.match(text(components), /function renderMeetingRow/);
assert.match(text(components), /function renderModelRow/);
assert.match(text(components), /function renderSettingsCard/);
assert.match(text(components), /function renderParticipant/);
assert.match(text(components), /function renderStatusList/);
assert.match(text(js), /renderStaticViews\(\);/);
assert.match(text(js), /function renderPrepareSelects/);
assert.match(text(js), /function renderCategoryFilter/);
assert.match(text(js), /flowSelect\('library-category'/);
assert.match(text(js), /flowSelect\('library-date'/);
assert.match(text(js), /closeMeetingMenus/);
assert.match(text(js), /closeCategoryMenu/);
assert.match(text(components), /data-meeting-action="category"/);
assert.match(text(components), /data-rename-meeting/);
assert.match(text(components), /data-delete-meeting-category/);
assert.match(text(js), /data-new-meeting-category/);
assert.match(text(js), /meeting-category/);
assert.match(text(uiData), /const uiData/);
assert.match(text(uiData), /Streaming Paraformer/);
assert.match(text(uiData), /Qwen3-ASR/);
assert.doesNotMatch(text(uiData), /VAD \+ Speaker/);
assert.doesNotMatch(text(uiData), /SenseVoice Small|Whisper Small/);
assert.match(text(js), /所有转写模型都在本地运行，不会将您的隐私上传到网络/);
assert.doesNotMatch(text(js), /Streaming Zipformer|Whisper/);
assert.match(text(js), /实时字幕/);
assert.match(text(js), /会后精修/);
assert.match(text(js), /language === 'en' \? 'zipformer-en-streaming-int8'/);
assert.match(text(js), /model\.stages\.includes\('punctuation'\) \? '标点恢复'/);
assert.doesNotMatch(text(js), /音频分析/);
assert.match(text(js), /data-download-model/);
assert.match(text(js), /data-delete-model/);
assert.match(text(js), /meeting\.exampleLocale === locale/);
assert.match(text(js), /function selectLibraryNav/);
assert.match(text(js), /await refreshBackendMeetings\(\)/);
assert.match(text(js), /let updateAvailable = false/);
assert.match(text(backendClient), /async prepare\(\{ mic, system \}\)/);
assert.match(text(backendClient), /await this\.capture\.prepare\(inputs\)[\s\S]*window\.brevia\.meeting\.start\(payload\)/);
assert.match(text(backendClient), /系统音频.*未产生音频数据/);
assert.match(text(backendClient), /this\.state\.meeting\?\.id \|\| this\.capture\?\.meetingId/);
assert.match(text(backendClient), /await this\.capture\.stop\(\)/);
assert.match(text(electronMain), /function promptInitialPermissions/);
assert.match(text(electronMain), /desktopCapturer\.getSources/);
assert.match(text(electronMain), /setDisplayMediaRequestHandler/);
assert.doesNotMatch(text(electronMain), /useSystemPicker/);
assert.match(text(electronMain), /MacCatapLoopbackAudioForScreenShare/);
assert.match(text(electronMain), /requestSingleInstanceLock/);
assert.match(text(electronMain), /Privacy_ScreenCapture/);
assert.match(text(js), /const button = event\.currentTarget/);
assert.match(text(js), /let followLiveTranscript = true/);
assert.match(text(js), /liveSpeakers\.set/);
assert.match(text(js), /segment\.classList\.remove\('is-active'\)/);
assert.match(text(js), /示例会议及录音已删除/);
assert.match(text(js), /function syncPlaybackTranscript/);
assert.match(text(js), /playback\.mix \|\| meeting\.audio\.playback\.mic/);
assert.match(text(js), /segment\.is-active/);
assert.match(text(js), /body\.scrollTo/);
assert.match(text(js), /Aún no se ha generado el resumen/);
assert.match(text(js), /function renderTermOverview/);
assert.match(text(js), /Speaker diarization/);
assert.match(text(js), /No hay términos/);
assert.match(text(js), /row\.dataset\.stage/);
assert.match(text(js), /modalCopy\[language\]\.storage\.items\.forEach/);
assert.match(text(components), /class="transcript-body"/);
assert.match(text(components), /data-start=/);
assert.match(text(css), /\.final-transcript\{[^}]*height:560px[^}]*overflow:hidden/);
assert.match(text(css), /\.transcript-body\{[^}]*overflow-y:auto/);
assert.match(text(html), /ui-data\.js[\s\S]*ui-components\.js[\s\S]*app\.js/);
console.log('UI structure checks passed.');
