import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { runInNewContext } from 'node:vm';

const [html, css, app, meetings, meetingDetail, uiData, components, i18n, i18nData, tailwind, onboarding, workspaces] = await Promise.all(['index.html', 'styles.css', 'app.js', 'app-meetings.js', 'app-meeting-detail.js', 'ui-data.js', 'ui-components.js', 'i18n.js', 'i18n-data.js', 'tailwind.css', 'onboarding.js', 'workspaces.js'].map((file) => readFile(file)));
const js = Buffer.concat([app, meetings, meetingDetail, workspaces]);
const [backendClient, logo, revealGif] = await Promise.all(['backend-client.js', 'assets/brevia-logo.svg', 'assets/brevia-logo-reveal.gif'].map((file) => readFile(file)));
const [electronMain, preload, packageManifest, modelManifest] = await Promise.all([readFile('../electron/main.js'), readFile('../electron/preload.js'), readFile('../package.json', 'utf8').then(JSON.parse), readFile('../backend/models.json', 'utf8').then(JSON.parse)]);
const asr = await readFile('../backend/asr.py');
const packWorker = await readFile('../backend/pack_worker.py');
const workerSession = await readFile('../backend/worker_session.py');
const text = (value) => value.toString().replace(/\r\n/g, '\n');
const onboardingContext = { window: {}, localStorage: { getItem: () => null, setItem() {} }, navigator: { language: 'zh-CN' } };
runInNewContext(text(onboarding), onboardingContext);
assert.deepEqual(Array.from(onboardingContext.window.BreviaOnboarding.defaultMeetingLanguages('zh')), ['zh']);
assert.deepEqual(Array.from(onboardingContext.window.BreviaOnboarding.defaultMeetingLanguages('en')), ['en']);
assert.match(text(app), /name="onboarding-\$\{index \? 'source-separation' : 'denoiser'\}" checked/);
assert.match(text(app), /name="onboarding-translation" checked/);
const componentContext = {};
runInNewContext(text(components), componentContext);
const mediaContext = { window: {}, navigator: { mediaDevices: {} } };
runInNewContext(`${text(backendClient)}\nthis.AudioCapture = AudioCapture;`, mediaContext);
const stoppedTracks = [];
const loopbackAudio = { readyState: 'live', stop() { stoppedTracks.push('audio'); } };
const displayVideo = { readyState: 'live', stop() { stoppedTracks.push('video'); } };
mediaContext.stopMediaStream({ getVideoTracks: () => [displayVideo], getAudioTracks: () => [loopbackAudio] });
assert.deepEqual(stoppedTracks, ['video', 'audio']);
mediaContext.stopMediaStream({ getVideoTracks: () => [displayVideo], getAudioTracks: () => [loopbackAudio] });
assert.deepEqual(stoppedTracks, ['video', 'audio']);
const microphone = { readyState: 'live', stop() { stoppedTracks.push('mic'); } };
mediaContext.stopMediaStream({ getVideoTracks: () => [], getAudioTracks: () => [microphone] });
assert.deepEqual(stoppedTracks, ['video', 'audio', 'mic']);
let displayConstraints;
const capturedAudio = { readyState: 'live', stop() {} };
const capturedVideo = { readyState: 'live', stop() {} };
mediaContext.navigator.mediaDevices.getDisplayMedia = async (constraints) => {
  displayConstraints = constraints;
  return { getAudioTracks: () => [capturedAudio], getVideoTracks: () => [capturedVideo] };
};
const systemCapture = new mediaContext.AudioCapture(() => {}, () => {});
await systemCapture.prepare({ mic: false, system: true });
assert.equal(displayConstraints.audio.systemAudio, 'include');
assert.equal(systemCapture.pendingStreams[0].track, 'system');
await systemCapture.stop();
mediaContext.navigator.mediaDevices.getDisplayMedia = async () => ({ getAudioTracks: () => [], getVideoTracks: () => [{ readyState: 'live', stop() {} }] });
await assert.rejects(new mediaContext.AudioCapture().prepare({ mic: false, system: true }), /未检测到系统音频/);
const localeContext = { window: {} };
runInNewContext(text(i18nData), localeContext);
const meetingCacheStorage = new Map([['brevia-meetings-v1', JSON.stringify({ savedAt: Date.now(), meetings: [{ id: 'cached', deleted: false }] })]]);
const meetingCacheContext = {
  uiData: { meetings: [] }, window: { brevia: {} }, activeLibraryNav: 'all-meetings', meetingSearch: { value: '' },
  localStorage: {
    getItem: (key) => meetingCacheStorage.get(key) || null,
    setItem: (key, value) => meetingCacheStorage.set(key, value),
    removeItem: (key) => meetingCacheStorage.delete(key),
  },
};
runInNewContext(text(meetings), meetingCacheContext);
assert.equal(meetingCacheContext.uiData.meetings[0].id, 'cached');
meetingCacheContext.uiData.meetings.push({ id: 'deleted', deleted: true });
meetingCacheContext.cacheMeetingList();
assert.deepEqual(JSON.parse(meetingCacheStorage.get('brevia-meetings-v1')).meetings.map(({ id }) => id), ['cached']);
const advancedDescription = '调整识别、端点检测、说话人分离和本地模型运行参数。';
for (const code of ['en', 'es', 'ja', 'ko', 'fr', 'de', 'ru']) assert.notEqual(localeContext.window.BreviaLocaleData.catalog[code].labels[advancedDescription], advancedDescription);
const runtimeI18nKeys = ['离线功能', '请选择声音', '请先配置翻译模型', '纪要服务拒绝了请求', '纪要模型需要配置', '请先选择译文目标并配置纪要模型', '将确认字幕发送到 {provider} 生成译文。是否继续？', '选择格式：md / txt / json / srt / docx / pdf / flac / wav / m4a', '刚刚', '已导出「{title}」', '示例会议及录音已删除', '会议已移至最近删除', '暂停录音', '播放录音', '这场会议没有可播放的录音', '纪要配置加载失败', '配置或后端启动失败', '翻译失败', '压缩包已导出', '未找到录音，已导出逐字稿压缩包', '内置纪要模型清单暂不可用。', '请先选择或填写纪要模型。', '请填写请求地址。', '请填写 API Key。', '纪要模型已保存'];
for (const code of ['en', 'es', 'ja', 'ko', 'fr', 'de', 'ru']) for (const key of runtimeI18nKeys) assert.notEqual(localeContext.window.BreviaLocaleData.catalog[code].labels[key], key);
for (const code of ['en', 'es', 'ja', 'ko', 'fr', 'de', 'ru']) assert.notEqual(localeContext.window.BreviaLocaleData.catalog[code].labels['添加录音到声纹库'], '添加录音到声纹库');
for (const code of ['en', 'es', 'ja', 'ko', 'fr', 'de', 'ru']) assert.notEqual(localeContext.window.BreviaLocaleData.catalog[code].labels['清空数据'], '清空数据');
for (const code of ['en', 'es', 'ja', 'ko', 'fr', 'de', 'ru']) {
  assert.notEqual(localeContext.window.BreviaLocaleData.catalog[code].labels['VAD 模型'], 'VAD 模型');
  assert.notEqual(localeContext.window.BreviaLocaleData.catalog[code].labels['查看完整内容'], '查看完整内容');
  assert.notEqual(localeContext.window.BreviaLocaleData.catalog[code].labels['确认'], '确认');
}
for (const [code, stage, allLanguages] of [['ja', 'ライブ字幕', 'すべての言語'], ['ko', '실시간 자막', '모든 언어'], ['de', 'Live-Untertitel', 'Alle Sprachen'], ['ru', 'Субтитры в реальном времени', 'Все языки']]) {
  const items = localeContext.window.BreviaLocaleData.appCopy.modalCopy[code].models.items;
  assert.equal(items[0][0], stage);
  assert.equal(items.find(([, name]) => name === 'Spleeter 2 Stems')[2], allLanguages);
}
assert.deepEqual(Array.from(localeContext.window.BreviaLocaleData.appCopy.modalCopy.zh.models.items.slice(9, 13), ([, name]) => name), ['Qwen3-ASR', 'FunASR Nano int8', 'Whisper Large v3', 'Qwen3-ASR 1.7B int8']);
for (const id of ['vits-mimic3-ko-kss-low', 'vits-piper-fr-siwis-medium-int8', 'vits-piper-de-thorsten-medium-int8', 'vits-piper-es-sharvard-medium-int8', 'vits-piper-ru-irina-medium-int8', 'zipformer-zh-streaming-int8', 'whisper-turbo', 'fire-red-asr2-ctc-zh-en-int8', 'nemo-titanet-small-en']) {
  assert.equal(modelManifest.find((entry) => entry.id === id), undefined, `pruned model ${id} still in manifest`);
  assert.doesNotMatch(text(js), new RegExp(`'${id}'`), `pruned model ${id} still referenced in app js`);
}
assert.equal(componentContext.rectanglesIntersect({ left: 0, right: 10, top: 0, bottom: 10 }, { left: 8, right: 12, top: 8, bottom: 12 }), true);
assert.equal(componentContext.rectanglesIntersect({ left: 0, right: 2, top: 0, bottom: 2 }, { left: 3, right: 5, top: 3, bottom: 5 }), false);
componentContext.t = (value) => value;
componentContext.editingMeetingIndex = null;
componentContext.categories = [];
assert.doesNotMatch(componentContext.renderMeetingRow({ id: 'active', tone: 'violet', title: 'Active', meta: '', tags: [], status: { tone: 'processing' } }, 0), /data-meeting-action="delete"/);
assert.doesNotMatch(componentContext.renderParticipant({ id: '1', name: '<img src=x>', source: 'Mic', avatar: 'blue', level: 'high' }), /<img/);
assert.match(componentContext.renderMeetingRow({ id: 'drag-me', tone: 'violet', title: 'Meeting', meta: '', tags: [], status: {} }, 0), /draggable="true"/);
assert.doesNotMatch(componentContext.renderStatusList([{ label: 'Status', value: '<script>' }]), /<script>/);
assert.doesNotMatch(componentContext.renderTranscriptSegment({ time: '00:00', speaker: { name: 'A' }, text: '<img src=x onerror=alert(1)>' }), /<img/);
assert.match(componentContext.renderTranscriptSegment({ time: '00:00', speaker: { name: 'A', overlapNames: ['A', 'B'] }, text: 'test' }), /重叠说话：A、B/);
assert.doesNotMatch(componentContext.renderMeetingSummary({ title: '<script>alert(1)</script>', sections: [{ title: 'Note', text: '<img src=x>' }] }), /<script>|<img/);

for (const id of ['home-view', 'prepare-view', 'live-view', 'detail-view', 'settings-view', 'meeting-form', 'end-meeting']) {
  assert.match(text(html), new RegExp(`id="${id}"`));
}
assert.match(text(html), /Content-Security-Policy/);
assert.match(text(html), /frame-src 'none'/);
assert.doesNotMatch(text(preload), /secret\.get/);
assert.match(text(electronMain), /printToPDF\(\{ printBackground: true \}\)/);
assert.match(text(css), /prefers-reduced-motion:\s*reduce/);
assert.match(text(css), /\.window-bar\{[^}]*-webkit-app-region:drag/);
assert.match(text(css), /\.window-bar\{[^}]*position:sticky/);
assert.match(text(css), /\.detail-refine \.flow-select-options button\{[^}]*overflow-wrap:anywhere/);
assert.match(text(css), /\.detail-refine \.flow-select-options\{[^}]*width:clamp\(16rem,30vw,26rem\)/);
assert.match(text(tailwind), /segment-context-label, \.segment-context-arrow \{ @apply shrink-0 p-0/);
assert.match(text(tailwind), /segment-context-options > button \{ @apply block w-full px-3 py-2/);
assert.match(text(tailwind), /segment-context-options > span \{ @apply block px-3 py-2/);
assert.match(text(tailwind), /segment-context-name-form \{ @apply w-52 p-3 text-\[12px\] leading-5/);
assert.match(text(app), /refineButton\.innerHTML = refineButton\.disabled \? t\('正在精修'\) : `\$\{t\('精修'\)\} <span>⌄<\/span>`/);
assert.match(text(tailwind), /segment-context-name-form input \{ @apply h-8 min-w-0.*text-\[12px\] leading-5/);
assert.match(text(tailwind), /segment-context-submenu\.is-positioned > \.segment-context-options/);
assert.match(text(tailwind), /segment-context-options \{ @apply invisible fixed hidden min-w-44/);
assert.match(text(js), /function positionFloating/);
assert.match(text(js), /placements\.map\(\(placement\) => positions\[placement\]\)\.find/);
assert.match(text(js), /Math\.max\(8, Math\.min\(position\.left, window\.innerWidth - width - 8\)\)/);
assert.match(text(js), /function fitSegmentSubmenu/);
assert.match(text(js), /submenu\.classList\.contains\('is-positioned'\)/);
assert.match(text(css), /\.app-shell\{[^}]*grid-template-columns:clamp\(220px,22vw,272px\)/);
assert.match(text(css), /\.task-cards\{[^}]*min-width:0[^}]*overflow:hidden auto/);
assert.match(text(css), /\.required-models-card ul\{[^}]*max-height:min\(36vh,18rem\)[^}]*overflow:hidden auto/);
assert.match(text(css), /#prepare-view\.active\{[^}]*overflow:hidden/);
assert.match(text(css), /\.prepare-layout\{[^}]*grid-template-columns:minmax\(0,2fr\) minmax\(12\.5rem,1fr\)/);
assert.match(text(css), /\.prepare-layout\{[^}]*transform:scale\(var\(--prepare-scale,1\)\)/);
assert.match(text(css), /#import-recording\{[^}]*margin-top:0/);
assert.match(text(js), /function fitPrepareLayout/);
assert.match(text(js), /function renderModelDownloadQueue/);
assert.match(text(js), /id = 'model-download-queue'/);
assert.match(text(js), /const installed = kind === 'models' && modelPaths\.has\(modelIds\[sourceIndex\]\)/);
assert.match(text(electronMain), /BREVIA_MODELS_DIR: process\.env\.BREVIA_MODELS_DIR \|\| path\.join\(dataDir\(\), 'models'\)/);
assert.match(text(electronMain), /const dataDir = \(\) => process\.env\.BREVIA_DATA_DIR \|\|/);
assert.match(text(electronMain), /const resetOnboarding = process\.argv\.includes\('--reset-onboarding'\)/);
assert.match(text(electronMain), /query: \{ resetOnboarding: '1' \}/);
assert.match(text(js), /resetOnboarding'\)\) localStorage\.removeItem\('brevia-onboarding-complete'\)/);
assert.match(text(js), /window\.brevia\.task\[paused \? 'resume' : 'pause'\]/);
assert.match(text(js), /miniPlaybackSeek\.addEventListener\('pointerdown'/);
assert.match(text(js), /let contextMeetingId;/);
assert.match(text(js), /openSegmentContextMenu\(meetingId, segmentId, x, y\)/);
assert.match(text(js), /followPlaybackTranscript = false/);
assert.match(text(workerSession), /speaker, speaker_name = self\._identify_speaker/);
assert.doesNotMatch(text(workerSession), /payload\["track"\] == "system"/);
assert.match(text(js), /styles\.paddingTop.*styles\.paddingBottom/);
assert.match(text(js), /new ResizeObserver\(\(\) => requestAnimationFrame\(fitPrepareLayout\)\)/);
assert.doesNotMatch(text(css), /max-width:1100px|max-height:760px/);
assert.match(text(css), /\.library-toolbar \.search input,.library-toolbar \.flow-select-toggle\{[^}]*height:/);
assert.match(text(css), /\.window-actions\{[^}]*-webkit-app-region:no-drag/);
assert.match(text(js), /showView\('live'\)/);
assert.match(text(js), /function setLiveTranslationEnabled/);
assert.match(text(js), /setLiveTranslationEnabled\(Boolean\(payload\.target_language\)\)/);
assert.match(text(js), /showView\('detail'\)/);
assert.match(text(html), /id="language-toggle"/);
assert.match(text(html), /href="https:\/\/github\.com\/zerolovesea\/Brevia"/);
assert.match(text(html), /id="all-meetings"/);
assert.doesNotMatch(text(html), /id="category-filter"/);
assert.doesNotMatch(text(js), /renderCategoryFilter|data-assign-category|data-new-meeting-category/);
assert.match(text(js), /refreshLocalizedTaskCards\(\);/);
for (const code of ['en', 'es', 'ja', 'ko', 'fr', 'de', 'ru']) assert.notEqual(localeContext.window.BreviaLocaleData.catalog[code].labels['导入录音'], '导入录音');
assert.doesNotMatch(text(js), /data-pause-required-all|data-download-required-all/);
assert.match(text(js), /data-pause-required="\$\{id\}" aria-label=.*Ⅱ/);
assert.match(text(html), /id="home-slogan"/);
assert.match(text(html), /id="home-eyebrow"[^>]*disabled/);
assert.match(text(html), /id="mini-meeting"/);
assert.match(text(html), /id="mini-playback-seek" role="slider"/);
assert.doesNotMatch(text(html), /id="mini-playback-seek" type="range"/);
assert.match(text(html), /id="refinement-progress"/);
assert.match(text(html), /data-pause-task/);
assert.doesNotMatch(text(html), /原版逐字稿仍可查看|data-refine-meeting/);
assert.match(text(html), /id="mic-level"/);
assert.match(text(html), /id="mic-input-state"/);
assert.match(text(html), /id="playback-rate"/);
assert.match(text(i18nData), /catalog\s*=\s*{/);
assert.match(text(js), /window\.BreviaLocaleData/);
assert.doesNotMatch(text(js), /defaultSummaryPrompts|prompt-form/);
assert.match(text(js), /const summaryProviders = \['built-in', 'claude', 'openai', 'openrouter', 'custom-openai', 'custom-claude'\]/);
assert.match(text(js), /model\.kind === 'llama-chat' && modelPaths\.has\(model\.id\)/);
// 只有两个自定义供应商暴露请求地址，固定供应商的地址由 summaryProviderPresets 派生。
assert.match(text(js), /const endpointField = preset\.needsEndpoint \?/);
assert.match(text(js), /'custom-openai': \{ format: 'openai', endpoint: '', needsKey: true, needsEndpoint: true/);
assert.match(text(js), /openrouter: \{ format: 'openai', endpoint: 'https:\/\/openrouter\.ai\/api\/v1\/chat\/completions', needsKey: true, needsEndpoint: false/);
assert.match(text(js), /data-download-summary-model="\$\{escapeHtml\(model\.id\)\}"/);
assert.match(text(js), /data-builtin-model-id="\$\{escapeHtml\(model\.id\)\}"/);
assert.doesNotMatch(text(js), /ollama/i);
assert.doesNotMatch(text(i18nData), /ollama/i);
assert.doesNotMatch(text(js), /data-new-summary-model|data-delete-summary-model|active-summary-config/);
assert.match(text(js), /type="password"[^>]*placeholder="\$\{entry\.keyReference/);
assert.doesNotMatch(text(js), /secret\.get|summaryKeyValues/);
assert.match(text(js), /speakerProfileName\(profile\)/);
assert.match(text(js), /window\.brevia\?\.appInfo\?\.version\?\.\(\)/);
assert.match(text(electronMain), /ipcMain\.handle\('app\.version', \(\) => app\.getVersion\(\)\)/);
assert.match(text(electronMain), /handle\('app\.maintain', z\.object\(\{\}\), 'app\.maintain'\)/);
assert.match(text(electronMain), /const useBundledWorker = app\.isPackaged/);
assert.match(text(js), /fetch\('\.\.\/package\.json'\)/);
assert.match(text(js), /const BUILTIN_VOICE_NAMES =/);
assert.match(text(js), /Object\.keys\(BUILTIN_VOICE_NAMES\)\.find/);
assert.match(text(js), /renderSettingsView\(\);[\s\S]{0,120}append\(speakerProfileCard, updateCard\)/);
assert.match(text(components), /function renderSettingsView\(\)/);
assert.doesNotMatch(text(electronMain), /ipcMain\.handle\('secret\.get'/);
assert.match(text(js), /renderSlogan/);
assert.match(text(js), /activeLibraryNav === 'recently-deleted' \? t\('最近删除'\)/);
assert.match(text(js), /if \(name === 'home'\) selectLibraryNav\(activeLibraryNav\)/);
assert.match(text(js), /async function showLibraryNav/);
assert.match(text(js), /async function transitionPage/);
assert.match(text(js), /transitionPage\(home, home/);
assert.match(text(js), /minimizeMeeting/);
assert.match(text(css), /page-in/);
assert.match(text(css), /language-out/);
assert.match(text(uiData), /modal: 'summary-model'/);
assert.match(text(js), /summaryProviders/);
assert.match(text(js), /persistSummaryConfig/);
assert.match(text(components), /function renderTranscriptSegment/);
assert.match(text(components), /inline-segment-speaker-form/);
assert.match(text(components), /function renderMeetingSummary/);
assert.match(text(components), /function flowSelect/);
assert.match(text(js), /renderMeetingDetail\(\);/);
assert.match(text(js), /function saveInlineSegmentSpeaker/);
assert.match(text(components), /function renderMeetingRow/);
assert.match(text(components), /function renderModelRow/);
assert.match(text(components), /function renderSettingsCard/);
assert.match(text(components), /function renderParticipant/);
assert.match(text(components), /function renderStatusList/);
assert.match(text(js), /renderStaticViews\(\);/);
assert.match(text(js), /function renderPrepareSelects/);
assert.match(text(js), /function selectCurrentWorkspaceForMeeting/);
assert.match(text(js), /if \(target\.dataset\.view === 'prepare'\) selectCurrentWorkspaceForMeeting\(\)/);
assert.match(text(js), /__new_workspace__/);
assert.match(text(js), /showNewWorkspaceDialog\(null, \(workspace\)/);
assert.match(text(app), /const rect = action\.getBoundingClientRect\(\);\s+closeMeetingMenus\(\);\s+if \(typeof showWorkspaceAssignMenu === 'function'\) \{\s+showWorkspaceAssignMenu\(index, rect\);/);
assert.match(text(js), /function renderWorkspaceNav/);
assert.match(text(js), /async function switchWorkspace/);
assert.match(text(js), /await transitionPage\(document\.querySelector\('#home-view'\), document\.querySelector\('#home-view'\), applyWorkspace\)/);
assert.match(text(js), /meeting\.list\(\{ include_deleted: includeDeleted, query: meetingSearch\.value\.trim\(\) \}\)/);
assert.match(text(js), /addEventListener\('pointerdown'/);
assert.match(text(js), /addEventListener\('dragstart'/);
assert.match(text(js), /meetingSelectionSurface\.setPointerCapture/);
assert.match(text(js), /meetingSelectionSurface = document\.querySelector\('#home-view'\)/);
assert.match(text(js), /event\.clientY < libraryToolbar\.getBoundingClientRect\(\)\.top/);
assert.doesNotMatch(text(js), /pointerdown[\s\S]{0,300}event\.preventDefault\(\)/);
assert.match(text(js), /pointermove[\s\S]{0,500}meetingSelectionSurface\.setPointerCapture/);
assert.doesNotMatch(text(js), /closest\('button, input, \.meeting-actions/);
assert.match(text(js), /meetingSelectionSurface\.addEventListener\('click',[\s\S]{0,200}stopImmediatePropagation\(\)[\s\S]{0,20}true\)/);
assert.match(text(js), /data-batch-export/);
assert.match(text(js), /data-batch-restore/);
assert.match(text(js), /mutateMeetings\(permanently \? 'purge' : 'delete', meetings\)/);
assert.match(text(js), /async function mutateMeetings/);
assert.match(text(js), /async function openMeetingRow/);
assert.match(text(components), /data-meeting-action="purge"/);
assert.match(text(electronMain), /meeting\.purge/);
assert.match(text(electronMain), /handleModelRequirement\('meeting\.reconfigure', meetingReconfigure, 'meeting\.reconfigure'\)/);
assert.match(text(electronMain), /const meetingReconfigure = id\.extend/);
assert.match(text(electronMain), /'meeting\.reconfigured'/);
assert.match(text(electronMain), /endpoint: z\.string\(\)\.url\(\)\.optional\(\)/);
// 纪要配置收敛为「单套激活 + 按供应商记住凭据」，只认 version 2，不再迁移旧结构。
assert.match(text(electronMain), /const summaryProviderIds = \['built-in', 'claude', 'openai', 'openrouter', 'custom-openai', 'custom-claude'\]/);
assert.match(text(electronMain), /providers: z\.partialRecord\(z\.enum\(summaryProviderIds\), summaryProviderEntry\)/);
assert.match(text(electronMain), /if \(!api_key && !isBuiltInProvider\(value\.provider\)\) return \{ configuration_required: true \}/);
assert.match(text(electronMain), /return current\.success \? current\.data : null;/);
assert.doesNotMatch(text(electronMain), /legacySummaryConfig|migrateSummaryConfig/);
assert.doesNotMatch(text(js), /migrateSummaryConfig|inferSummaryProvider/);
assert.doesNotMatch(text(electronMain), /ollama/i);
assert.match(text(electronMain), /ipcMain\.handle\('translation\.generate',[\s\S]{0,700}target_language: z\.string\(\)\.min\(2\)\.max\(32\),[\s\S]{0,100}consent: z\.literal\(true\)/);
assert.doesNotMatch(text(electronMain), /ipcMain\.handle\('translation\.generate',[\s\S]{0,700}provider: z\.string\(\)/);
assert.match(text(electronMain), /const startupAnimationMs = 1700;/);
assert.match(text(electronMain), /const startupDataWaitMs = 2200;/);
assert.doesNotMatch(text(electronMain), /const splash = new BrowserWindow/);
assert.match(text(electronMain), /window\.loadFile\(path\.join\(packagedRoot, 'frontend', 'index\.html'\)/);
assert.match(text(electronMain), /webContents\.on\('did-finish-load'/);
assert.doesNotMatch(text(electronMain), /webContents\.once\('did-finish-load'/);
assert.match(text(electronMain), /reloadRevealTimer = setTimeout/);
assert.match(text(electronMain), /!pageReady \|\| !animationComplete \|\| !initializationReady/);
assert.match(text(electronMain), /type: 'startup\.ready'/);
assert.match(text(html), /id="startup-splash"/);
assert.match(text(html), /brevia-logo-reveal\.gif/);
assert.match(text(js), /brevia\.on\('startup\.ready'/);
assert.match(text(js), /const dismissStartupSplash/);
assert.match(text(meetings), /brevia-meetings-v1/);
assert.match(text(js), /cacheMeetingList\(\)/);
assert.match(text(css), /\.startup-splash\{[^}]*z-index:100[^}]*transition:opacity \.36s/);
assert.match(text(electronMain), /PYTHONUTF8: '1'/);
assert.match(text(electronMain), /setPermissionRequestHandler/);
assert.match(text(js), /exportMany/);
assert.doesNotMatch(text(js), /flowSelect\('library-category'/);
assert.match(text(js), /flowSelect\('library-date'/);
assert.match(text(js), /const dateMatch = activeDateRange === 'all'/);
assert.match(text(js), /activeView !== 'detail' && playbackStarted && Boolean\(playerAudio\.src\) && !playerAudio\.ended/);
assert.match(text(js), /closeMeetingMenus/);
assert.doesNotMatch(text(js), /closeCategoryMenu/);
assert.match(text(js), /const positionMeetingMenu =/);
assert.match(text(js), /window\.innerHeight - anchor\.bottom < height && anchor\.top >= height/);
assert.match(text(css), /\.meeting-menu\{(?=[^}]*position:fixed)(?=[^}]*z-index:50)/);
assert.match(text(css), /\.detail-head\{(?=[^}]*z-index:50)/);
assert.doesNotMatch(text(components), /data-meeting-action="category"/);
assert.match(text(components), /data-rename-meeting/);
assert.match(text(components), /class="meeting-title-rename"/);
assert.doesNotMatch(text(components), /meeting-rename-menu/);
assert.match(text(js), /renameForm && !event\.target\.closest\('\.meeting-row'\)\) renameForm\.requestSubmit\(\)/);
assert.doesNotMatch(text(components), /data-delete-meeting-category/);
assert.match(text(components), /data-selection-key/);
assert.doesNotMatch(text(js), /data-new-meeting-category/);
assert.match(text(js), /event\.target\.matches\('input, textarea'\)\) return/);
assert.doesNotMatch(text(js), /meeting-category/);
assert.match(text(uiData), /const uiData/);
assert.match(text(uiData), /Streaming Paraformer/);
assert.match(text(uiData), /Qwen3-ASR/);
assert.match(text(i18nData), /Qwen3-ASR 1\.7B int8/);
assert.doesNotMatch(text(uiData), /VAD \+ Speaker/);
assert.doesNotMatch(text(uiData), /SenseVoice Small|Whisper Small/);
assert.match(text(i18nData), /所有转写模型都在本地运行，不会将您的隐私上传到网络/);
assert.match(text(i18nData), /Réunions et enregistrements/);
assert.match(text(i18nData), /Modèle de sous-titres en direct/);
assert.match(text(i18nData), /Gérer les modèles →/);
assert.match(text(js), /whisper-large-v3/);
assert.match(text(i18nData), /实时字幕/);
assert.match(text(i18nData), /会后精修/);
assert.match(text(js), /const languageModelDefaults/);
assert.match(text(js), /zh: \{ streaming: 'zipformer-zh-xlarge-streaming-int8', refined: 'funasr-nano-int8'/);
assert.match(text(html), /id="active-refined-model" data-model="funasr-nano-int8">FunASR Nano int8/);
assert.match(text(electronMain), /path\.join\(app\.getPath\('home'\), 'brevia'\)/);
assert.match(text(electronMain), /appendFile\(logFile\(\), line, 'utf8'\)/);
assert.match(text(electronMain), /await migrateDataDir\(\)/);
assert.match(text(js), /en: \{ streaming: 'zipformer-en-streaming-int8', refined: 'qwen3-asr-1\.7b-int8'/);
assert.match(text(js), /const compatibleStreamingModels/);
assert.match(text(html), /src="\.\/i18n\.js"/);
assert.match(text(js), /BreviaI18n\.languageOptions\(locale, t/);
assert.match(text(js), /Object\.values\(modalCopy\)\.forEach/);
assert.match(text(i18n), /new Intl\.DisplayNames/);
assert.match(text(i18n), /defaultMeetingTitle/);
assert.match(text(i18n), /selectionOverview/);
assert.match(text(js), /renderDefaultMeetingTitle\(\)/);
assert.match(text(js), /\(themeLabels\[locale\] \|\| themeLabels\.en\)/);
for (const code of ['ja', 'ko', 'fr', 'de', 'ru']) assert.match(text(html), new RegExp(`data-language="${code}"`));
assert.doesNotMatch(text(js), /音频分析/);
assert.match(text(js), /data-download-model/);
// A cancelled download is terminal: the library button must not stay disabled on "下载中", and dismissing the
// queue must drop cancelled/failed entries so re-downloading works. Guards the stuck-"下载中" regression.
assert.match(text(js), /const downloadInFlight = progress && !progress\.error && !progress\.cancelled/);
assert.match(text(js), /\$\{downloadInFlight \? ' disabled' : ''\}/);
assert.match(text(js), /if \(card\?\.id === 'model-download-queue'\) \{[\s\S]*?if \(progress\.cancelled \|\| progress\.error\) \{ modelDownloads\.delete\(modelId\); requiredModelIds\.delete\(modelId\); \}/);
assert.match(text(js), /prepareModelChoices/);
assert.match(text(js), /t\('VAD 模型'\)/);
assert.match(text(js), /function renderPrepareSelects\(\) \{[\s\S]*?importRecording\.textContent = t\('导入录音'\);/);
assert.match(text(components), /t\('查看完整内容'\)/);
assert.match(text(js), /function renderPauseButton/);
assert.match(text(js), /const translation = payload\.translation \|\| previous\?\.querySelector\('\.translation'\)\?\.textContent;/);
assert.match(text(js), /qwen3-asr-1\.7b-int8/);
assert.match(text(js), /'silero-vad',\s*'online-punct-en-int8'/);
assert.doesNotMatch(text(js), /ten-vad|TEN-VAD/);
assert.doesNotMatch(text(asr), /ten_vad/);
// The download size rides in the tag row as its own tag; the compute/runtime tag was dropped.
assert.match(text(js), /model\.size_bytes/);
assert.match(text(js), /model-library-size/);
assert.doesNotMatch(text(js), /function renderModelLibraryMeta/);
assert.doesNotMatch(text(js), /model-library-meta/);
assert.match(text(js), /model-library-installed/);
// The library foregrounds curated quality/speed ratings and the supported language, demoting the model name to a caption.
assert.match(text(js), /const modelRatings = \{/);
assert.match(text(js), /function renderModelLibraryRatings/);
assert.match(text(js), /model-library-ratings/);
assert.match(text(js), /rating-scale/);
assert.match(text(js), /model-library-headline/);
assert.match(text(js), /model-library-modelname/);
// The model name rides inside the tag row (renderModelLibraryTags), not on a line of its own.
assert.match(text(js), /function renderModelLibraryTags\(model, installed, name\)/);
assert.match(text(js), /class="model-library-modelname">\$\{escapeHtml\(name\)\}/);
// Every catalogued model must carry a rating so no card renders a blank ratings row.
for (const id of ['paraformer-zh-en-int8', 'whisper-large-v3', 'zipformer-zh-xlarge-streaming-int8', 'silero-vad', 'zipvoice-zh-en']) {
  assert.match(text(js), new RegExp(`'${id.replace(/[.]/g, '\\.')}':\\s*\\{ quality:`));
}
assert.match(text(js), /qualityTiers: \['标准', '高', '极高'\]/);
assert.match(text(js), /speedTiers: \['较慢', '均衡', '快'\]/);
assert.match(text(js), /zipformer-multilingual-streaming/);
assert.match(text(js), /active-diarization-model/);
assert.doesNotMatch(text(html), /id="active-model-name"/);
assert.doesNotMatch(text(js), /createElement\('select'\)/);
assert.match(text(js), /modelPicker/);
assert.match(text(logo), /<svg/);
assert.equal(revealGif.readUInt16LE(6), 2400);
assert.equal(revealGif.readUInt16LE(8), 1520);
assert.equal(revealGif.includes(Buffer.from('NETSCAPE2.0')), false);
assert.match(text(backendClient), /this\.stopPromise/);
assert.doesNotMatch(text(electronMain), /require\('@ffmpeg-installer\/ffmpeg'\)/);
assert.match(text(electronMain), /app\.asar\.unpacked/);
assert.match(text(electronMain), /BREVIA_FFMPEG: ffmpeg/);
assert.equal(packageManifest.dependencies['@ffmpeg-installer/ffmpeg'], '1.1.0');
assert.deepEqual(packageManifest.build.asarUnpack, ['node_modules/@ffmpeg-installer/**']);
assert.doesNotMatch(text(backendClient), /setTrackEnabled\(/);
assert.match(text(backendClient), /start_ms: resource\.startMs \+ Math\.round\(offset \/ 16\)/);
assert.match(text(backendClient), /this\.startedAt = performance\.now\(\)/);
assert.match(text(electronMain), /setWindowOpenHandler/);
assert.match(text(electronMain), /will-navigate/);
assert.match(text(electronMain), /process\.on\('unhandledRejection'/);
assert.match(text(electronMain), /process\.on\('uncaughtException'/);
assert.match(text(electronMain), /workerMessage\.parse\(JSON\.parse\(line\)\)/);
assert.match(text(electronMain), /schema_version: z\.literal\(1\)/);
assert.match(text(app), /addEventListener\('unhandledrejection'/);
assert.match(text(app), /addEventListener\('error'/);
assert.match(text(backendClient), /await this\.release\(resource\)/);
assert.match(text(meetings), /function syncBackendMeeting/);
assert.match(text(packWorker), /resource\("fixtures", "backend\/fixtures"\)/);
assert.match(text(packWorker), /"--onedir"/);
assert.doesNotMatch(text(packWorker), /"--onefile"/);
assert.match(text(css), /\.confirmation-actions \.secondary\{margin-top:0/);
assert.match(text(css), /\.model-card \.model-picker\{/);
assert.match(text(js), /prepareModelCard\.addEventListener\('dblclick'/);
assert.match(text(i18nData), /管理语言识别模型的下载、删除与版本信息/);
assert.match(text(i18nData), /Bibliothèque de modèles/);
assert.match(text(html), /data-model="zipformer-zh-xlarge-streaming-int8"/);
assert.match(text(js), /model\.progress/);
assert.match(text(js), /model-download-progress/);
assert.match(text(js), /function formatBytes\(bytes = 0\)/);
assert.match(text(js), /showRefinementComplete/);
assert.doesNotMatch(text(js), /function missingModelIds/);
assert.doesNotMatch(text(js), /function openModelLibraryAt/);
assert.match(text(js), /window\.brevia\.on\('model\.required'/);
assert.match(text(js), /const requiredModelIds = new Set/);
assert.doesNotMatch(text(js), /downloadRequiredModels\(\[\.\.\.requiredModelIds\]\)/);
assert.match(text(js), /pending\.task === 'meeting\.start'/);
assert.match(text(js), /queueModelTask\('meeting\.start', \{ \.\.\.payload, inputs \}/);
assert.match(text(html), /id="task-cards"/);
assert.match(text(html), /data-dismiss-task-card/);
assert.match(text(js), /data-dismiss-task-card/);
assert.match(text(js), /function hideRefinementProgress/);
assert.match(text(js), /transcript\.scrollTop = transcript\.scrollHeight/);
assert.match(text(js), /const isAtLiveBottom = \(\) => transcript\.scrollHeight - transcript\.clientHeight - transcript\.scrollTop <= 32/);
assert.match(text(js), /currentCaption\.scrollLeft = currentCaption\.scrollWidth/);
assert.match(text(js), /currentCaption\.classList\.add\('caption-increment'\)/);
assert.doesNotMatch(text(html), /id="latest"/);
assert.match(text(css), /caption-increment/);
assert.doesNotMatch(text(css), /html\{zoom:/);
assert.match(text(css), /#live-view\.active/);
assert.match(text(css), /\.workspace:has\(#live-view\.active\)/);
assert.match(text(css), /\.transcript\{[^}]*min-width:0/);
assert.match(text(css), /\.transcript\{[^}]*grid-template-rows:auto minmax\(0,1fr\) auto/);
assert.match(text(css), /\.transcript-scroll \.segment\{[^}]*grid-template-columns:5\.5rem minmax\(0,1fr\)[^}]*padding-left:0/);
assert.match(text(css), /\.transcript-scroll \.segment-meta\{[^}]*align-self:flex-start/);
assert.doesNotMatch(text(css), /\.transcript-scroll \.segment p\{[^}]*-webkit-line-clamp/);
assert.match(text(css), /participants-list/);
assert.match(text(tailwind), /\.live-panel \{ @apply col-start-10 col-span-3 grid min-h-0 min-w-0 grid-rows-\[minmax\(14rem,1fr\)_auto_auto\] overflow-hidden/);
assert.match(text(tailwind), /\.live-layout\.is-panel-collapsed \.live-panel/);
assert.match(text(js), /function syncLivePanelToggle/);
assert.match(text(tailwind), /\.participants-list \{ @apply min-h-0 overflow-y-auto/);
assert.match(text(tailwind), /\.live-settings \.flow-select-options button \{ @apply break-words whitespace-normal/);
assert.doesNotMatch(text(js), /live-translation-target|live-toggle|liveInputs/);
assert.match(text(js), /formatSpeakerName\(participant\.name \|\| participant\.speakerId\)/);
assert.match(text(js), /function renderExportModal/);
assert.doesNotMatch(text(js), /data-track="vocals"/);
assert.doesNotMatch(text(js), /data-track="accompaniment"/);
assert.doesNotMatch(text(js), /data-export-detail[\s\S]{0,300}prompt\(/);
assert.doesNotMatch(text(components), /data-detail-tab="tracks"/);
assert.match(text(components), /data-detail-tab="refined"/);
assert.match(text(components), /data-detail-panel="refined"/);
assert.match(text(components), /class="refined-transcript-empty"/);
assert.match(text(meetingDetail), /uiData\.detail\.refinedTranscript = revision === null \? \[\]/);
assert.match(text(app), /finalTranscript\.addEventListener\('click',[\s\S]{0,500}\[data-detail-tab\]/);
assert.doesNotMatch(text(app), /finalTranscript\.addEventListener\('dblclick',[\s\S]{0,500}\[data-detail-tab\]/);
assert.doesNotMatch(text(components), /双轨录音/);
assert.match(text(components), /data-view-full-summary/);
assert.match(text(components), /查看完整内容/);
assert.match(text(js), /function showSeparationProgress/);
assert.match(text(js), /function showSummaryConfigCard/);
assert.match(text(js), /isSummaryAuthenticationError/);
assert.match(text(js), /summary\?\.configuration_required/);
assert.match(text(js), /function showSummaryProgress/);
assert.match(text(js), /summary\.started/);
assert.match(text(js), /pendingModelTasks/);
assert.match(text(js), /pending\.task === 'tts\.synthesize'/);
assert.match(text(js), /function playTts/);
assert.match(text(js), /let ttsSubmitting = false/);
assert.match(text(js), /if \(ttsSubmitting\) return/);
assert.match(text(js), /submit\.setAttribute\('aria-busy', 'true'\)/);
assert.match(text(css), /\.tts-selects \.flow-select-options\.opens-up/);
assert.doesNotMatch(text(js), /将逐字稿发送到所选模型供应商以生成纪要/);
assert.match(text(js), /openModal\('summary-model'\)/);
assert.match(text(js), /renderSummaryDetailModal/);
assert.match(text(js), /sharePanelHtml\('notes'\)/);
assert.match(text(js), /data-format="pdf"/);
assert.match(text(js), /data-regenerate-summary/);
assert.match(text(js), /async function generateMeetingSummary\(meetingId = breviaClient\?\.state\.selectedMeetingId\)/);
assert.match(text(js), /if \(meeting && summaryRequestConfig\(\)\) void generateMeetingSummary\(meeting\.id\);/);
assert.match(text(js), /data-content="notes"/);
// 统一分享面板:三处入口共用平台按钮 + 导出文件按钮。
assert.match(text(js), /function sharePanelHtml/);
assert.match(text(js), /data-share-platform/);
assert.match(text(js), /data-share-file/);
assert.match(text(js), /data-share-export/);
assert.match(text(js), /share\.copyText/);
assert.match(text(js), /share\.openExternal/);
assert.match(text(js), /share\.file/);
// 社交分享只带摘要,邮件/剪贴板带全文。
assert.match(text(js), /function shareExcerpt/);
assert.match(text(js), /function markdownToPlainText/);
// mailto 正文按编码后长度截断,避免 CJK 膨胀撑爆主进程 URL 上限。
assert.match(text(js), /function buildMailto/);
assert.match(text(js), /encodeURIComponent\(text\)\.length > maxEncodedBody/);
assert.match(text(js), /share\.openExternal\(\{ url: buildMailto\(subject, body\) \}\)/);
// macOS 系统原生分享面板:仅在 darwin 上出现,分享文件走 share.system。
assert.match(text(js), /window\.brevia\?\.platform === 'darwin'/);
assert.match(text(js), /window\.brevia\?\.share\.system/);
assert.match(text(preload), /system: invoke\('share\.system'\)/);
assert.match(text(preload), /platform: process\.platform/);
assert.match(text(electronMain), /new ShareMenu\(sharingItem\)\.popup/);
assert.match(text(electronMain), /System share is only available on macOS/);
// 详情页「转发」改为打开分享面板,不再直接打包。
assert.doesNotMatch(text(js), /data-share-detail'\)\.addEventListener\('click', async/);
// preload 暴露 share API;主进程只放行 https 与 mailto。
assert.match(text(preload), /copyText: invoke\('share\.copy-text'\)/);
assert.match(text(preload), /openExternal: invoke\('share\.open-external'\)/);
assert.match(text(preload), /file: invoke\('share\.file'\)/);
assert.match(text(electronMain), /\^\(https:\\\/\\\/\|mailto:\)/);
assert.match(text(js), /separation\.progress/);
assert.match(text(js), /speakerProfile\.samples/);
assert.match(text(js), /speakerProfile\.deleteSample/);
assert.match(text(asr), /Models \{segmentation_id\}, \{embedding_id\} are not installed/);
assert.match(text(asr), /expected_checksum = model\.get\("archive_sha256"\)/);
assert.match(text(asr), /if digest != expected_checksum:/);
assert.match(text(electronMain), /meeting\.bundle/);
assert.match(text(electronMain), /error\.code === 'ENOENT'/);
assert.match(text(electronMain), /configuration_required: true/);
assert.match(text(electronMain), /summary\.config\.save/);
assert.match(text(js), /punct-ct-transformer-zh-en-int8/);
assert.match(text(js), /online-punct-en-int8/);
assert.doesNotMatch(text(js), /const modelSizes/);
assert.match(text(js), /const modelSize = \(modelId\) => modelCatalog\.find/);
const frontendModelIds = [...text(js).match(/const modelIds = \[([\s\S]*?)\];/)[1].matchAll(/'([^']+)'/g)].map(([, id]) => id);
// llama-chat GGUF models are managed through the summary modal, not the generic
// model library. llama-translation models (caption translation) are now shown in
// the generic model library, so they're included in modelIds.
const libraryManifestIds = modelManifest.filter(({ kind }) => kind !== 'llama-chat').map(({ id }) => id);
assert.deepEqual(new Set(frontendModelIds), new Set(libraryManifestIds));
assert.match(text(js), /data-delete-model/);
assert.match(text(css), /::-webkit-scrollbar-thumb\{/);
assert.match(text(css), /:where\(html,body,\*\)\.is-scrolling\{scrollbar-color:#aaa transparent/);
assert.doesNotMatch(text(css), /scrollbar-color:#666 transparent/);
assert.match(text(css), /html\[data-theme=dark\] \.brand img,html\[data-theme=dark\] \.onboarding-brand\{filter:invert\(\)/);
assert.match(text(css), /html\[data-theme=dark\] \.secondary,html\[data-theme=dark\] \.meeting-color,html\[data-theme=dark\] \.model-icon\{color:#eee;border-color:#eee/);
assert.match(text(css), /html\[data-theme=dark\] \.processing-bar i,html\[data-theme=dark\] \.model-download-progress i\{background-color:#fff/);
assert.match(text(js), /document\.addEventListener\('scroll',[\s\S]{0,300}is-scrolling/);
assert.match(text(js), /setTimeout\(\(\) => scroller\.classList\.remove\('is-scrolling'\), 2000\)/);
assert.match(text(js), /meeting\.exampleLocale === locale/);
assert.match(text(js), /function selectLibraryNav/);
assert.match(text(js), /await refreshBackendMeetings\(\)/);
assert.match(text(js), /let updateAvailable = false/);
assert.match(text(js), /updateNoticeProgressBar\.style\.transform/);
assert.match(text(js), /renderUpdateNotice\(\);/);
assert.match(text(tailwind), /\.software-update-notice > i/);
assert.match(text(backendClient), /async prepare\(\{ mic, system \}\)/);
assert.match(text(backendClient), /async previewMic\(\)/);
assert.match(text(backendClient), /async stopPreview\(\)/);
assert.match(text(js), /async function previewMicrophone/);
assert.match(text(js), /transcript\.discarded/);
assert.match(text(js), /window\.brevia\.meeting\.refine\(\{ meeting_id: meeting\.id \}\)/);
assert.match(text(backendClient), /await this\.capture\.prepare\(inputs\)[\s\S]*window\.brevia\.meeting\.start\(payload\)/);
assert.match(text(backendClient), /系统音频.*未产生音频数据/);
assert.match(text(backendClient), /this\.state\.meeting\?\.id \|\| this\.capture\?\.meetingId/);
assert.match(text(backendClient), /await this\.capture\.stop\(\)/);
assert.match(text(electronMain), /ipcMain\.handle\('permissions\.status'/);
assert.match(text(electronMain), /systemPreferences\.askForMediaAccess\('microphone'\)/);
assert.ok(packageManifest.build.mac.extendInfo.NSAudioCaptureUsageDescription);
assert.ok(packageManifest.build.mac.extendInfo.NSMicrophoneUsageDescription);
assert.match(text(electronMain), /MacCatapLoopbackAudioForScreenShare/);
assert.match(text(electronMain), /autoUpdater\.downloadUpdate\(\)/);
assert.match(text(electronMain), /autoUpdater\.quitAndInstall\(\)/);
assert.match(text(electronMain), /releases\/latest/);
assert.match(text(js), /navigator\.mediaDevices\.getUserMedia\(\{ audio: true \}\)/);
assert.match(text(js), /window\.brevia\.permissions\.requestMicrophone\(\)/);
assert.match(text(js), /window\.brevia\?\.update\?\.check/);
assert.match(text(js), /window\.brevia\.update\.install/);
assert.match(text(electronMain), /ipcMain\.handle\('metrics\.record'/);
assert.match(text(electronMain), /error\.code === 'EPIPE'/);
assert.match(text(electronMain), /workerRequestTimeouts = new Map/);
assert.match(text(electronMain), /Worker request timed out/);
assert.match(text(electronMain), /clearTimeout\(pending\.timer\)/);
assert.doesNotMatch(text(electronMain).match(/workerRequestTimeouts = new Map\(\[[\s\S]*?\]\);/)?.[0] || '', /meeting\.(audio|pause|stop)/);
assert.doesNotMatch(text(electronMain).match(/const timer = timeout && setTimeout\([\s\S]*?\}, timeout\);/)?.[0] || '', /stopProcess/);
assert.match(text(backendClient), /navigator\.mediaDevices\.getDisplayMedia/);
assert.match(text(backendClient), /systemAudio: 'include'/);
assert.match(text(backendClient), /stream\.getAudioTracks\(\)\.length/);
assert.match(text(electronMain), /systemAudioSupported/);
assert.match(text(electronMain), /require\('node:os'\)/);
assert.doesNotMatch(text(electronMain), /app\.getSystemVersion/);
assert.match(text(electronMain), /createDisplayMediaHandler\(desktopCapturer, writeLog\)/);
assert.doesNotMatch(text(js), /checkForUpdates\(\{ silent: true \}\)/);
assert.match(text(js), /if \(!silent\) showToast\(error\.message\)/);
assert.match(text(js), /const requiredModelsForLanguage/);
assert.match(text(js), /const punctuation = language === 'en' \? 'online-punct-en-int8'/);
assert.match(text(js), /onboardingModelIds = models\.filter\(\(modelId\) => !modelPaths\.has\(modelId\)\)/);
assert.match(text(js), /modelPaths\.has\(modelId\) \? \(modelLabels\[locale\] \|\| modelLabels\.en\)\.installed/);
assert.match(text(js), /function downloadRequiredModels/);
assert.match(text(js), /void Promise\.all\(models\.map\(downloadRequiredModel\)\)/);
assert.match(text(js), /function scheduleRequiredModelsCardRender/);
assert.match(text(js), /requestAnimationFrame\(\(\) => \{\s*requiredModelsRenderFrame = undefined;\s*renderRequiredModelsCard\(\);/);
assert.match(text(js), /const scrollTop = card\.querySelector\('ul'\)\?\.scrollTop \|\| 0;/);
assert.match(text(js), /card\.querySelector\('ul'\)\.scrollTop = scrollTop;/);
assert.equal([...text(js).matchAll(/id = 'model-download-queue'/g)].length, 1);
assert.doesNotMatch(text(js), /id = 'required-models'|data-minimize-required-models|requiredModelsCardDismissed/);
assert.match(text(js), /function renderRequiredModelsCard\(\) \{[\s\S]{0,240}renderModelDownloadQueue\(\);/);
assert.match(text(html), /id="mini-playback"/);
assert.match(text(html), /id="mini-playback-close"[^>]*aria-label="关闭播放"/);
assert.match(text(js), /function renderMiniPlayback/);
assert.match(text(js), /miniPlaybackClose\.addEventListener\('click',[\s\S]{0,180}playbackStarted = false;[\s\S]{0,100}playerAudio\.pause\(\);[\s\S]{0,100}playerAudio\.currentTime = 0;/);
assert.match(text(js), /miniPlayback\.addEventListener\('dblclick'/);
assert.match(text(css), /\.required-models-card li small\{[^}]*overflow-wrap:anywhere/);
assert.match(text(css), /\.task-card-close\{[^}]*width:clamp\(1rem,2vw,1\.25rem\)/);
assert.match(text(css), /\.mini-playback\{/);
assert.match(text(js), /function openOnboardingLanguage/);
assert.match(text(js), /function initializeLanguageWheel/);
assert.match(text(js), /data-language-wheel-value/);
assert.match(text(js), /onboarding-actions onboarding-page-copy/);
assert.match(text(js), /onboarding-language-page/);
assert.doesNotMatch(text(js), /data-onboarding-exit/);
assert.match(text(js), /onboarding-page/);
assert.match(text(js), /if \(window\.BreviaOnboarding\.isFirstLaunch\(\)\) openOnboardingLanguage\(\);[\s\S]{0,220}initializationPromise = breviaClient\.initialize\(\)\.then/);
assert.match(text(js), /if \(initializationPromise\) await initializationPromise;[\s\S]{0,160}openOnboardingPermissions\(\); return;/);
assert.match(text(js), /window\.brevia\.on\('app\.maintenance'/);
assert.match(text(js), /void window\.brevia\.maintain\(\)/);
assert.match(text(js), /void loadSummaryConfig\(\)\.catch/);
assert.match(text(js), /updateOnboardingLanguageCopy/);
assert.match(text(js), /function openOnboardingSetup/);
assert.match(text(js), /new Set\(window\.BreviaOnboarding\.defaultMeetingLanguages\(locale\)\)/);
assert.match(text(js), /className = 'onboarding-page onboarding-active'/);
assert.match(text(js), /onboarding-page onboarding-active onboarding-\$\{kind\}-overlay/);
assert.doesNotMatch(text(js), /onboarding-page onboarding-active onboarding-\$\{kind\}-page/);
assert.doesNotMatch(text(js), /document\.body\.classList\.(?:add|remove)\('onboarding-active'\)/);
assert.match(text(css), /\.onboarding-page\.onboarding-active\{[^}]*position:fixed[^}]*overflow-y:auto/);
assert.match(text(css), /\.onboarding-page:before\{[^}]*-webkit-app-region:drag/);
assert.match(text(css), /body:has\(\.onboarding-page\) \.app-shell\{display:none/);
assert.doesNotMatch(text(css), /\*\{scrollbar-gutter:stable/);
assert.match(text(js), /data-onboarding-estimate/);
assert.match(text(js), /onboardingModelListLabel/);
assert.match(text(js), /data-onboarding-language-models/);
assert.match(text(js), /data-onboarding-feature-models/);
assert.match(text(js), /onboardingSecurityCopy/);
assert.match(text(js), /src="\.\/assets\/brevia-logo\.svg"/);
assert.match(text(js), /我们正在为您准备需要的语音识别模型。/);
assert.match(text(js), /onboarding-language-selection/);
assert.match(text(js), /modelSize\(modelId\)/);
assert.match(text(js), /<li><span>\$\{escapeHtml\(modelDisplayName\(modelId\)\)\}<\/span><small>/);
assert.match(text(css), /\.onboarding-model-preview\{[^}]*border-left/);
assert.match(text(css), /\.onboarding-setup-page header\{[^}]*justify-items:center[^}]*text-align:center/);
assert.match(text(css), /\.onboarding-language-selection\{[^}]*height:calc\(var\(--spacing\) \* 64\)/);
// Onboarding quality/performance preference drives which models get selected, coupled to runtime defaults via preferredModelsForLanguage.
assert.match(text(js), /const modelPreference = \(\)/);
assert.match(text(js), /const languageModelPreferences = \{/);
assert.match(text(js), /function onboardingPreferenceControl/);
assert.match(text(js), /name="onboarding-model-preference"/);
assert.match(text(js), /brevia-model-preference/);
assert.match(text(js), /const preset = languageModelPreferences\[modelPreference\(\)\]/);
assert.match(text(js), /preferenceQuality: '质量优先'/);
assert.match(text(css), /\.onboarding-preference-option\{/);
assert.match(text(js), /data-onboarding-back-language/);
assert.match(text(js), /function openOnboardingPermissions/);
assert.match(text(js), /data-request-onboarding-permission/);
assert.match(text(js), /onboarding-permission-action/);
assert.match(text(js), /onboarding-permission-granted/);
assert.match(text(js), /data-onboarding-mic-level/);
assert.match(text(js), /breviaClient\?\.previewMic\(\)/);
assert.match(text(js), /const granted = permissionGranted\(permission\);/);
assert.match(text(js), /data-open-screen-settings/);
assert.match(text(css), /\.onboarding-permission-title\{[^}]*align-items:center/);
assert.match(text(css), /\.onboarding-mic-meter\{[^}]*width:calc\(var\(--spacing\) \* 32\)/);
assert.match(text(js), /const permissionPoll = window\.setInterval/);
assert.match(text(js), /window\.clearInterval\(permissionPoll\)/);
assert.match(text(js), /const placeholders = steps\.map[\s\S]*?onboarding-permission-complete/);
assert.match(text(js), /function openOnboardingLanguage[\s\S]*?openOnboardingPermissions\(\);/);
assert.match(text(js), /dismissOnboardingPage\(\(\) => \{\s*onboardingPreviewLocale = undefined;\s*applyLanguage\(nextLocale, true\);\s*openOnboardingPermissions\(\);/);
assert.match(text(js), /data-skip-onboarding-permissions/);
assert.match(text(js), /dismissOnboardingPage\(openOnboardingSetup\)/);
assert.doesNotMatch(text(js), /function openOnboardingWelcome/);
assert.match(text(js), /const page = onboardingPage/);
assert.match(text(js), /page\.querySelector\('\[name="locale"\]'\)\.value/);
assert.match(text(js), /finally \{\s*switchingLanguage = false/);
for (const selector of ['.settings-grid', '.meeting-list', '#meeting-form .form-grid', '.final-transcript', '.notes', '.live-panel', '#tts-chat', '#model-download-queue']) {
  assert.match(text(js), new RegExp(selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
}
assert.match(text(js), /rerendered\.push\(batchToolbar, updateNotice/);
assert.doesNotMatch(text(html), /原始录音与每版逐字稿均保存在本机/);
assert.doesNotMatch(text(i18nData), /原始录音与每版逐字稿均保存在本机/);
assert.doesNotMatch(text(js), /function openOnboardingMeetingLanguages/);
assert.doesNotMatch(text(js), /function openOnboardingModels/);
assert.match(text(js), /data-download-onboarding-models/);
assert.match(text(js), /data-onboarding-model-selection/);
assert.match(text(js), /' checked disabled'/);
assert.doesNotMatch(text(js), /modelPaths\.has\(modelIds\[sourceIndex\]\) \? '✓'/);
assert.match(text(js), /data-download-onboarding-selected/);
assert.match(text(js), /onboardingModelIds = models/);
assert.match(text(js), /showOfflineTranscriptionReady/);
assert.doesNotThrow(() => new Function(text(js)));
assert.doesNotMatch(text(electronMain), /showMessageBox/);
assert.match(text(electronMain), /permissions\.open-screen-settings/);
assert.match(text(electronMain), /permissions\.open-microphone-settings/);
assert.match(text(electronMain), /Privacy_ScreenCapture/);
assert.match(text(electronMain), /Privacy_Microphone/);
assert.match(text(electronMain), /spawn\('open', \['x-apple\.systempreferences/);
assert.doesNotMatch(text(electronMain), /useSystemPicker/);
assert.match(text(electronMain), /requestSingleInstanceLock/);
assert.match(text(electronMain), /function stopActiveMeetingBeforeQuit/);
assert.match(text(electronMain), /worker\.request\('meeting\.stop'/);
assert.match(text(electronMain), /event\.preventDefault\(\)/);
assert.match(text(electronMain), /meeting\.export-many/);
assert.match(text(js), /const button = event\.currentTarget/);
assert.doesNotMatch(text(js), /await breviaClient\.pause\(!paused\)[\s\S]{0,200}event\.currentTarget/);
assert.doesNotMatch(text(app), /document\.querySelector\('#end-meeting'\)[\s\S]{0,800}meeting\.refine/);
assert.match(text(app), /data-refine-model[\s\S]{0,500}window\.brevia\.meeting\.refine/);
assert.match(text(js), /let followLiveTranscript = true/);
assert.match(text(js), /meetingActive = true;\s*seconds = 0;\s*const pauseButton = document\.querySelector\('#pause'\);\s*pauseButton\.dataset\.paused = 'false';\s*renderPauseButton\(\);/);
assert.match(text(js), /transcript\.scrollTop = transcript\.scrollHeight/);
assert.doesNotMatch(text(js), /segment\.offsetTop - \(transcript\.clientHeight - segment\.offsetHeight\) \/ 2/);
assert.match(text(js), /liveSpeakers\.set/);
assert.match(text(js), /const maxLiveSegments = 500/);
assert.match(text(js), /while \(liveSegments\.size > maxLiveSegments\)/);
assert.match(text(js), /liveConfig = \{ language: language \|\| 'auto', streaming_model_id: streamingModelId \|\| '', refined_model_id: refinedModelId \|\| '', target_language: payload\.target_language \|\| null \}/);
assert.match(text(js), /await window\.brevia\.meeting\.reconfigure\(\{ meeting_id: meetingId, \.\.\.changes \}\)/);
assert.doesNotMatch(text(js), /setTrackEnabled\(/);
assert.doesNotMatch(text(js), /uiData\.live\.status/);
assert.match(text(js), /segment\.classList\.remove\('is-active'\)/);
assert.match(text(js), /示例会议及录音已删除/);
assert.match(text(js), /function syncPlaybackTranscript/);
assert.match(text(js), /\['zh', 'en'\]\.includes\(targetLanguage\) && !voiceId/);
assert.match(text(js), /const ttsLanguages = \['zh', 'en'\]/);
assert.match(text(electronMain), /target_language: z\.enum\(\['zh', 'en', 'es', 'ko', 'fr', 'de', 'ru'\]\)/);
assert.match(text(electronMain), /translationPending: z\.boolean\(\)\.optional\(\)/);
assert.match(text(electronMain), /translationPending: floatingCaptionState\.translationPending/);
assert.match(text(js), /function showRefinementProgress/);
assert.match(text(js), /\$\{copy\.title\} - \$\{refinementMeetingTitle\}/);
assert.match(text(js), /segment\.version\.startsWith\('postprocess'\)/);
assert.match(text(js), /playback\.mix \|\| meeting\.audio\.playback\.mic/);
assert.match(text(js), /segment\.is-active/);
assert.match(text(js), /body\.scrollTo/);
assert.match(text(i18nData), /Aún no se ha generado el resumen/);
assert.match(text(i18nData), /Speaker diarization/);
for (const copy of ['ローカル会議', '로컬 회의', 'Réunion locale', 'Lokale Besprechung', 'Локальная встреча']) assert.match(text(i18nData), new RegExp(copy));
assert.doesNotMatch(text(css), /\.status\.complete:before/);
assert.match(text(css), /\.page-head>div\{[^}]*min-height:/);
assert.doesNotMatch(text(js), /renderModelRow/);
assert.match(text(components), /id="installed-models"[\s\S]*data-settings-modal="models"/);
assert.match(text(js), /Object\.values\(modalCopy\)\.forEach/);
assert.match(text(components), /class="transcript-body"/);
assert.match(text(components), /data-start=/);
assert.match(text(components), /data-segment-id=/);
assert.match(text(components), /class="segment-copy"/);
assert.match(text(js), /segmentContextMenu/);
assert.match(text(js), /addProfileSample/);
assert.match(text(js), /data-create-segment-profile/);
assert.match(text(i18nData), /Create voiceprint/);
assert.match(text(css), /\.final-transcript\{[^}]*height:100%[^}]*overflow:hidden/);
assert.match(text(css), /#prepare-view\.active\{[^}]*height:calc\(100dvh - 4rem\)/);
assert.match(text(css), /#detail-view\.active\{[^}]*height:calc\(100dvh - 4rem\)/);
assert.match(text(css), /\.transcript-body,.dual-track-panel\{(?=[^}]*font-size:16px)(?=[^}]*scroll-behavior:smooth)(?=[^}]*padding-top:calc\(var\(--spacing\) \* 5\))(?=[^}]*padding-right:calc\(var\(--spacing\) \* 4\))(?=[^}]*overflow-y:auto)/);
assert.match(text(css), /\.dual-track-empty\{[^}]*padding-block:calc\(var\(--spacing\) \* 8\)/);
assert.match(text(css), /\.refined-transcript-empty\{[^}]*padding-block:calc\(var\(--spacing\) \* 8\)/);
assert.doesNotMatch(text(css), /\.dual-track-empty\{[^}]*border-(?:top|bottom|style|width)/);
assert.match(text(css), /scrollbar-gutter:stable/);
assert.match(text(css), /\.transcript\{[^}]*grid-template-rows:auto minmax\(0,1fr\) auto/);
assert.match(text(css), /::-webkit-scrollbar-thumb/);
assert.match(text(css), /\.sidebar\{[^}]*position:sticky/);
assert.match(text(css), /\.input-meter/);
assert.match(text(css), /\.selection-marquee\{/);
assert.match(text(css), /\.meeting-row\.is-selected\{/);
assert.match(text(html), /ui-data\.js[\s\S]*ui-components\.js[\s\S]*app\.js/);
// 纪要模态框的真实渲染产物：字段可见性、内置模型清单、凭据回填、转义和八语言标签。
const summaryAppSource = text(app);
const summaryFn = (name) => { const start = summaryAppSource.indexOf(`function ${name}(`); return summaryAppSource.slice(start, summaryAppSource.indexOf('\n}\n', start) + 2); };
const summaryConst = (decl, multiline = false) => { const start = summaryAppSource.indexOf(decl); return multiline ? summaryAppSource.slice(start, summaryAppSource.indexOf('\n};', start) + 3) : summaryAppSource.slice(start, summaryAppSource.indexOf('\n', start) + 1); };
const summaryNodes = { h2: { textContent: '' }, '.modal-title p': { textContent: '' }, '.modal-body': { innerHTML: '' } };
const summaryContext = {
  locale: 'zh',
  t: (value) => localeContext.window.BreviaLocaleData.catalog.zh.labels[value] || value,
  summaryModelCopy: localeContext.window.BreviaLocaleData.appCopy.summaryModelCopy,
  modelLabels: localeContext.window.BreviaLocaleData.appCopy.modelLabels,
  builtinModelIntro: { 'qwen3.5-2b-q4km': { zh: '质量与速度均衡' } },
  renderModelLibraryRatings: () => '<span>质量：极高 · 速度：均衡</span>',
  formatBytes: (bytes) => `${bytes}B`,
  modelDownloads: new Map(),
  settingsModal: { querySelector: (selector) => summaryNodes[selector] },
};
runInNewContext(`${text(components)}\nthis.escapeHtml = escapeHtml;`, summaryContext);
runInNewContext(`${summaryConst('const summaryProviders = ')}${summaryConst('const summaryProviderPresets = ', true)}\n${summaryFn('summaryProviderLabel')}${summaryFn('summaryProviderEntry')}${summaryFn('renderBuiltinSummaryModels')}${summaryFn('renderSummaryModelModal')}`, summaryContext);
const summaryCatalogModels = [{ id: 'qwen3.5-2b-q4km', name: 'Qwen 3.5 2B', kind: 'llama-chat', size_bytes: 100 }, { id: 'gemma3-1b-q8', name: 'Gemma 3 1B', kind: 'llama-chat' }, { id: 'whisper-large-v3', name: 'Whisper', kind: 'asr' }];
const renderSummaryModal = (provider, { providers = {}, installed = [] } = {}) => {
  summaryContext.modelCatalog = summaryCatalogModels;
  summaryContext.modelPaths = new Map(installed.map((id) => [id, `/tmp/${id}`]));
  summaryContext.summaryConfig = { version: 2, provider, providers };
  summaryContext.selectedBuiltinModel = '';
  summaryContext.renderSummaryModelModal();
  return summaryNodes['.modal-body'].innerHTML;
};
let summaryHtml = renderSummaryModal('built-in', { installed: ['qwen3.5-2b-q4km'] });
assert.match(summaryHtml, /data-builtin-model-id="qwen3\.5-2b-q4km"/);
assert.match(summaryHtml, /data-download-summary-model="gemma3-1b-q8"/);
assert.match(summaryHtml, /质量与速度均衡/);
assert.match(summaryHtml, /质量：极高 · 速度：均衡/);
assert.doesNotMatch(summaryHtml, /whisper-large-v3/);
assert.match(summaryHtml, /name="model" value="qwen3\.5-2b-q4km"/);
assert.doesNotMatch(summaryHtml, /name="apiKey"|name="endpoint"/);
assert.doesNotMatch(summaryHtml, /type="submit" disabled/);
// 一个内置模型都没装时无从选择，保存必须禁用。
summaryHtml = renderSummaryModal('built-in');
assert.match(summaryHtml, /type="submit" disabled/);
assert.doesNotMatch(summaryHtml, /data-builtin-model-id/);
for (const provider of ['claude', 'openai', 'openrouter']) {
  summaryHtml = renderSummaryModal(provider);
  assert.doesNotMatch(summaryHtml, /name="endpoint"/, `${provider} must not expose an endpoint field`);
  assert.match(summaryHtml, /name="apiKey"/, `${provider} needs an api key field`);
  assert.match(summaryHtml, /name="model"/, `${provider} needs a model field`);
  assert.doesNotMatch(summaryHtml, /data-builtin-model-id|data-download-summary-model/);
}
for (const provider of ['custom-openai', 'custom-claude']) {
  assert.match(renderSummaryModal(provider), /name="endpoint"[^>]*type="url"/, `${provider} needs an endpoint field`);
}
// 已存凭据只回填模型和圆点占位长度，密钥引用和明文都不进 DOM。
summaryHtml = renderSummaryModal('openai', { providers: { openai: { model: 'gpt-4.1-mini', keyReference: 'summary-1', keyLength: 12 } } });
assert.match(summaryHtml, /name="model" value="gpt-4\.1-mini"/);
assert.match(summaryHtml, /name="apiKey"[^>]*type="password"/);
assert.match(summaryHtml, /name="apiKey"[^>]*autocomplete="new-password"/);
assert.match(summaryHtml, /name="apiKey"[^>]*placeholder="••••••••••••"/);
assert.doesNotMatch(summaryHtml, /summary-1/);
// 输入上限必须和主进程 zod 的上限一致，否则超长值要到主进程才被拒。
assert.match(summaryHtml, /name="apiKey"[^>]*maxlength="512"/);
assert.match(summaryHtml, /name="model"[^>]*maxlength="128"/);
assert.match(text(electronMain), /model: z\.string\(\)\.trim\(\)\.min\(1\)\.max\(128\)/);
assert.match(text(electronMain), /keyLength: z\.number\(\)\.int\(\)\.positive\(\)\.max\(512\)/);
summaryHtml = renderSummaryModal('openai');
for (const id of ['built-in', 'claude', 'openai', 'openrouter', 'custom-openai', 'custom-claude']) {
  assert.match(summaryHtml, new RegExp(`data-flow-select-choice="provider" data-value="${id}"`), `missing provider choice ${id}`);
}
for (const code of ['zh', 'en', 'es', 'ja', 'ko', 'fr', 'de', 'ru']) {
  summaryContext.locale = code;
  const copy = localeContext.window.BreviaLocaleData.appCopy.summaryModelCopy[code];
  summaryHtml = renderSummaryModal('custom-openai');
  assert.ok(summaryHtml.includes(copy.providers['custom-openai']), `${code} is missing the custom-openai label`);
  assert.ok(summaryHtml.includes(copy.save), `${code} is missing the save label`);
  assert.equal(summaryNodes.h2.textContent, copy.title);
}
summaryContext.locale = 'zh';
summaryContext.modelCatalog = [{ id: '"><img src=x onerror=alert(1)>', name: '<script>alert(1)</script>', kind: 'llama-chat' }];
summaryContext.modelPaths = new Map();
summaryContext.summaryConfig = { version: 2, provider: 'built-in', providers: {} };
summaryContext.renderSummaryModelModal();
assert.doesNotMatch(summaryNodes['.modal-body'].innerHTML, /<img|<script>/);
console.log('UI structure checks passed.');
